ja2-stracciatella/ja2-stracciatella

Build/Tactical/Tactical_Save.cc
BB PR 20, fixing #143
http://thepit.ja-galaxy-forum.com/index.php?t=msg&th=16589&goto=250723&#msg_250723
=> fix #143, adjusted from BP forum

Build/Tactical/Handle_Items.cc, Build/Tactical/Rotting_Corpses.cc
Bitbucket Comments:
@lynxlynxlynx:
Judging from the diff, this is a prime candidate for refactoring — both chunks are the same (the same stop-spot typo suggest c/p).
@selaux:
True, I'll check what I can do.
=> Fix corpses and items appearing in water.

Build/Strategic/MapScreen.cc, Build/Strategic/Map_Screen_Helicopter.cc, Build/Strategic/Map_Screen_Helicopter.h, Build/Strategic/Map_Screen_Interface_Map.cc, Build/Strategic/StrategicMap.cc
some Cleanup in Map_Screen_Helicopter. Stuff that I noticed when working on one of the segfaults. Some of this is purely cosmetic, some is refactoring. Shouldn't hurt anybody in either way. I also tried to split it up into well-sorted commits. Comments welcome :)
=> Helicopter cleanup

Build/Credits.cc
- Fixed glitches by restoring background rectangle below scrolling text after rendering text
- Credits screen now has a background mouse region with the default cursor
=> Fix remaining credits issues

README.md
=> Add homepage to README and remove news.

sgp/MemMan.cc, sgp/MemMan.h, sgp/SGP.cc
discussion: #258 
this PR is for the case we agree on deleting it.
=> Remove extreme memory debugging

Build/JAScreens.cc, Build/Strategic/Assignments.cc, Build/Strategic/Assignments.h, Build/TileEngine/Explosion_Control.cc
only little adjustments besides reenabling the code. Tested, worked.
=> Fix #76 by reenabling the brothel

Build/AniViewScreen.cc, Build/GameScreen.cc, Build/TileEngine/Render_Dirty.cc, Build/TileEngine/Render_Dirty.h, Build/Utils/WordWrap.cc, docs/archeology/TODO
Both calls do exactly the same. I tested by printing the towns loyalty with both functions to check for differences:
=> Resolve todo0017

Build/Tactical/Animation_Control.cc, docs/archeology/TODO
The proposed solution is the only one that makes sense. The only use of this in Soldier_Control.cc shows a lot of similarity to gubAnimSwatSpeeds which looks quite the same
=> resolve TODO0011

Build/Strategic/Auto_Resolve.cc, Build/Strategic/Strategic_Movement.cc
This is more of a workaround, but it removes SEGFAULTs so I think it's worth it.
=> Fix #253 by eventually invalidating gpBattleGroup in RemoveGroup

Build/Tactical/FOV.cc
just whitespace fixes. This file lookd so ugly I needed to fix it :)
=> FOV Cleanup

Makefile
uninstall is much more common and expected
=> Makefile: added synonym for deinstall

Build/TileEngine/Phys_Math.cc, Build/TileEngine/Phys_Math.h, Build/TileEngine/Physics.cc, Build/TileEngine/Physics.h, docs/archeology/FIXME
open fixme, purely coding style.
=> Remove typedef real

Build/TileEngine/RenderWorld.cc
Reverts ja2-stracciatella/ja2-stracciatella#281
=> Revert "ApplyScrolling: buffer the top border, so npcs there can be shot in t…"

_build/solution-vs10e/ja2.vcxproj
- Fixes building with Visual Studio
=> Add Debug_Pages to visual studio solution.

changes.md
not final, just less work for later.
=> changes: update up to now

Makefile, Release-checklist.md
=> added release process documentation

Build/Tactical/Handle_UI.cc, Build/TileEngine/RenderWorld.cc, Build/TileEngine/RenderWorld.h
=> Sector exit

Build/TacticalAI/NPC.cc
fixes #327. removed two newlines that do not belong there, too.
=> only call GetProfile when we expect a valid profile

Build/Strategic/Map_Screen_Interface_Map.cc
=> correct some asserts to reflect higher resolutions

Build/Strategic/MapScreen.cc, Build/Strategic/MapScreen.h, Build/Tactical/Interface_Panels.cc, Build/Tactical/Interface_Panels.h, externalized/game.json, src/policy/DefaultGamePolicy.cc, src/policy/GamePolicy.h
as previously done by vxx and 1.13, switchable via gui_extras in game.json
=> integrate gui_extras

Build/Tactical/LOS.cc, Build/Tactical/PathAI.cc, Build/Tactical/Points.cc, docs/archeology/FIXME
=> resolve FIXME: (DOUBLE): casts placed wrong

Build/Strategic/Game_Event_Hook.cc, Build/Strategic/Game_Event_Hook.h, Build/Strategic/Game_Events.cc, Build/Strategic/Hourly_Update.cc, Build/Strategic/Hourly_Update.h, docs/archeology/FIXME
removing of gEventNames is a bit off-topic, but was spotted here and would have had a merge conflict if splitted. If we decide to not merge one of the two things, I'll gladly split the PR.
=> Fixme minute update

docs/archeology/FIXME
=> remove an old fixme that was already fixed

Build/Strategic/Map_Screen_Interface.cc, Build/Strategic/Strategic_Movement.cc, Build/Strategic/Strategic_Movement.h, docs/archeology/FIXME
pretty straight-forward inline
=> Fixme inline vehicle has fuel

docs/archeology/FIXME, sgp/MemMan.cc
=> Fixme remove mem total

Build/Strategic/StrategicMap.cc, Build/Tactical/Handle_Items.cc, Build/Tactical/Handle_UI.cc, Build/Tactical/LoadSaveSoldierType.cc, Build/Tactical/OppList.cc, Build/Tactical/Overhead.cc, Build/Tactical/PathAI.cc, Build/Tactical/Soldier_Ani.cc, Build/Tactical/Soldier_Control.cc, Build/Tactical/Soldier_Control.h, Build/Tactical/Soldier_Tile.cc, Build/Tactical/TeamTurns.cc, Build/TacticalAI/AIMain.cc, Build/TacticalAI/DecideAction.cc, Build/TacticalAI/Movement.cc
My try at fixing #328. Lets see if it works (last commit actually implements the change).
=> Create temporary UINT16 variables when saving/loading

Build/Utils/Debug_Pages.cc, Build/Utils/Debug_Pages.h
Seems I forgot to implement a function for char strings :wink:
=> Fix #337: Char strings not displaying correctly in debug pages

CMakeLists.txt
XCode generation resulted in broken XCode file otherwise
=> Fix definitions for XCode

.travis.yml
Lets check if we have more coverity issues...
=> Fix coverity build command

Build/Laptop/BobbyRMailOrder.cc
small cleanup done while investigating #394
=> Bobby Ray's mailer bits and pieces

Build/GameLoop.cc, Build/SaveLoadGame.cc, sgp/FileMan.cc, sgp/FileMan.h
=> Use proper type for disk space

Build/Tactical/PathAI.cc
=> Fix types in pathing

_build/lib-slog/slog/slog.c, _build/lib-slog/slog/slog.h
Not sure when this went missing...
=> Add missing debug string

Build/Tactical/Interface_Items.cc, Build/Tactical/Interface_Items.h, Build/Tactical/ShopKeeper_Interface.cc
Fixes #424 #423.
- Flo now also gets discounts for `IC_WEAPON` class items (according to her merc description)
- Extracted attachment star coloring into own function and check for `IC_LAUNCHER` class instead of talon launcher
- Use extracted function in dealer inventory
=> Fix issues with weapons dealers

src/DefaultContentManager.cc
=> Fix type for variable declaration.

.travis.yml
Working in the direction of nightly builds / builds released through travis...
=> Run travis builds on osx as well

Build/Tactical/LoadSaveMercProfile_unittest.cc, Build/Utils/_DutchText.cc, Build/Utils/_FrenchText.cc, Build/Utils/_GermanText.cc, Build/Utils/_ItalianText.cc, Build/Utils/_PolishText.cc, Build/Utils/_RussianText.cc, README.md, _build/lib-slog/slog/slog.h, appveyor.yml, cmake/FindSDL2.cmake, sgp/LoadSaveData_unittest.cc, sgp/UTF8String_unittest.cc, sgp/wchar_unittest.cc
Readding the BOM's was required for the unittests to work. Building on Openbsd is broken afterwards for me though, which is fixed in #441.
Additionally I created a bot user and shared email account for the stracciatella team. Bot should be used to e.g. automatically attach links to builds to pull requests. The shared email is used for the bot user. We should exchange credentials somehow.
=> Add Appveyor CI

.travis.yml, CMakeLists.txt, appveyor.yml
This builds packges for pull requests so changes can be tested more easily also by non-developers.
=> Build pull requests

Build/Strategic/Meanwhile.cc, Build/Strategic/Queen_Command.cc, Build/Strategic/Strategic_AI.cc, Build/Strategic/Strategic_Movement.cc, Build/Tactical/OppList.cc, Build/Tactical/Soldier_Create.cc, Build/Tactical/Soldier_Profile.cc, Build/TileEngine/Explosion_Control.cc, Build/Utils/Music_Control.cc, CMakeLists.txt, sgp/MemMan.cc, src/AmmoTypeModel.cc, src/AmmoTypeModel.h, src/CalibreModel.cc, src/CalibreModel.h, src/ItemModel.cc, src/ItemModel.h, src/policy/GamePolicy.h, src/policy/IMPPolicy.h
Hi, I made a bunch of cleanups, this is trivial stuff.
Let me know if you don't like any of the commits, I can take it out.
Feel free to squash it, if you want to.
=> Minor cleanups

dependencies/readme.txt, src/externalized/readme.txt
=> Remove outdated documentation

CMakeLists.txt, src/sgp/Button_Sound_Control.cc, src/sgp/Button_System.cc, src/sgp/Cursor_Control.cc, src/sgp/MemMan.cc, src/sgp/MouseSystem.cc, src/sgp/MouseSystem.h, src/sgp/Random.cc, src/sgp/Random.h, src/sgp/SGP.cc, src/sgp/SoundMan.cc
=> remove JA2 preprocessor define

src/game/Utils/Message.cc
@JAsmine-ja2 Can you test if that fixes #398 properly?
Builds: http://builds-ja2.stefanlau.com/pull-requests/465/
=> Only dont show tactical messages if time is being compressed

COMPILATION.md
=> Add rust to compilation docs

src/game/Tactical/Turn_Based_Input.cc
Deal substantially more and explosiver damage to kill tanks and creatures.
Fixes #503 
NB: Not sure if appveyor issue needs fixing as it will probably be resolved with https://github.com/appveyor/ci/issues/1431
=> Deal more and explosive damage to enemies when killing everyone

src/game/Laptop/Laptop.cc
Without reintroducing the laptop double free problem (issue #68).
The solution is based on the previous one by @momoko-h, but introduces a new
variable to store the information if a page has been exited.
Untangling the page transition mess seems highly complicated without rewriting
the whole laptop code.
This also changes a global variable to a local variable.
=> Fix laptop page logic (issue #510)

src/game/Utils/Sound_Control.cc
This fixes #520 (and therefore a part of #521)
=> Change "/doorcr_b.wav" to "/doorcr.wav"

src/game/Tactical/Rotting_Corpses.cc
by it's corresponding animation with blood.
Resolves a part of the issues mentioned in #521
=> Replace non-existing corpse animation

src/game/Utils/Sound_Control.cc, src/game/Utils/Sound_Control.h
Resolves a part of the issues mentioned in #521
=> Remove unused references to non-existing sound files

src/sgp/Video.cc
=> Allow resizing of game window

ja2_manpage, rust/src/stracciatella.rs
Fixes:
- JSON options being prefered over cli switches
Adds:
- Datadir cli switch to set vanilla data directory
=> Fix and enhance cli switch parsing

rust/src/stracciatella.rs, src/game/Tactical/Turn_Based_Input.cc
With these changes master compiles without warnings on my system.
=> Fix warnings

src/game/Tactical/Weapons.cc
Fixes #191 
For some reason someone put the condition in comments. Can't tell why. Normal Hand to hand still works as aspected with the condition.
=> Fixes Stealing AP Bug

src/game/Tactical/Turn_Based_Input.cc
=> Cheat: alt+o damages bloodcats now

src/game/Tactical/Handle_Items.cc
fix #595
Added a check for blocking doors when attacking with Hand-to-hand.
=> Check for blocking doors when attacking with HTH

src/game/TileEngine/Explosion_Control.cc, src/game/TileEngine/SmokeEffects.cc
=> Gasroofbug

src/game/Utils/Timer_Control.h
=> Add missing bracket around COUNTERDONE define

README.md
=> [RFC] README: Add section about the launcher.

assets/externalized/game.json, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/DefaultGamePolicy.h
last part of #307.
As a follow-up, if we decide and think we'll never need any special hotkey discrimination, IsHotkeyEnabled can be removed or vastly simplified.
=> Unified hotkeys

docs/archeology/FIXME, src/game/Strategic/Strategic_Town_Loyalty.cc, src/game/Tactical/Arms_Dealer_Init.cc, src/game/Tactical/Structure_Wrap.cc, src/game/Tactical/Structure_Wrap.h, src/game/TacticalAI/AIUtils.cc, src/game/TileEngine/Isometric_Utils.cc, src/game/TileEngine/WorldDef.cc
=> Misc cleanup

.travis.yml, CMakeLists.txt, appveyor.yml, rust/src/stracciatella.rs
__Goal__: Build release packages when a git tag is created.
Also include some rust changes for the newest serde version that was released recently.
Contains a bunch of changes to CI, so I have to open a PR early again to ensure everything still works.
=>  Build release tags

CMakeLists.txt
- Now installed into package root (and only once)
- Install UCRT dlls as well
Again early PR for package builds.
=> Fix distributed runtime dlls

assets/externalized/game.json
Changes made by JAsmine-ja2 in issue #643.
=> Fix typos and improve comments in game.json

contributors.txt
new people from:
git shortlog -s v0.15.0..v0.16.0
=> contributors.txt: updated for 0.16

.travis.yml, appveyor.yml
Let's hope that this does not block PR building.
=> Limit ci building to master branch

assets/externalized/game.json
=> Add warning about low health (< 15) to game.json

assets/distr-files-mac/BundleInfo.plist, changes.md, contributors.txt
Update contributors.txt
Update changelog and increase mac bundle version
=> squash merged changes from the 0.16.1 branch

.travis.yml, appveyor.yml
So we can actually see what release packages will look like.
=> Build nightlies as release packages

src/game/Tactical/Interface.h, src/game/Tactical/Overhead.cc, src/game/TileEngine/Radar_Screen.cc, src/game/TileEngine/RenderWorld.cc
Have separated this from pr #733, as they were not really related.
It should solve #171, #73, #195, #125 once properly tested which are all listed in #225.
=> Fix radar map issues

src/game/TileEngine/Isometric_Utils.cc, src/game/TileEngine/RenderWorld.cc, src/game/TileEngine/WorldDef.h
This patch solves #119 
Please do not merge it yet.. I need to test it properly, and check it against other possibly related issues first.
=> Fixed tactical world rendering when scrolling to top left

docs/archeology/TODO, src/game/Laptop/IMP_Compile_Character.cc
=> Fixed IMP attitude generation

docs/archeology/TODO, src/game/Laptop/IMP_Personality_Quiz.cc
Of TODO0006 comments quite a few felt arbitrary, maybe the authors wanted it that way. Well, actually most did.
One didn't and I fixed it today.
=> TODO0006: fixed a fallthrough

src/game/Tactical/Bullets.h, src/game/Tactical/LOS.cc
OK, this should fix #769.
However, the code base of JA2 is realy mix of styles. Including many I would call bad. I searched discussion on what style to use on future commits and failed to find any. I tried to be consistent with what's around, to the point of adding tabs in the middle of a line which I personally despise.
=> #769: Fixed cleaning knives from blood

src/game/Tactical/Points.cc, src/game/Tactical/Rotting_Corpses.cc, src/game/Tactical/Soldier_Add.cc
Fixes: #806
NOTE: the AP cost of CROW_WALK was changed
=> Fix extra crows when a game is loaded

rust/Cargo.toml
=> Add panic=abort to rust library

src/game/Tactical/Interface_Panels.cc
just so if it happens again it'll be more obvious what goes wrong.
=> CheckForDisabledForGiveItem: added assert for #821

src/game/Tactical/Interface.cc, src/game/TileEngine/Radar_Screen.cc, src/game/TileEngine/Radar_Screen.h
This should fix cause of those 3 bug reports.
=> Fix tactical interface rendering on strategic interface.

src/game/Tactical/Soldier_Ani.cc
=> Cowering civs die from a standing position.

src/game/TacticalAI/NPC.cc
=> Don't set FACT_HILLBILLIES_KILLED if they are still alive.

src/game/Tactical/PathAI.cc
=> Rework path finding estimates and increase path finding limits

src/game/Tactical/Soldier_Ani.cc, src/game/Tactical/Soldier_Control.cc, src/game/TacticalAI/DecideAction.cc, src/game/TacticalAI/PanicButtons.cc
=> Panic triggers only happen for soldiers

.travis.yml, appveyor.yml
I retriggered the latest nightly build and the upload that previously failed succeeded now. Lets try if retying the upload will work...
=> Retry binary uploads

rust/stracciatella/src/logger.rs
Creating TermLogger can fail.
Uses SimpleLogger as fallback on failure.
Creating the log file can fail.
Prints a warning on failure.
=> Allow failures in Logger::init

src/externalized/DefaultContentManager.cc, src/game/Tactical/Points.cc
=> fix a coverity issue in Points.cc

src/game/TileEngine/WorldDef.cc
=> Fix bad format specifier

src/game/Laptop/AIMArchives.cc, src/game/Laptop/AIMMembers.cc, src/game/Laptop/EMail.cc, src/game/Strategic/MapScreen.cc, src/game/Strategic/Strategic_Mines.cc, src/game/Tactical/Dialogue_Control.cc, src/game/Tactical/Inventory_Choosing.cc, src/game/TileEngine/LoadSaveLightSprite.cc, src/game/TileEngine/Map_Edgepoints.cc, src/game/Utils/Cinematics.cc, src/game/Utils/Message.cc, src/game/Utils/Text_Input.cc, src/launcher/Launcher.cc, src/sgp/FileMan.cc, src/sgp/LoadSaveData.cc
Either cast explicitly or change the type.
Reference: #857
=> Fix C4267 warnings

src/game/Strategic/Strategic_AI.cc
The assert message would never show up.
Reference #857
=> Fix warning C4551

src/launcher/Launcher.cc
=> Fix expression result unused warning

src/game/Editor/Item_Statistics.cc
=> Silence fallthrough warning in SpecifyItemToEdit

src/game/Strategic/Assignments.cc
=> Silence fallthrough warning in SquadMenuBtnCallback

src/game/Tactical/Arms_Dealer_Init.cc
=> Silence fallthrough warning in GetArmsDealerItemTypeFromItemNumber

src/game/Strategic/Auto_Resolve.cc
=> Silence fallthrough warnings in ResetAutoResolveInterface

src/game/Strategic/Strategic_AI.cc
=> Fix unintended fallthrough in LoadStrategicAI

src/game/Tactical/Interface_Dialogue.cc, src/game/Tactical/Inventory_Choosing.cc, src/game/Tactical/Soldier_Control.cc, src/game/TacticalAI/AIMain.cc
=> Silence remaining fallthrough warnings

src/game/Editor/Sector_Summary.cc
=> Fix unused result warning in LoadSummary

src/game/Laptop/BobbyRGuns.cc
=> Fix variable set but not used warning in DisplayArmourInfo

src/game/Strategic/Map_Screen_Interface.cc
=> Fix variable set but not used warning in DisplayUserDefineHelpTextRegions

src/game/Strategic/StrategicMap.cc
=> Fix variable set but not used warning in BeginLoadScreen

src/game/Tactical/LOS.cc
There is spaghetti code related to this commented out, so I'm commenting instead of deleting.
Reference #857
=> Fix variable set but not used in CTGTHandleBulletStructureInteraction

src/game/Tactical/PathAI.cc
There is commented code for vehicle movement that uses them, so comment instead of delete.
Reference #857
=> Fix variable set but not used in FindBestPath

src/game/Tactical/Soldier_Profile.h
=> Fix array bounds warning in GetProfile

src/launcher/Launcher.cc
=> Fix result not used warning in Launcher

src/game/AniViewScreen.cc
fgets returns nullptr when eof is reached and nothing is read.
Reference #857
=> Fix result not used warning in BuildListFile

src/game/TileEngine/Lighting.cc
=> Fix result not used in LoadShadeTablesFromTextFile

src/sgp/LoadSaveData_unittest.cc
=> Fix unused result in test LoadSaveData.floatAndDoubleFormat

src/game/GameScreen.cc, src/game/Tactical/FOV.cc, src/game/Tactical/Handle_Doors.cc, src/game/Tactical/Interface_Panels.cc, src/game/Tactical/Tactical_Save.cc, src/game/Tactical/Weapons.cc, src/game/TacticalAI/NPC.cc, src/game/TileEngine/RenderWorld.cc
=> Fix remaining variable set but not used warnings

src/sgp/VObject_Blitters.cc
=> Fix unused-but-set-variable warnings in VObject_Blitters.cc

src/externalized/DefaultContentManager.cc, src/game/GameInitOptionsScreen.cc, src/game/HelpScreen.cc, src/game/Laptop/AIMArchives.cc, src/game/Laptop/IMP_Compile_Character.cc, src/game/Laptop/IMP_Personality_Quiz.cc, src/game/Strategic/Assignments.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Strategic_Movement.cc, src/game/Tactical/FOV.cc, src/game/Tactical/Interface_Dialogue.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/LoadSaveMercProfile.cc, src/game/Tactical/Overhead.cc, src/game/Tactical/PathAI.cc, src/game/Tactical/Turn_Based_Input.cc, src/game/TileEngine/Map_Edgepoints.cc, src/game/TileEngine/Radar_Screen.cc, src/game/TileEngine/RenderWorld.cc, src/game/Utils/WordWrap.cc, src/sgp/FileMan.cc, src/sgp/SoundMan.cc, src/sgp/VObject_Blitters.cc
=> Fix simple sign-compare warnings

src/game/Strategic/Assignments.cc
=> Fix underflow in CreateDestroyMouseRegionsForSquadMenu

src/game/Tactical/Dialogue_Control.cc, src/game/Tactical/LOS.cc
=> Fix sign-compare warnings of random values

src/game/Laptop/Insurance.cc, src/game/Laptop/Insurance_Contract.cc, src/game/Laptop/Insurance_Contract.h
Fixes sign-compare warning in DisableInsuranceContractNextPreviousbuttons.
Reference #857
=> Make insurance index variables unsigned

src/sgp/SGP.cc
Windows does not support the utf8 locale, not sure how to proceeed here.
*nix, macosx and *bsd are set according to the info from python.
Problems are logged after the logger is initialized.
=> Rework unicode locale initialization

src/game/Strategic/Quest_Debug_System.cc
=> Fix negative array index read in EnableQDSButtons

src/game/Tactical/ArmsDealerInvInit.cc
=> Fix negative array index write in ItemTransactionOccurs

assets/mods/generous-rebels/Generous Rebels Mod.txt, assets/mods/imp-quiz-honest-answers/IMP quiz honest answers mod.txt
=> mods: removed obviated (un)install instructions

src/game/Strategic/Strategic_Mines.cc
=> Fix divide by zero in GetAvailableWorkForceForMineForEnemy

src/coverity_model.cpp
This model "fixed" 16 false positives and allowed the detection of a new defect.
=> Add coverity modeling file

src/sgp/SoundMan.cc
Detected by coverity.
pName had fixed size and filename unknown size.
=> Fix buffer overflow in SoundLoadDisk

src/game/Tactical/Morale.cc
=> Fix negative array index read in HourlyMoraleUpdate

src/game/Tactical/Soldier_Add.cc
=> Fix uninitialized variable in InternalAddSoldierToSector

src/sgp/Button_System.cc
=> Fix uninitialized member in GUI_BUTTON::GUI_BUTTON

src/game/Tactical/Morale.cc
=> Fix negative array index read in HourlyMoraleUpdate - take 2

src/game/Strategic/Assignments.cc, src/game/TacticalAI/NPC.cc
=> Fix hillbilies quest

src/game/Init.cc, src/game/JAScreens.cc, src/game/Sys_Globals.cc, src/game/Sys_Globals.h, src/game/TileEngine/Tile_Surface.cc, src/game/TileEngine/WorldDef.cc
The message wraps as needed to fit the screen.
=> Show error from InitializeJA2

CMakeLists.txt
Target run-ja2-editor runs the ja2 editor.
Target run-ja2-unittests runs the ja2 unittests.
=> Add auxiliary targets

appveyor.yml
travis doesn't care where [ci skip] shows up
=> appveyor: support skipping more liberally

CMakeLists.txt, src/game/Utils/_FrenchText.cc
stuff that sidetracked me yesterday.
=> Misc fixes

src/externalized/Soldier.cc, src/externalized/Soldier.h, src/game/Strategic/Meanwhile.cc, src/game/Tactical/Dialogue_Control.cc, src/game/Tactical/Dialogue_Control.h, src/game/Tactical/Interface_Dialogue.cc, src/game/Tactical/Overhead.cc
=> Shut up door popups when busy

src/game/Laptop/BobbyRGuns.cc, src/game/Tactical/Map_Information.cc, src/game/Tactical/OppList.cc, src/game/Tactical/Soldier_Ani.cc, src/game/TacticalAI/AIMain.cc
Closes #1057. 
Logging changes only, as described in the issue.
=> Adjusting log levels

src/game/AniViewScreen.cc, src/game/Tactical/Interface_Dialogue.cc
=> Fix bad st_format_printf calls

src/externalized/strategic/CreatureLairModel.cc, src/game/Strategic/Creature_Spreading.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/StrategicMap.cc, src/game/Strategic/Strategic_AI.cc, src/game/Strategic/Strategic_Mines.cc, src/game/Strategic/Strategic_Mines.h, src/game/Tactical/PathAI.cc, src/game/TileEngine/Map_Edgepoints.cc
Tried doing a build with gcc today, and saw a bunch of new compiler warnings. These should not affect anything.
=> Misc fixes: gcc warning and Coverity defects

src/externalized/DefaultContentManager.cc
For #1127, and follow up #1126.
1. `~/.ja2/data` is optional. Should not error out if users have not created that directory
2. Improve error messages on errors in DefaultContentManager, so users have better idea of what went wrong.
=> Error handling in data loading

.ci/ci-publish.sh, .ci/upload-artifact.sh
Somehow the upload on appveyor works for PRs, but not for nightlies. This should fix it.
=> Fix nightlies upload on appveyor

assets/externalized/game.json, src/externalized/JsonObject.h, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/game/Laptop/CharProfile.cc, src/game/Laptop/CharProfile.h, src/game/Laptop/IMP_Begin_Screen.cc, src/game/Laptop/IMP_Compile_Character.cc, src/game/Laptop/IMP_Confirm.cc, src/game/SaveLoadGame.cc, src/game/SaveLoadGame.h, src/game/Strategic/Strategic_Merc_Handler.cc, src/game/Tactical/Campaign.cc, src/game/Tactical/Merc_Hiring.cc, src/game/Tactical/Merc_Hiring.h, src/game/Tactical/Soldier_Profile.cc, src/game/Tactical/Soldier_Profile.h, src/game/Tactical/Weapons.cc, src/game/Tactical/Weapons.h, src/game/TacticalAI/AIUtils.cc
This cherry-picks a few of the updated changes from vvx, finishes them where they were incomplete and then cleans up game.json and its handling a bit.
#32
#665
#1127
=> Vvx and more

cmake/target-rebuild-contributors-list.cmake.in, contributors.txt
The script wants to add email to everyone, which is too leaky, so now all are stripped.
Pretty unwieldy system, but we don't need it often.
btw, adding .mailmap didn't do much for the need for exceptions.
=> Contributors bump

CMakeLists.txt
my testing went fine as well :)
this also includes the tag
=> set version to 0.17.0

.ci/ci-publish.sh, .ci/upload-artifact.sh, .travis.yml, appveyor.yml
It seams that CI builds dont upload into the correct directory (they use the directory name as file name).
Second issue is that travis does not seem to run for tagged releases. I am not sure why.
=> Fix upload dirs for releases

rust/stracciatella/src/guess.rs
=> Fix resource_packs not being found in launcher

src/externalized/DefaultContentManager.cc, src/externalized/strategic/SamSiteAirControlModel.cc, src/externalized/strategic/SamSiteAirControlModel.h, src/game/Laptop/IMP_SkillTraits.cc, src/game/Strategic/Map_Screen_Interface_Bottom.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/StrategicMap.cc, src/game/Tactical/ShopKeeper_Interface.cc, src/game/TileEngine/Isometric_Utils.cc
Clearing some Coverity and compiler warnings. There should be no change in functionality. More details in the commit messages.
=> Fixing compiler and coverity warnings

src/game/Laptop/CharProfile.cc, src/game/Laptop/Florist_Gallery.cc, src/game/Laptop/Insurance_Info.cc, src/game/Laptop/Mercs.cc, src/game/Tactical/Arms_Dealer_Init.cc
These are illegal array access (out-of-bounds access/read), in the Laptop. Mostly because of wrong array bounds and checks.
=> Fixing illegal array access flagged by Coverity

src/game/SaveLoadGame.cc
Currently, DiD save tries to create a backup before creating the save. Attempting backup crashes the game if the parent directory (`SavedGames/`) does not yet exist.
This PR:
- Creates the `SavedGames` directory before creating the `Backup\` (fixes #1216)
- Changes some `char[]` to `ST::string` (#1056)
=> Fix for Dead-is-dead failure on save if JA2/SavedGames does not exist

src/game/TileEngine/SaveLoadMap.cc
Fixes #1219.
`SaveModifiedMapStructToMapTempFile` was called inside a loop, so that each iteration opens the same temp file, append an object and close (via `AutoSGPFile`). There could be hundreds of modifications to a map, and may be even more in a longer game.
On Windows, opening files is slow due to the built-in virus scanner. This slows down saving games so much that it makes DiD gameplay unpleasant.
This PR updates the `SaveModifiedMapStructToMapTempFile` so that:
- Callers should open the temp file before the loop, and use the `std::shared_ptr<AutoSGPFile>` returned
- Clean up is still automatic; File is closed once the `std::shared_ptr` goes out of scope
- The old API is still there if caller only needs to write once
Tested on my own computer and saving game is much faster.
- c.f. …
=> Reducing temp file open in SaveModifiedMapStructToMapTempFile

dependencies/lib-smacker/LICENSE.txt
indicate it has been modified
according to CC BY-NC-2.0
Signed-off-by: Richard Fröhning <misanthropos@gmx.de>
=> give credit to Greg Kennedy for libsmacker

src/externalized/mercs/MercProfileInfo.cc, src/game/Strategic/StrategicMap.cc
A couple of new defects uncovered by Coverity.
=> Fixing bugs found by Coverity

rust/stracciatella/src/unicode.rs
=> Only do unicode normalization on strings where it is necessary

src/game/Tactical/LoadSaveObjectType.cc
Fixes #1234 and fixes #1308.  We had a previous similar fix (#1162) but that did not cover attached items. 
This prevents the problem from happening in newly loaded maps. It does not fix existing saves and sectors that have already been loaded, unfortunately.
The problem is that NightOps maps contain invalid items (some items with `usItem` >= 999). It causes errors when the game tries to get the ItemModel for those invalid IDs. It is reproducible in a fresh game with `mod-nightops-maps` at sector H13.
=> Replacing invalid attached objects in preplaced world items

src/game/SaveLoadGame.cc
=> Fix saving IMP merc without save game directory present

assets/externalized/game.json, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/game/Laptop/Laptop.cc
Adds "website_loading_speed_scale" config var for scaling the speed of loading time of websites on the laptop.
=> Config var for scaling website loading time on laptop

README.md
the website has already been updated
=> README: replace irc with discord [ci skip]

src/externalized/DefaultContentManager.cc, src/externalized/scripting/FunctionsLibrary.cc, src/externalized/scripting/FunctionsLibrary.h, src/externalized/scripting/ScriptingExtensionsLua.cc, src/game/CMakeLists.txt, src/game/Cheats.h, src/game/Editor/LoadScreen.cc, src/game/Editor/Sector_Summary.cc, src/game/GameLoop.cc, src/game/GameMode.cc, src/game/GameMode.h, src/game/GameRes.cc, src/game/GameScreen.cc, src/game/GameVersion.cc, src/game/Init.cc, src/game/LoadSaveTacticalStatusType.cc, src/game/SaveLoadGame.cc, src/game/SaveLoadGameStates.cc, src/game/SaveLoadGameStates.h, src/game/SaveLoadGameStates_unittest.cc, src/game/Strategic/Scheduling.cc, src/game/Tactical/Turn_Based_Input.cc, src/game/TileEngine/Overhead_Map.cc, src/game/TileEngine/RenderWorld.cc, src/game/TileEngine/Structure.cc, src/game/TileEngine/WorldDef.cc, src/game/Utils/Font_Control.cc, src/game/Utils/Font_Control.h, src/sgp/SGP.cc
Providing the basis for #1272.
- Renamed `GameState` to `GameMode`, because the class has nothing to do with the current state of the game
- Game save version incremented from `100` to `101`
- Saved game is compatible with current master (Not yet tested with base vanilla)
- Extra key-value data is appended to the end of the save
- Key are strings; Values are `std::variant`, can be any one of  primitives (`int32_t`, `float`, `bool` and `string`) or, a map or vector of primitives.
It is accessed via the `g_gameStates` in SaveLoadGameStates.h.
- Loading a primitive value (one of `int32_t`, `bool`, `ST::string` or `float`)
```c
#include "SaveLoadGameStates.h"
INT32 intval = g_gameStates.Get<INT32>("key1");
ST::string st = g_gameStates.Get<ST::string>("key2");
```
- Saving a typed container …
=> Appending extra game states at the end of Saves

assets/externalized/game.json
To load an IMP with nickname, you must not provide the full name or gender. 
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/e23678b74af7e7fa2ccaf067eb44993184af0a33/src/game/Laptop/IMP_Begin_Screen.cc#L280-L282
Updating the `game.json` comments a little to clarify this.
=> Brief instruction on how to load an IMP character

src/game/TacticalAI/AIUtils.cc, src/game/TacticalAI/Attacks.cc, src/game/TacticalAI/FindLocations.cc, src/game/TileEngine/WorldDef.cc
Including the simple and (seemingly) straight-forward fixes as suggested in #1384, #1385 and #1388. May add more commits if we have more of the bugs.
I propose to gate all these bug-fixes (together with #1281) behind one option in `game.json`. Defaults to enabled, but it can still be disabled to allow a true "vanilla" (and buggy) experience.
I plan to do a play-through with all fixes enabled, and see how it goes. I don't really have a systematic way to verify the AI fixes.
=> Tactical AI fixes

src/game/SaveLoadGame.cc
=> Fix created directories when saving files

src/externalized/DefaultContentManager.cc
=> DefaultContentManager::loadTranslationTable: silence warning

src/game/Tactical/LOS.cc
fixes #1394
Co-authored-by: Seven <sevenfm@gmail.com>
=> LineOfSightTest: only consider smoke on the current tile level

rust/stracciatella/src/fs.rs
=> Fix renaming files on different file systems for all rust versions

src/game/TacticalAI/NPC.cc
=> NPC: removed a few pointless macros

assets/mods/simplified-chinese-localization/manifest.json
The `simplified-chinese-localization` mod requires a little more instructions. The `manifest.json` is a nice place to put it.
=> Instructions and credits for the simplified chinese mod

src/game/Strategic/PreBattle_Interface.cc, src/game/Tactical/Soldier_Create.cc, src/game/Tactical/Turn_Based_Input.cc, src/game/TileEngine/WorldDef.cc
Unrelated problems found while working on #1479
=> Fix rare vanilla vehicle bugs

CMakeLists.txt, dependencies/lib-lua/CMakeLists.txt, dependencies/lib-sol2/CMakeLists.txt
Ability to take LUA and SOL2 dependencies from the system
=> LUA and SOL2 may be taken from system now

src/externalized/DefaultContentManager.cc
=> DefaultContentManager::loadTranslationTable: remove unused variable

CMakeLists.txt, dependencies/lib-miniaudio/CMakeLists.txt
Ability to pick up system miniaudio
I hope https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1377 can be closed when this one is merged
=> Make system miniaudio use possible

assets/externalized/game.json, rust/stracciatella/src/schemas/yaml/game.schema.yaml, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/game/Strategic/Assignments.cc, src/game/Tactical/Weapons.cc, src/game/Tactical/Weapons.h
Lifted, adapted and extended the (IMHO) last useful things from #1002.
=> Externalize more hardcoded values

src/game/SaveLoadScreen.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Queen_Command.cc, src/game/Strategic/Strategic_AI.cc, src/game/Tactical/Interface_Control.cc, src/game/Tactical/Interface_Dialogue.cc, src/launcher/Launcher.cc
there was a fresh report right after the previous PR was merged, so I picked some more off the list.
The big chunk is just an indentation reduction, easiest to look at with whitespace changes disabled.
=> several more coverity fixes

rust/stracciatella/src/fs.rs
=> Fix ERROR_NOT_SAME_DEVICE for Windows

src/game/SaveLoadGame.cc, src/game/Strategic/Strategic_Movement.cc, src/game/Utils/_ChineseText.cc, src/game/Utils/_DutchText.cc, src/game/Utils/_EnglishText.cc, src/game/Utils/_FrenchText.cc, src/game/Utils/_GermanText.cc, src/game/Utils/_ItalianText.cc, src/game/Utils/_PolishText.cc, src/game/Utils/_RussianText.cc
• Ensure ambient sounds are always loaded after loading a game
• Pass all required arguments to st_format_printf
=> Fix crashes #1537 and #1559

src/game/Tactical/Merc_Entering.cc
The fade in and out didn't take into account the sound effects volume modifier.
Fixes #1562
=> Fix helicopter run not using sound effects volume modifier

dependencies/lib-miniaudio/CMakeLists.txt, dependencies/lib-miniaudio/getter/CMakeLists.txt.in, src/sgp/SoundMan.cc
Also adds a configure time check for the system miniaudio version to have the same major and minor version as the included one.
=> Upgrade included miniaudio to 0.11.9

src/game/TileEngine/Render_Dirty.cc
A vector cannot be safely expanded, all BACKGROUND_SAVE pointers such
as those held by mouse regions and overlays would become invalid.
In commit e0875ba82420841a32caf148d5a002013135af25 I changed the way we keep track of BACKGROUND_SAVE structs from a vector of pointers to a vector of the structs, which wasn't my best decision ever. Fortunately the basic idea is still sound, one just has to use an appropriate container.
=> Store BACKGROUND_SAVE structs in a forward_list

src/game/Tactical/TeamTurns.cc
=> Don't try to move soldiers that are not in the sector in EndTurn()

src/game/Tactical/Soldier_Tile.cc
We cannot use Teleport while another soldier is currently NOWHERE.
Fixes #1607.
=> Fix SwapMercPositions logic

CMakeLists.txt, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.h, src/game/SaveLoadGame.cc, src/game/Strategic/Game_Init.cc, src/game/Strategic/Strategic_AI.cc, src/game/Strategic/Strategic_Movement.cc, src/game/Tactical/Militia_Control.cc, src/game/Tactical/Morale.cc, src/game/Tactical/Soldier_Create.cc, src/game/Tactical/Soldier_Create.h, src/launcher/main.cc, src/sgp/SGP.cc, src/sgp/SGPStrings.h, src/sgp/SoundMan.cc
More stuff for your kind consideration. Don't wory, I won't have much free time for the rest of the week and won't bother you any more. :)
Some of this is mainly to make coverity happy, but the strategic movement stuff seems useful. If we're lucky it's the cause of those spurious movement groups warnings that start to appear after a couple of game days.
=> More coverity fixes

src/game/Tactical/Soldier_Tile.cc
It would be good to also fix this bug on 0.19.x which is where I found it.
=> [0.19.x] Fix SwapMercPositions logic

src/externalized/DefaultContentManager_unittests.cc, src/game/Strategic/Strategic_Pathing.cc, src/game/Tactical/Morale.cc, src/game/Tactical/Soldier_Ani.cc
Some commits caused conflicts so I skipped them.
I tested this by creating a new save and playing enough to attack one tile in Drassen on Normal difficulty, I ragequit my last save.
=> [0.19.x] cherry-pick Coverity fixes

.github/workflows/coverity-scan.yml, CMakeLists.txt
Grrr, now I really feel silly.
=> coverity: properly pass a cmake define [ci skip]

src/game/Laptop/Finances.cc
ATM all militia training is reported to happen in sector B10.
=> Display correct location of militia training in Finances

src/game/TileEngine/Tactical_Placement_GUI.cc
The gMercPlacement array was never freed. Old vanilla bug which also didn't have the corresponding `MemFree` call.
=> Fix memory leak in tactical placement

src/game/Tactical/OppList.cc
Plus misc. cleanup of OppList.cc
The cleanup and the macros hide the bug here a bit, so I'll explain:
The bug here is the `if` block starting in line 4588: the condition ensures that `*pbPublOL` must be either -5 or 6 when we call `UpdatePublic()`. `UpdatePublic()` then subtracts -4, so it's now either -1 or 10 and uses that as an index into a 10x10 array, so both cases are out of bounds.
=> Fix OOB array access in UpdatePublic

src/externalized/DefaultContentManager.cc, src/externalized/LoadingScreenModel.cc, src/externalized/mercs/MERCListingModel.cc, src/externalized/strategic/CreatureLairModel.cc, src/game/Editor/Sector_Summary.cc, src/game/Laptop/Mercs.cc, src/game/SaveLoadGameStates.h, src/game/Strategic/Creature_Spreading.cc, src/game/Strategic/Game_Init.cc, src/game/Strategic/Strategic_AI.cc, src/game/Tactical/Dialogue_Control.cc, src/game/Tactical/Interface_Items.cc, src/game/Utils/Observable.h
One logically dead code, several unnecessary copies.
CIDs 275760 - 275780
Overall some nice progress here, 15 fixed, only 7 high impact issues left.
=> Fix the newly detected Coverity issues

src/game/Strategic/Strategic_Mines.cc
=> MineAMine: return amount mined only if mine is controlled by player

src/game/Tactical/Soldier_Control.cc, src/game/Tactical/Weapons.cc
Also fixes the "failed to steal" message. #1676
=> Fix stealing from enemies on roof

src/game/Tactical/Handle_UI.cc
As no other opinion was provided, I went with my own and just removed the file check.
=> Autosave please

android/app/src/main/java/io/github/ja2stracciatella/ConfigurationModel.kt, android/app/src/main/java/io/github/ja2stracciatella/Ja2Json.kt, android/app/src/main/java/io/github/ja2stracciatella/LauncherActivity.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/DataTabFragment.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/PlaceholderFragment.kt, android/app/src/main/res/layout/fragment_launcher_data_tab.xml, android/app/src/main/res/layout/launcher_spinner_item.xml, android/app/src/main/res/values/strings.xml
Adds Spinner for the game version to the Android launcher. Unfortunately auto-detecting the game version is not possible yet, as it would require interacting with the Stracciatella library via FFI, which requires some work.
=> Allow to choose vanilla version in Android launcher

src/game/Tactical/Handle_UI.cc, src/game/Tactical/Real_Time_Input.cc, src/game/Tactical/Touch_UI.cc, src/game/Tactical/Turn_Based_Input.cc, src/game/TileEngine/Interactive_Tiles.cc
This should fix two touch control issues, that still make the game quite hard to play on touch devices.
- Using the item in your hand was not possible, now there is a button for it. Now you can actually bandage your mercs before the end of battle
- Interacting with closed doors was not possible, so you could not get into places
I recommend this still going into `0.20.0`, as it only affects touch controls and enhances playability quite a lot.
=> Fix two touch control issues

src/game/Strategic/Strategic_Movement.cc
Fixes #1703.
The comment about `GROUP::uiArrivalTime` says that it should only be set by `setArrivalTime`, so I changed that, too.
=> Properly test if a group's only member is a vehicle

src/game/Options_Screen.cc, src/game/Strategic/Game_Clock.cc, src/game/Strategic/Game_Clock.h, src/game/Strategic/Game_Events.cc, src/game/Strategic/Quest_Debug_System.cc
Also factor out some duplicated code into a new function.
=> Remove some unused code from Game_Clock

CMakeLists.txt, src/externalized/Soldier.cc, src/externalized/VehicleModel.cc, src/game/Laptop/AIMFacialIndex.cc, src/game/Laptop/Mercs.cc, src/game/SaveLoadScreen.cc, src/game/Strategic/Strategic_AI.cc, src/game/TileEngine/Physics.cc
Wno-missing-braces and Wno-deprecated-declarations are not necessary, Wno-unused-function just hides functions that have become unused due to other cleanup.
=> Turn on currently disabled warnings

src/externalized/Soldier.cc, src/externalized/Soldier.h, src/game/Sys_Globals.h, src/game/Tactical/Auto_Bandage.cc, src/game/Tactical/Handle_Items.cc, src/game/Tactical/Handle_UI.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/Overhead.cc, src/game/Tactical/Soldier_Add.cc, src/game/Tactical/Soldier_Control.cc, src/game/Tactical/Turn_Based_Input.cc, src/game/TileEngine/Interactive_Tiles.cc
Continuation of #1709: allocating a `shared_ptr` just to call one simple method is really inefficient. These pointers are never shared.
=> Remove SoldierSP and GetSoldier

src/game/JAScreens.cc, src/game/JAScreens.h, src/game/MainMenuScreen.cc
picking 8fcc33db1d4d836c2cf2b70e993decc10be5d398 from maxrd2
=> [TEST] reduce intro splash duration

src/game/Tactical/Soldier_Macros.h, src/game/Tactical/Turn_Based_Input.cc
The default cursor for hostile persons is now the attack cursor, prior the was only the case for Deidranna's guys (ENEMY_TEAM).
Fixes #1723.
=> Do not try to talk to hostile civilians

src/sgp/Video.cc
Before this commit, RefreshScreen() used SDL_UpdateTexture to blit the entire screen buffer surface to the screen texture every frame. Since this function has to convert the screen texture format to the actual output format of our window, this is extremely costly. The game spent well above 50% of its time under this function.
With this commit, only the union of all screen buffer regions that actually got modified are updated. In the most extreme cases (Load Screen and others) this union can be smaller than 1% of the screen area.
Blit_RGB565_32 is by far the heaviest function in the entire program, it usually accounts for more than 60% of all CPU usage on my system. Here is a graph showing how this very simple PR affects this function:
The performance data for the Laptop screen with this …
=> Do not update the entire screen texture every frame

src/sgp/Video.cc
As its last step, ScrollJA2Background() currently creates a temporary SDL texture from the screen buffer and copies this texture to the renderer. This is pointless because after the function returns, RefreshScreen() then updates the permanent screen texture from the screen buffer and copies it to the renderer, over the texture created by ScrollJA2Background().
This commit removes this last step, resulting in faster scrolling and at least 900 K less memory used (in 640x480).
Additionally this commit addresses all -Wconversion warnings in Video.cc.
=> Improve scrolling

rust/stracciatella/src/schemas/yaml/army-gun-choice.schema.yaml, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h
=> Build the army gun choice tables correctly

src/game/TileEngine/Explosion_Control.cc, src/game/TileEngine/Smell.cc
• Wrong calculation of blood amount in `ExpAffect()`
• Wrong MAP_ELEMENT member checked for blood type (#1808)
• Wrong variable used for dropping new blood on roof
=> Fix three blood / smell bugs

src/game/Tactical/Soldier_Init_List.cc
=> Fix placement of Kingpin's group when they have become hostile

dependencies/lib-magic_enum/getter/CMakeLists.txt.in, src/externalized/scripting/EnumCodeGen.h
=> Upgrade magic_enum to 0.8.2

COMPILATION.md, ISSUE_TEMPLATE.md, README.md, docs/Release-checklist.md
I fixed a variety of spelling, grammar, and formatting issues in some of the Markdown files.  I also resolved a bunch of warnings from the Markdown linter.
=> Doc cleanup

src/game/Strategic/Strategic_Merc_Handler.cc, src/game/Strategic/Strategic_Merc_Handler.h
=> Fix crash when insured merc dies without an attacker

src/sgp/Input.cc
• Add the fix for #539 suggested by Tercus
• Use the special treatment for some keys added in #1853 also
when Num Lock, Caps Lock or Scroll Lock are active
=> Improve handling of modifier keys

src/game/Tactical/LoadSaveVehicleType.cc
It is somehow possible for a merc to be in a vehicle's passenger list while having an assignment other than VEHICLE. This commit detects this situation and tries to bring the game state back to normal.
Obviously this doesn't fix the underlying issue that it shouldn't even possible to get into the state described in #1885, but at least now players have the chance to continue their game without having to dismiss the merc in question.
=> Detect wrong soldier state when loading a VEHICLETYPE

src/game/Editor/EditorMercs.cc
RenderWorld could attempt to use a non-existing animation frame because not all body types have the same number of animations. Also make this function less eager to kill the program by removing one assert and one abort() call.
=> Fix crash in ChangeBodyType

src/game/Editor/SelectWin.cc
=> Don't crash when cancelling the selection window

android/app/src/main/java/io/github/ja2stracciatella/ConfigurationModel.kt, android/app/src/main/java/io/github/ja2stracciatella/Ja2Json.kt, android/app/src/main/java/io/github/ja2stracciatella/LauncherActivity.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/LogsTabFragment.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/SectionsPagerAdapter.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/SettingsFragment.kt, android/app/src/main/res/layout/fragment_launcher_logs_tab.xml, android/app/src/main/res/layout/fragment_launcher_settings.xml, android/app/src/main/res/values/strings.xml, rust/Cargo.lock, rust/stracciatella/Cargo.toml, rust/stracciatella/src/logger.rs, src/sgp/SGP.cc
Just here for the builds again :wink:.
This adds a tab to the Android launcher for easier bug reporting / debugging.
=> Implement tab to view logs in Android launcher

src/game/SaveLoadGame.cc, src/game/Tactical/Squads.cc, src/game/Tactical/Squads.h
=> Use the old way to load squads if save is of an older version

.mailmap, contributors.txt
added aliases and new entries.
=> updated contributors lists

src/game/Strategic/MapScreen.cc
This menu does not have useful options for EPCS; the Dismiss option could even cause serious problems (issue #1980).
Also addresses two clangd complaints about unnecessary copies and removes some duplicated code with a function call in DrawCharacterInfo().
=> Disable contract menu for EPCs

src/game/Tactical/Turn_Based_Input.cc
• Split HandleModAlt in two functions for a clean seperation
of regular and debug/cheat keys.
• Remapped the end AI turn cheat from Alt+Return, which toggles
between fullscreen and windowed mode, to Alt+6.
• Merged GrenadeTest1 and GrenadeTest2 into one function • Alt+y not only recruited Maria in cheat mode but also gave
MadLab's robot a new G41, even without cheats. This is now
a cheat activated by Alt+7.
• Remapped "next shot is autokill" from Ctrl+Alt+k to Alt+8.
Resolves #1977.
=> Maintenance work on Alt key handling in tactical mode

src/game/TileEngine/RenderWorld.cc
Instead of passing the same three start and end coordinates pairs every time we now have a new class to hold these value; RenderTiles is a method of this class and can access its former arguments without any changes.
A little helper function allows us to pass the RenderLayerIDs directly inside the function call, no need to fill in an array first and count the IDs.
=> Implement an easier way to call RenderTiles()

.ci/ci-functions.sh, .github/workflows/coverity-scan.yml, .github/workflows/github-ci.yml, .github/workflows/nightly.yml
I have not seen any breaking changes for our usecases, so lets see if upgrading everything works.
Edit: The issue with the Android SDK is quite weird. It seems to use the wrong java version, although all pointers point to a different one. Will continue debugging this soon.
=> Upgrade all GitHub action tasks

src/game/Editor/EditorItems.cc, src/game/Laptop/BobbyR.cc, src/game/Laptop/Store_Inventory.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/Items.cc, src/game/Tactical/ShopKeeper_Interface.cc
Remove some more references to `MAXITEMS`.
=> Remove some more references to MAXITEMS

src/game/Strategic/Strategic_Movement.cc
=> Check for and reapir wrong group id while loading

src/game/Laptop/Personnel.cc
No more uninitialized variables in this function.
=> Address HACK000E comments in DisplayTeamStats

src/game/TacticalAI/Attacks.cc
Crash happened when the AI considered throwing a grenade. Grenades do not count as weapons, so the weapon pointer was NULL.
This commit also tones down the gigantic block of variable declarations at the top of the function a bit by moving down several variables to the location of their initialization.
=> Fix crash in CalcBestThrow

docs/archeology/TODO, src/game/Editor/Smoothing_Utils.cc, src/game/Tactical/Overhead.cc, src/game/TileEngine/TileDef.cc, src/game/TileEngine/TileDef.h, src/game/TileEngine/WorldDef.cc, src/game/TileEngine/WorldMan.cc, src/game/TileEngine/WorldMan.h
-   It's no longer possible to get stuck in an endless loop in the very unlikely case where we find a LEVELNODE with an usIndex oF NO_TILE.
-   Refactored TypeRangeExists... functions.  Changed three "find roof or floor" functions to use   TypeRangeExists...
-   Replace eight levelnode remove functions with a function template
-    Change the return type of TypeRangeExistsInLandLayer so it matches the other two TypeRangeExists... functions.
=> Address TODO0009: possible endless loop

src/externalized/tileset/TilesetTileIndexModel.cc, src/externalized/tileset/TilesetTileIndexModel.h
Before this function just always returned an empty string.
=> Implement TilesetTileIndexModel::serialize

src/game/TacticalAI/NPC.cc
=> Fix crashing due to missing script records

src/game/Strategic/Strategic_AI.cc, src/game/Strategic/Strategic_AI.h
Two functions that were defined but never called and one function declaration without a matching definition.
=> Remove unused code in Strategic_AI

src/game/Strategic/Creature_Spreading.cc, src/game/Strategic/Creature_Spreading.h
DetermineCreatureTownComposition and PrepareCreaturesForBattle are almost text book examples for discrete_distribution use cases.
=> Modernize random number generation for creature spreading

src/game/Strategic/Strategic_AI.cc
Two arrays were leaked if you started a new game and then quit that game and started another new one.
Looking a bit closer the array gubPatrolReinforcementsDenied was not actually used for anything.
=> Fix memory leak in Strategic_AI

src/externalized/LoadingScreenModel.cc, src/externalized/LoadingScreenModel.h, src/externalized/MagazineModel.cc, src/externalized/MagazineModel.h, src/externalized/WeaponModels.cc, src/externalized/WeaponModels.h, src/externalized/mercs/MERCListingModel.cc, src/externalized/mercs/MERCListingModel.h, src/externalized/strategic/CacheSectorsModel.cc, src/externalized/strategic/CacheSectorsModel.h, src/externalized/strategic/MovementCostsModel.cc, src/externalized/strategic/MovementCostsModel.h, src/externalized/strategic/NpcPlacementModel.cc, src/externalized/strategic/NpcPlacementModel.h, src/externalized/strategic/SectorLandTypes.cc, src/externalized/strategic/TownModel.cc, src/externalized/strategic/TownModel.h, src/externalized/strings/ItemStrings.cc, src/externalized/tactical/SmokeEffectModel.cc, src/externalized/tactical/SmokeEffectModel.h
This attempts to fix all of the occurences inside a `deserialize` method.
=> More copy instead of move fixes

src/game/TileEngine/Physics.cc
• Removed several unused preprocessor macros
• Removed second parameter of SimulateObject (always DELTA_T) • Removed always false variable fDampingActive
• Changed return type of two functions that always returned
TRUE to void
• Removed unused last parameter of PhysicsHandleCollisions • Removed overriden second parameter of CalculateSoldierMaxForce • Fixed two incorrect comparisons of structure IDs
=> Minor cleanup of Physics.cc

src/game/Tactical/PathAI.cc, src/game/Tactical/PathAI.h
A lot of duplication needs removing after #1995.
This is in preparation to a possible enhancement enabling diagonal interaction with doors.
=> Refactor pathfinding through doors

src/game/Editor/SelectWin.cc, src/game/Tactical/Interface_Control.cc, src/game/Utils/Text_Input.cc, src/sgp/Types.h
Another case of stdlib allowing for some minor cleanup.
=> use std::swap instead of a hand-rolled version

src/game/Strategic/Map_Screen_Interface_Map_Inventory.cc
Rewrite four functions that are very similar and were obviously copy & pasted to use a common helper function.
=> Minor cleanup of printing functions

src/externalized/DefaultContentManager.cc
=> Enable mod-aware fixing of vanilla binaries by stracc script record json file

src/externalized/DefaultContentManager.cc
=> Fix wrong path separator for Linux systems

dependencies/lib-sol2/CMakeLists.txt, dependencies/lib-sol2/getter/CMakeLists.txt.in, dependencies/lib-sol2/getter/gcc-15.patch
based on some incomplete gentoo patches and redoing all of it because sol uses mixed line endings
fixes #2168
=> sol: fixed compilation with gcc 15

src/game/Laptop/AIMMembers.cc, src/game/Laptop/IMP_Attribute_Selection.cc
=> fixed marksmanship typos [ci skip]

src/game/Strategic/Strategic_Merc_Handler.cc, src/game/Tactical/CMakeLists.txt, src/game/Tactical/Items.cc, src/game/Tactical/Soldier_Profile.cc, src/game/Tactical/Weapons.cc, src/game/Tactical/Weapons.h, src/game/Tactical/Weapons_unittest.cc
This adds some unit tests to armour calculations and fixes some usages of `asArmour` and `IC_ARMOUR`.
=> Some more armour cleanup

rust/stracciatella/src/schemas/yaml/script-records.schema.yaml, rust/stracciatella/src/schemas/yaml/smoke-effects.schema.yaml, rust/stracciatella/src/schemas/yaml/types/base-item.schema.yaml
These are some fixes for the schema, that come out of updating the stracciatella toolset. Those are quite minor fixes, so I think it is still good to go into this release.
=> Some schema fixes
