Build/Tactical/Dialogue_Control.cc
If a cutscene is ended by an NPC action then an extraneous dialogue pop
is executed. This patch adds a check to prevent an empty queue from
being acted on. The true bug may be the return value of Execute and the
correct patch to return the opposite boolean value.
=> Fix #198: end of meanwhile cutscene crash

Build/Strategic/Strategic_Merc_Handler.cc
Bitbucket Comments:
@lynxlynxlynx:
While the usefulness of locking is questionable there, wouldn't it be better to just unlock it afterwards? Or does the execution of the dialog happen in the next tick?
@selaux:
I couldn't dig anything particularly insightful from the refactoring history.
=> Fix #200: Dont end up in a locked ui state when somebody leaves.

Build/Tactical/Handle_Items.cc
I've traced the variable and nothing particularly interesting happens. The money transaction works normally and is dumped to the ground just fine with a full inventory.
=> fixed #199 (rare boxing crash)

sgp/SGP.cc
Issue: All command line arguments after `-debug`, `-unittests` and `-no3btnmouse` are ignored.
Expected Behavior: `-unittests` should be prioritized before all other arguments
=> Correctly prioritize the unittests command line switch.

Makefile
`make build-releases` referenced old paths. Now it works again. I tested the resulting builds on the following configurations and they seem to run fine. Building the Mac release still needs to be tested though and we could consider creating an .app directory structure instead of a common build so it integrates better for OS X users. Then we are ready to do a release.
- Ubuntu 12.04 i386
- Ubuntu 14.04 i386
- Ubuntu 14.04 x64
- OS X 10.11
- OS X 10.9
- Windows 10 x64
=> Fix `make build-releases`

sgp/SoundMan.cc
This is a proposed fix for #78. Since `44100hz` waves sample rates were halved when loaded, I doubled the sample rates of the `11025hz` samples. This seems to fix the affected sounds. A few notes though:
- I could not test with any stereo samples since i could find none. If anybody could point me to some I could test if they work as well (8 and 16bit)
- There is a lot of  `.WAV` file parsing going on in `SoundMan.cc` not sure if we want to keep this in the long run. SDL also has functions to load WAV files, which I tried to use but in the end failed. But this might be a better approach.
=> Fix #78: Double sample rate of sound samples if necessary.

sgp/MemMan.cc, sgp/MemMan.h
Stumbled across this when trying to rework logging. Situtation on Master right now is we have 3 possible Memory-Backends:
- "for release versions" we use a pretty standard wrapper around stdlib
- "_DEBUG" switches on an old implementation that Tron originally marked as to do. It logs some stuff but is broken right now (semms he added the release version to not depend on this one)
- "EXTREME_MEMORY_DEBUGGING" turns on a beast that logs everything that happens with Memory
In this PR, I deleted the _DEBUG variant. The extreme version still compiles but question is whether we need it. I think the widely used stdlib implementation is the way we should go. In the wrapper, we throw exceptions on bad allocations and for me this seems reasonable and enough.
In conclusion, I would vote for removing …
=> Mem man cleanup

Build/Tactical/OppList.cc
not obvious here but bInWater is later used again (expand context two times to see it) but would always be false.
=> fix an obviously forgotten assignment to bInWater in MovementNoise

Build/Cheats.h, Build/GameScreen.cc, Build/GameState.cc, Build/GameState.h, Build/JAScreens.cc, Build/Tactical/OppList.cc, Build/Tactical/Turn_Based_Input.cc, Build/TileEngine/Structure.cc, Build/TileEngine/WorldMan.cc, Build/Utils/Debug_Pages.cc, Build/Utils/Debug_Pages.h, Makefile, sgp/SGP.cc
I enabled some debug screens to be accessible when using the `-debug` parameter.
Tactical Screen
- `F11` for Quest Debug Screen
- `CTRL+f` for FPS Display
- `CTRL+z` to toggle z-buffer
- `ALT+m` for level node debug mode
- `ALT+n` to play quotes of hovered merc
- `q` for soldier and land debug mode
- `y` for struct debug mode
To exit any screen press `q`. To cycle through different pages use pageup and pagedown.
I'm in the progress of making everything look pretty and usable. Progress:
Examples:
=> Debug screens

.travis.yml
This allows us to run a coverity scan every time the coverity-via-travis branch is updated. We should merge this into master though, so we can simply create a PR from master to this branch to get a fresh build. I'm currently waiting for the first build to complete to see if everything works.
We could also create a bot that does that every week.
=> Fix #201: Add coverity testing via coverity-via-travis branch.

Build/Laptop/EMail.cc
1: HandleIMPCharProfileResultsMessage: adjust the size of a w_char_t array to the actual maximum size fo a mercs name
2: AddEmailRecordToList: add a 0-termination to a string at the end. all callers currently don't exceed its length but it's safer to ensure this here.
=> Fix 2 Coverity issues in Email.cc

Build/Laptop/EMail.cc
1, Function "AddEmailRecordToList" is called with parameter "text" which is always an array of length MAIL_STRING_SIZE.
therefore text[MAIL_STRING_SIZE] = 0; causes accessing an array out of bounds.
2, MAIL_STRING_SIZE length of pRecord should be sufficient. Maximum length that is read from data files is MAIL_STRING_SIZE (including trailing zero).
=> Fixed stack corruption

Build/Tactical/LOS.cc
caused by mixed-up array indices. Original by vxx.
=> fix undefined behaviour in LOS.cc

_build/lib-boost/boost/detail/lightweight_mutex.hpp, _build/lib-boost/boost/filesystem/detail/utf8_codecvt_facet.hpp, _build/solution-xcode/JA2-Stracciatella.xcodeproj/project.pbxproj
Addresses #331, #332 and #333. Provides missing boost headers and updates the xcode project. Also changes architecture though I do not know if that was only necessary on my machine.
=> Fix build for xcode osx

Build/JAScreens.cc, Build/MainMenuScreen.cc, Build/UILayout.cc, Build/UILayout.h
Removes it from the splash instead otherwise it looks weird with the copyright fading in.
=> Fix #300: Show version number in main menu

CMakeLists.txt
- Otherwise compiler will choose language level, which e.g. does not work for me in mingw.
=> Set CXX_STANDARD for cmake

Build/Tactical/LoadSaveSoldierType.cc
Found this when loading the savegame from #367. Loop was executing endlessly because of corrupt savegame data. Afterwards loading looked fine.
=> Fix infinite loop with broken savegames when loading

Build/Strategic/Campaign_Types.h, Build/Strategic/Strategic_Movement.cc
E.g. when a group is not moving it does not have a previous sector.
Fixes #356.
=> Only check retreat conditions for valid sectors

Build/Strategic/Auto_Resolve.cc, src/CMakeLists.txt, src/ui/CMakeLists.txt, src/ui/Easings.cc, src/ui/Easings.h, src/ui/Easings_unittests.cc
Fixes #381 
- Replace custom easing function with standard cubic one
- Reduce complexity of function
=> Extract easing from DoTransitionFromPreBattleInterfaceToAutoResolve

Build/Tactical/Campaign.cc
Should fix #364.
Not sure why this broke (I'm blaming cmake), but it seams for gcc
there is no abs(short), and newer versions fall back to abs(double)
which returns a double and breaks the sprintf
=> Fix printing of stat strings

CMakeLists.txt
- DESTINATION share/man/man6/ja2.6 is incorrect, it creates named
directory instead of renaming the file. Use RENAME instead
- Introduce condition for FreeBSD-specific manpage directory. Other
*BSDs may use it as well
=> Fix manpage installation

Build/Editor/Cursor_Modes.cc, Build/Editor/SelectWin.cc, Build/Editor/Smoothing_Utils.cc, Build/Laptop/AIMMembers.cc, Build/Laptop/BobbyRGuns.cc, Build/Laptop/Personnel.cc, Build/Strategic/MapScreen.cc, Build/Strategic/Strategic_AI.cc, Build/Strategic/Strategic_Movement.cc, Build/Strategic/Strategic_Pathing.cc, Build/Tactical/Arms_Dealer_Init.cc, Build/Tactical/Campaign.cc, Build/Tactical/Handle_UI.cc, Build/Tactical/LOS.cc, Build/Tactical/Merc_Hiring.cc, Build/Tactical/PathAI.cc, Build/Tactical/Real_Time_Input.cc, Build/Tactical/ShopKeeper_Interface.cc, Build/Tactical/Soldier_Add.cc, Build/Tactical/Soldier_Ani.cc, Build/Tactical/Soldier_Create.cc, Build/TacticalAI/AIUtils.cc, Build/TacticalAI/FindLocations.cc, Build/TacticalAI/Movement.cc, Build/TileEngine/Isometric_Utils.cc, Build/TileEngine/Lighting.cc, Build/TileEngine/Overhead_Map.cc, Build/TileEngine/RenderWorld.cc, Build/Utils/Sound_Control.cc, sgp/Types.h
Follow up of  #388 i replaced all `abs()` that were not explicitly `fabs()` with a macro that does a integer abs.
This seems to fix (at least) the AI deadlocks occuring during enemy turns.
=> Use integer abs function where necessary

Build/SaveLoadScreen.cc
The addiotional checks dont really make sense here since the second branch does not depend on tmpGuiPreviousOptionScreen.
@RinneT Can you have a look at this? Currently most of my saves get corrupted.
=> Fixes dead is dead saves when exiting game

CMakeLists.txt
Otherwise the headers will use dllimport/dllexport, which breaks the linking process on windows.
=> Re-add MICROINI_STATIC definition for headers

CMakeLists.txt, _build/buildboxes/openbsd-5.9/bootstrap.sh
Was using "system" gcc 4.2.1 which does not understand BOMs.
=> Use current version of gcc on OpenBSD

Build/Laptop/IMP_Begin_Screen.cc, Build/Laptop/IMP_HomePage.cc, Build/Laptop/IMP_HomePage.h, Build/Utils/Text_Input.cc, Build/Utils/Text_Input.h, sgp/Input.cc, sgp/Input.h, sgp/SGPStrings.cc, sgp/SGPStrings.h
Closes #419 
This ended up in an almost complete rewrite of the `IMP_HomePage` and `IMP_Begin_Screen` Screens. Basically they had own custom code to handle input fields and keyboard input. I replaced it with inputs from `Text_Input`. Additionally I had to fix that keydown events were not marked as handled anymore, so e.g. pressing one inside an input on the save screen afterwards selected the first save slot. Implications from all of this:
- If a text input is focused, almost all key events are ignored by the respective screens (except for some "chosen" ones)
- The cursors now blink differently on the two mentioned screens than before
- Checkboxes on `Imp_Begin_Screen` now dont get focus anymore when they are hovered over
- Removed ifs that mentioned visiting the `IMP_Begin_Screen` after …
=> Fix issues with text inputs

Build/MainMenuScreen.cc
- Save buffer is restored by the button system, so first we need to blit to frame_buffer (because it is cleared) and then to the save buffer (to be able to restore). Otherwise we would restore from a non-cleared save buffer
- Fixes #72, #106 
Builds 🙂 : http://builds-ja2.stefanlau.com/pull-requests/446/
=> Blit main menu backgrounds to frame buffer

.travis.yml, appveyor.yml
Solution: Dont try to upload package when no sftp password is set.
Rationale: This is a security issue since a user could create a PR which basically reads sftp credentials and sends them somewhere. This is why secure variables are not set in CI non-orga PR builds.
=> Fix PR building for non-organization PRs

Build/Strategic/Strategic_Turns.cc, Build/Tactical/Overhead.cc, Build/TileEngine/Physics.cc, Build/TileEngine/Tile_Animation.cc
Instread of checking for time compression modes manually, we can check if time is being compressed...
Fixes #160 
Also fixes an error with the debug message when there is no owner of the explosion (found when loading the attached savegame)
=> Check for time accelleration properly when checking for end of turn

src/game/Strategic/MapScreen.cc
When merc is leaving the `.merc` member might not be present anymore for the currently selected slot. So we should handle it as if there is no merc currently selected, not throw.
Fixes #462.
=> Return NULL from GetSelectedInfo char when no merc is attached to slot

CMakeLists.txt
This is a minimal version of #463 without the nightmarish `#include` path commit.
It allows to use system wide installations of RapidJSON and GTest and cleans up some minor things.
=> CMake cleanup (minimal version)

cmake/FindRustc.cmake, rust/CMakeLists.txt
Both minimal versions might have to be increased (see #483).
=> Added checks for rustc and cargo versions

src/sgp/SGP.cc
main() contains two calls to functions that are not present when you try to build without unit tests. Additionally it would be possible to completely remove the -unittests command line option in such builds but IMO options that are sometimes present, sometimes not kind of suck.
=> Build fails if WITH_UNITTESTS is off

src/sgp/VObject_Blitters.cc
Fix #468: convert a couple of unsigned 16-bit integers
to signed 32-bit integers to ensure it is safe to add them to
other signed integers. No more 30 + -33 = 65533.
=> Fix segfault in Blt8BPPDataTo16BPPBufferTransZNBClipTranslucent

src/game/Strategic/Strategic_Movement.cc
A typo in PlayersBetweenTheseSectors leads to an incorrect calculation
of sec_next. Fixes #467.
=> Fix squard movement arrows on strategic map

rust/CMakeLists.txt
`cmake -E env` has only been introduced in CMake 3.1.
This will provide clear error message in case user's CMake is outdated.
Compare https://cmake.org/cmake/help/v3.1/manual/cmake.1.html
and https://cmake.org/cmake/help/v3.0/manual/cmake.1.html
=> Fix #500: update required cmake version

src/game/Tactical/Points.cc
Fixes the 'invalid movement mode 299' warnings that occasionally
flood the console.
=> Teach (Estimate)ActionPoints about KID_SKIPPING

src/sgp/Input.cc
This fixes the crash described in #497.
Although it does not fix the underlying issue, I think it is a good idea to add the `try{} catch{}` because it is very easy to hit a wrong key and lose all game progress.
=> catch InvalidEncodingException& in TextInput(...)

src/sgp/FileMan.cc, src/sgp/FileMan.h, src/sgp/Smack_Stub.cc, src/sgp/SoundMan.cc
This sets 44100Hz 16bit as the target audio spec and converts all loaded files (currently in-memory) into this format.
- Makes output rendering easier
- Fixes bad audio on sdl2 (#444)
Issues:
Both points proove quite hard to implement. Streaming is hard and SDL2 does not have a function to read only wav spec.
=> Fix sdl2 audio

src/sgp/SoundMan.cc
to prevent crash when a sound is not found.
=> Add try{} catch{} to SoundLoadDisk

src/sgp/Input.cc, src/sgp/Input.h
Alternative to #506 using @momoko-h's code.
Shrink the size of gfKeyState from 1Gb + 512 to 128 bytes
Remap SDL keycodes with bit 30 set to make them usable as gfKeyState indices.
=> Shrink gfKeyState (alternative)

src/game/Tactical/Bullets.cc
with the missile smoke animation.
The missing animation could lead to crashes when accessing
the unfinished flame thrower weapon using cheats.
Resolves a part of the issues mentioned in #521
=> Replace reference to non-existing flame animation

src/sgp/SoundMan.cc
Disregard the invalid sound on release builds. Throw on debug builds.
Superficial fix for #528. Obviously the underlying issue should be fixed as well.
=> Check if argument of SoundLoadDisk() is an empty string.

src/game/MessageBoxScreen.cc, src/game/MessageBoxScreen.h, src/game/Strategic/Town_Militia.cc
inline the remaining one line function for the sake of clarity
=> Fix #540: always show militia dialogues in the same spot

rust/src/stracciatella.rs
This should (hopefully) fix the UNC prefix issue on Windows and the `/private` prefix issue on Mac.
Related to #515 and #559.
=> Fix rust datadir parsing

src/game/Tactical/Interface_Control.cc
fixing #550. 
I am not that happy with that solution though. I Tried to ignore the next Left-Mousebutton-Up so if you command a merc to open a door/talk to a person/... and hold the button down it would not close the menu after. I wasn't able to do that because the event system in the code is kind of unpredictable.
Maybe the way it works with my commit is enough and not a problem for the user-experience view.
=> Selecting Area not resetting after being interrupted by menus

rust/src/stracciatella.rs
to match the upstream rust getopts changes.
NOTE: This fix breaks the unit test for older versions of getopts
Hacky fix for #562
=> Drop the dot in the unrecognized option unit test

src/game/Tactical/Handle_UI.cc
fixes #188 
preinit a value to prevent false ap costs; actions which dont charge turning ap are coming after this line and put the value to true. The assumption should be that every tunring costs ap not the other way round.
=> preinit dontchargeap to prevent false AP costs

src/game/SaveLoadGame.cc, src/game/Strategic/StrategicMap.cc, src/game/TacticalAI/AI.h, src/game/TacticalAI/Knowledge.cc
fixes the first part of #126
I recognized that loading an ambush gamestate could lead to get the wrong statuscode for encounters because they were loaded later. I get around this by calling the enemies to ambush after a gamestate has been fully loaded.
Also I introduced a new method called CallAvailableTeamEnemiesToAmbush to prevent code duplication.
=> Passive bloodcat ambush fix

src/game/Tactical/Bullets.cc
fixes #395 
A little bit hacky because some sectors deliver tripled z positions. As there are only a few ways to throw a knife(ground->ground, roof->ground, roof->roof, ground->roof) we can overcome this problem by decreasing the values while don't affecting gravity or precision.
=> fixed wrong animations in some sectors for throwing knifes

src/game/Tactical/OppList.cc
fixes #402 
While soldiers/mercs were climbing there is a short time in which they have no fixed grid_no. If you use the WhosIsThere method to determine the soldier on that grid_no it returns 0(null). So by checking whether the value is 0 we can overcome the problem of false calculations of visibitily while climbing.
=> checking for existence of subject while climbing

src/game/GameLoop.cc, src/game/SaveLoadGame.cc, src/game/SaveLoadGame.h
Stumbled upon this while reviewing the whitespace changes.You can force to trigger this code for testing by initialising ```gfCheckForFreeSpace...``` to TRUE. I tested the inner if by comparing the free space to ```(uintmax_t) -1```.
=> Minor cleanups

src/game/Tactical/Soldier_Ani.cc
fixes #84 
After reaching the top of a roof we set the ui for that merc to crouching rather than doing nothing and keeping the standing state for movements.
=> Climbing up on a roof now no longer leads to standing up for movement

src/game/Tactical/OppList.cc
Reverts the change faulty change in #585 see the discussion for more information(thanks to chmallon)
new approach for fixing #402 
As the method distancevisible is also used on empty grids(no soldier on grid) we can't return a 0 value. Now we calculate the visibility correctly by night by using better conditions for lightlevel-calculation.
=> Climbingvisibility revert + new bugfix

.travis.yml
one sudo less (closer to container-based runs) and fixes this apt dependency problem that recently broke the build:
> The following packages have unmet dependencies:
>  libsdl2-dev : Depends: libegl1-mesa-dev
>                Depends: libgles2-mesa-dev
> E: Unable to correct problems, you have held broken packages.
=> travis: use the apt addon

CMakeLists.txt
in gentoo, the library should end up in /usr/lib64 otherwise there's a qa check failing. therefore, make the library path configurable.
```
making executable: usr/lib/libstracciatella.so
Files matching a file type that is not allowed:
usr/lib/libstracciatella.so
* ERROR: games-strategy/ja2-stracciatella-9999::poncho failed:
*   multilib-strict check failed!
* 
* Call stack:
*   misc-functions.sh, line 605:  Called install_qa_check
*   misc-functions.sh, line 217:  Called source 'install_symlink_html_docs'
*   80multilib-strict, line  46:  Called multilib_strict_check
*   80multilib-strict, line  42:  Called die
* The specific snippet of code:
*   		[[ ${abort} == yes ]] && die "multilib-strict check failed!"
```
=> make INSTALL_LIB_DIR configurable

src/game/Tactical/Handle_UI.cc, src/game/Tactical/Points.cc
fixes #192 
If enemys are unreachable due to a blocking door etc. the game puts a message. If you try to right click on the enemys you sometimes receive calculated AP-costs, what can be used with a left click to start an attack for 0AP. Now it checks whether the enemy is reachable.
=> Attack for 0 AP fix for unreachable enemys

src/game/TileEngine/Explosion_Control.cc
Fixes #600 
Check for existent structure on the spot and the bLevel. If there isn't any structure we can't spread the smoke.
=> fixed smoke leaving roof edge

src/game/Tactical/PathAI.cc, src/game/TileEngine/Explosion_Control.cc
Fixes #94 
Some defines weren't used for explosion calculations, also the spread of grenades was stopped due to high structureheight which is weird because the default size for doors and walls is 4.
=> Fixed grenades getting blocked by open doors

src/game/TileEngine/Explosion_Control.cc
Fixes #477 
Preventing damage on the wrong level by rechecking whether there is gas on the grid and height-level, also considering gasmask etc..
=> Fixed error with gas on roof hitting mercs below

src/game/Laptop/Laptop.cc
fixes #426 
In the code there wasn't any handling for the CTRL and + cheat. So added it.
The value for decreasing the money value was 10.000 therefore too low. I increased it to 100.000.
Disclaimer: I have a german keyboard layout.
=> Moneycheat added (Laptopview and + key)

src/sgp/SoundMan.cc
This should fix #609. But it comes with a new problem: Performance. Basically everytime a music piece (aka. long sound) is loaded, this results in a tiny hang. Not sure if that was the same before and not sure if we can actually improve performance on this.
Imho it does too many big allocations (one for source wav, one for cvt buffer, one for destination wav). It would probably be better to stream into AudioCVT, with preallocated tiny buffers. I tried this approach already once, but failed implementing it. It's not as simple as it seems, as you have to ensure that you have enough content in the buffers, so the data can be pulled at any time.
=> Copy audio into a buffer of the correct size

src/launcher/Launcher.cc, src/launcher/Launcher.h
Predefined resolution input is set to 640x480 if custom resolution is selected as startup.
Custom resolution is set to predefined resolution when predefined resolution is selected at startup.
=> Launcher: Always set both resolution input values to something useful

COMPILATION.md, src/game/MainMenuScreen.cc, src/sgp/SGP.cc
Fix (or rather workaround) for #608
=> SDL2 2.0.6 Warnings

src/game/Tactical/LOS.cc
It was always considered a miss.
one of the fixes from vvx's work
=> Do not increase shots fired statistic without a live target

CMakeLists.txt, src/sgp/UTF8String.cc, src/sgp/UTF8String.h
I got annoyed that we cannot use modern C++ features, so I updated the C++ standard we use to C++11.
I removed the `throw` annotations as they are deprecated with C++11. According to the [spec](http://en.cppreference.com/w/cpp/language/noexcept_spec) all the functions are potentially throwing functions so the annotations should not matter.
It now builds for me without warnings. Lets check if it is the same on macOS/Windows.
=> Increase C++ standard to C++11

src/launcher/StracciatellaLauncher.cc, src/launcher/StracciatellaLauncher.fl
Note: This requires some reshuffling of the other widgets as well, because
"Game" needs more space than "Data" for non-monospace fonts.
=> Launcher: change label "JA2 Data Directory" to "JA2 Game Directory"

src/game/Utils/_RussianText.cc
When I'm using RUSSIAN game version, as soon as I try to open load screen, the game crashes. 
Added missing entry s_rus_gs_dead_is_dead_mode_tab_name to g_LanguageResRussian array.
RUSSIAN_GOLD version seems to already have it.
=> Fix crash during load screen with RUSSIAN data files

src/game/Laptop/IMP_Attribute_Selection.cc
The old calculation in `SliderRegionButtonCallback` was wrong.
This also fixes some typos inside comments.
Fixes #644
=> Refactor skill value from mouse position calculation.

src/game/Tactical/Weapons.cc
Check if item is a weapon before entering the dual wielding penalty calculation
code.
GCM->getWeapon() returns NULL if the item is not a weapon.
Fixes #495
=> Prevent segmentation fault in CalcChanceToHitGun()

src/game/Tactical/Interface_Items.cc
always throw it.
Without this fix it is possible to give an item to an unnamed NPC via the
alternative cursor mode that can be activated by right clicking while
hovering over the NPC. This causes a softlock that displays the spinning
watch indefinitely.
Fixes issue #694
=> Never give an item to an unnamed NPC

src/game/Tactical/Interface_Utils.cc, src/game/Tactical/ShopKeeper_Interface.cc, src/game/Tactical/World_Items.cc
A SIGFPE can happen if cycling through items in Alt+w cheat mode. With this change the exception is gone.
=> fix possible division by zero / SIGFPE

src/game/Strategic/Strategic_AI.cc
When enemy patrol group notices player group in section with garrison, Strategic_AI::HandlePlayerGroupNoticedByPatrolGroup() will send enemy group in PURSUIT and it will cause crash because of following assertion failure in Strategic_AI::MoveSAIGroupToSector():
```
/* Make sure that the group isn't moving into a garrison sector. These sectors
* should be using ASSAULT intentions! */
Assert(intention != PURSUIT || SectorInfo[sector].ubGarrisonID == NO_GARRISON);
```
Have attached the [SaveGame07.zip](https://github.com/ja2-stracciatella/ja2-stracciatella/files/2508869/SaveGame07.zip) that will cause the crash by advancing the time for few seconds. You have to retry it few times so RNG will trigger enemy patrol notice.
=> Fixed crash due to assertion in Strategic_AI::MoveSAIGroupToSector()

assets/distr-files-linux/ja2_manpage, rust/src/stracciatella.rs, src/externalized/RustInterface.h, src/sgp/SGP.cc, src/sgp/Video.cc, src/sgp/Video.h
As the title says. It allows to set brightness value so it corrects the gamma in game.
=> Added brightness/gamma setting to ja2.json. closes #709

rust/src/stracciatella.rs
When starting game directly without ja2-launcher and no brightness setting defined in json or command line it would default to 0.0, and whole screen would turn completely dark.
I'd appreciate if someone with more experience in rust and serde_json would check this to confirm this is correct solution. Apparently serde(default) would set this value to 0.0 instead of using what was defined here: https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/rust/src/stracciatella.rs#L196
I thought serde(default) is just supposed to add line to json if not present using the default value from that line... apparently not.
Edit: this was introduced by changes from my pull request #734
=> Fixed game starting completely dark.

rust/src/config/cli.rs, rust/src/config/engine_options.rs, rust/src/config/ja2_json.rs, rust/src/config/mod.rs, rust/src/config/resolution.rs, rust/src/config/scaling_quality.rs, rust/src/config/stracciatella_home.rs, rust/src/config/vanilla_version.rs, rust/src/stracciatella.rs, src/game/GameRes.h
This is part of a multi-step refactoring i want to make. It basically extracts functionality into separate modules without touching the external interface. Next step would be to migrate tests to their respective modules and introduce an integration test from C++ using gtest.
The overall goal is for `stracciatella.rs` to only contain the ffi bindings.
=> Modularize rust code

src/game/TileEngine/Render_Dirty.cc
This fixes #753. Commit 25503e9 was considering sizeof pointer instead of data it pointed to.
=> Fixed bad z-buf write during render dirty. refs #753

src/game/Laptop/IMP_Confirm.cc
There's a silly piece of code in IMP character generation.
If the character is CAMOUFLAGED they get a camo kit.
First, CAMOUFLAGED characters don't need camo kits, this is entirely useless for them.
Second, one can't create a CAMOUFLAGED IMP so this is dead code.
=> Removed silly camo kit addition

src/game/Tactical/Handle_Items.cc
Should fix #790.
Also fix #763.
=> Fixed bug when picking up items during combat doesn't deduct APs

src/game/Tactical/Weapons.cc
Should fix #778.
Previous variant had casting float to uint, damage to head was unchanged (1.5f -> 1), damage to legs was removed completely (0.5f -> 0).
Also, leg hit adjusts new impact by squared multiplier, in comments I proposed another variant of calculation.
=> Fixed AdjustImpactByHitLocation() - missing damage to legs, unchanged damage to head

src/launcher/Launcher.cc
It opens location in the input field instead of the system default.
=> Set the directory of the file chooser.

src/game/GameInitOptionsScreen.cc, src/game/Laptop/Laptop.cc, src/game/Tactical/Soldier_Control.cc, src/game/TileEngine/Explosion_Control.cc, src/game/Utils/Font_Control.cc, src/game/Utils/Music_Control.cc, src/game/Utils/Sound_Control.cc, src/sgp/SGP.cc, src/sgp/SoundMan.cc
also has a small vanilla ai bugfix included.
-Wall generates more-than-my-screen-buffer-full of extra warnings and I haven't tried -Wextra. I think we should clean it up and use -Werror for debug builds.
The spammer was ENUM_BITSET, which looks useless and random sampling of the users show no uses of the functions. Can probably be outright killed... It turns out that's tricky. While there are some useless users, converting to an old school templated class enum (the cxx11 keyword doesn't help — we need the methods) only almost worked. I couldn't get the bool operator to work, while the rest seemed fine. The simplest way out is to not use the enums as types in the first place.
Then there's the:
- ubLoop = ubLoop FIXME in LOS.cc:3472 …
=> fixed clang Warnings

rust/src/config/cli.rs, rust/src/config/engine_options.rs, rust/src/config/ja2_json.rs, rust/src/config/mod.rs, rust/src/config/resolution.rs, rust/src/config/scaling_quality.rs, rust/src/config/stracciatella_home.rs, rust/src/config/vanilla_version.rs
I really liked the adding of doc comments in #820, so I added comments to all exported things in `rust/src/config`. This should give a better overview over what exists in rust code and the responsibilities of the individual modules.
To see the current docs you can run `cargo doc && firefox target/doc/stracciatella/index.html` in the `rust` subdirectory (adapt for your favorite other browser :wink:)
=> Add some rust doc comments to exported things from rust/src/config

rust/src/stracciatella.rs, src/externalized/ModPackContentManager.cc, src/externalized/ModPackContentManager.h, src/launcher/Launcher.cc, src/launcher/Launcher.h, src/launcher/StracciatellaLauncher.cc, src/launcher/StracciatellaLauncher.fl, src/launcher/StracciatellaLauncher.h, src/sgp/SGP.cc
The launcher can edit the mods in `ja2.json`.
The game can use multiple mods. (order matters)
Launcher screenshot:
Those checkboxes are for selecting which mods you want to move up/move down/remove.
Addresses most of #321
=> Multiple mods + launcher

README.md, assets/distr-files-linux/ja2_manpage, rust/Cargo.lock, rust/Cargo.toml, rust/src/bin_resource_pack.rs, rust/src/config/cli.rs, rust/src/config/engine_options.rs, rust/src/config/ja2_json.rs, rust/src/stracciatella.rs, src/launcher/Launcher.cc, src/launcher/Launcher.h, src/launcher/StracciatellaLauncher.cc, src/launcher/StracciatellaLauncher.fl, src/launcher/StracciatellaLauncher.h, src/sgp/SGP.cc
To preserve backwards compatibility, ja2.json treats data_dir as an alias to game_dir.
The serde field attribute 'alias' requires serde_derive >= 1.0.85.
cbindgen was blocking serde_derive updates, so it was updated to 0.9.
The lock file also had to be updated.
=> Change all missnamed data dirs to game dirs

rust/Cargo.lock, rust/Cargo.toml, rust/src/bin_resource_pack.rs, rust/src/guess.rs, rust/src/librarydb.rs, rust/src/res.rs, rust/src/stracciatella.rs, rust/src/unicode.rs
Reference: #835
Is was using ascii caseless comparisons in the rustified LibraryDB.
It was decided that unicode caseless comparisons should be used.
Other code needs it too so I made the changes here instead of the original PR.
This PR introduces a `unicode::Nfc` struct that ensures the string is normalized and can be used for comparisons, caseless or not.
=> Use normalized unicode in rust

src/game/Editor/EditScreen.cc, src/game/Editor/Edit_Sys.cc, src/game/Editor/EditorTerrain.cc, src/game/Editor/NewSmooth.cc, src/game/Editor/Smooth.cc, src/game/TileEngine/WorldDef.cc, src/sgp/Random.cc
1. Use C++ facilities to generate uniform pseudo-random integer numbers.
2. Replace leftover uses of `rand()` with `Random`.
3. Add game policy to allow not recycling prerandom numbers.
Vanilla had this commented out in the name of optimization, but today computers are much more powerful and this is not a hot path so I don't see value in this optimization.
This PR is based on the opposite view of #777.
For me non-uniform pseudo-random numbers is a bug (`PreRandom` was not uniform) and issue #777 is not a bug.
=> Rework Random

src/game/Strategic/Merc_Contract.cc
The contract hasn't been renewed yet.
It needs to compare against the balance after contract renewal.
Fixes #93
=> Fix "enough money to extend life ensurance" test.

src/game/TacticalAI/DecideAction.cc
BestThrow.bWeaponIn can be NO_SLOT (-1) which leads to a silent out of
bounds access and an usItem value that I can't predict.
Closes #378
=> Fix out of bounds access in DecideActionRed.

COMPILATION.md
Got some errors about a missing "core" crate for rust when compiling on Debian for Windows, this fix solved the issue. Originally mentioned in https://github.com/ja2-stracciatella/ja2-stracciatella/issues/726
=> Add note about rustup and cross-compilation

src/externalized/DefaultContentManager.h
Reference #857
The AppVeyor console had this warning:
```
warning C4099: 'LibraryDB': type name first seen using 'struct' now seen using 'class'
```
=> Fix warning C4099

src/game/TileEngine/Explosion_Control.cc
Fixes #294
The grid had a wall and a switch, and received explosion damage.
While the wall received explosion damage, *ppNextCurrent pointed to the
switch. The switch was removed but *ppNextCurrent still pointed to the
switch and was used in the next loop.
=> Fix dangling pointer when removing structures on the right wall.

rust/Cargo.lock, rust/Cargo.toml, rust/src/guess.rs, rust/src/res.rs
This rewrites guessing vanilla version to some degree. Motivation for the change is mostly that I think it never worked as intended on my machine (because of not matching paths case insensitively). I found the logic hard to follow as well. 
- When building resource packs, resources are now read in parallel using rayon
- Iterators and HashMap are used instead of for loops
- Case insensitivity has been introduced
- When comparing resource packs, we first check for language specific resources (e.g. `german` subdirectory), this is just faster (at least on my machine) and less error prone. It will return a game version if ONLY files for this version are found
- We compare resource packs second, in parallel. We calculate percentages for each resource pack, e.g. how many files are missing in …
=> Rewrite guessing vanilla version

src/game/Utils/Music_Control.cc
Does not show an error in the log each time a music ends and the next music starts playing.
Fixes #805
=> Rework MusicStop.

.travis.yml, appveyor.yml, rust/build.rs, rust/src/bin_resource_pack.rs, rust/src/c/config.rs, rust/src/c/librarydb.rs, rust/src/c/logger.rs, rust/src/c/misc.rs, rust/src/c/mod.rs, rust/src/config/cli.rs, rust/src/config/engine_options.rs, rust/src/config/ja2_json.rs, rust/src/config/mod.rs, rust/src/config/resolution.rs, rust/src/config/scaling_quality.rs, rust/src/config/stracciatella_home.rs, rust/src/config/vanilla_version.rs, rust/src/file_formats/slf.rs, rust/src/guess.rs, rust/src/json.rs, rust/src/librarydb.rs, rust/src/logger.rs, rust/src/res.rs, rust/src/stracciatella.rs, rust/src/unicode.rs
Tasks:
-  [x] C code is contained inside module `c`
Postponed:
- split rust code into subcrates (lib, bin, C static lib)
A different PR:
- rename C functions
=> Reorganize rust

rust/build.rs, rust/cbindgen.toml
Simplify the use of `cbindgen`.
Add comments to the header.
Exclude constants of module `file_formats::slf`.
=> Rework header generation

src/game/Tactical/LoadSaveMercProfile_unittest.cc, src/sgp/LoadSaveData_unittest.cc
Reference #857
The AppVeyor console had warnings like this:
```
warning C4566: character represented by universal-character-name '\u0412' cannot be represented in the current code page (1252)
```
Visual Studio supports UTF-8, but it must not have a BOM.
=> Fix warning C4566

CMakeLists.txt
Continuation of #867
@lynxlynxlynx better let the tests finish before merging from now on >.<
Even if it works for me, it might not work in the builders, like what happened here.
=> Set the source and execution charset to utf-8 in MSVC

rust/src/c/config.rs, rust/src/c/librarydb.rs, rust/src/c/logger.rs, rust/src/c/misc.rs, rust/src/c/mod.rs, src/externalized/DefaultContentManager.cc, src/launcher/Launcher.cc, src/launcher/main.cc, src/sgp/FileMan.cc, src/sgp/Logger.cc, src/sgp/SGP.cc
Rename C-rust interface functions according to http://geosoft.no/development/cppstyle.html
The C-rust interface is an interface to rust code that is only used in C/C++.
Therefore it should try to use the recommended naming style of C++, which we have not defined.
#863 is an attempt to define a "last resort" recommended naming style (when there is no old code to reference).
Feel free to voice complaints about the names.
I just want a consistent naming style and can redo the PR.
Split from: #855
=> Rename C-rust interface

CMakeLists.txt, src/sgp/SGP.cc
This is an attempt to fix #485 and fix #487.
According to  https://stackoverflow.com/a/15440423, the wchar_t representation  is  platform-dependent  and  locale-dependent.
In particular, the LC_CTYPE category of the locale at compile time and at run time should be the same.
~This PR will attempt to make them match.~
This PR sets a unicode locale at the start, which hopefully means it can handle the characters of all game languages. (our linux and mac builders have a utf-8 locales)
=> Set locale at the start

rust/stracciatella_c_api/cbindgen.toml, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/launcher/Launcher.cc, src/launcher/Launcher.h, src/sgp/SGP.cc
Manually freeing rust memory is an easy recipe for resource/memory leaks, specially when exceptions are involved.
This PR introduces the use of `std::unique_ptr` with a custom deleter, aliased as `RustPointer`.
`SGPFile` is excluded because it feels unsafe to put `RustPointer` there.
=> Add RustPointer

.github/workflows/coverity.yml, .travis.yml
According to https://scan.coverity.com/faq#frequency we have minimum 1 build a day, so we can trigger a coverity build similarily to nightlies every day. Now we can think about how to make the results of the scan more visible to developers (us).
~Ref: https://scan.coverity.com/projects/ja2-stracciatella~
Ref: https://scan.coverity.com/projects/ja2-stracciatella-ja2-stracciatella
=> Trigger daily coverity builds as well

CMakeLists.txt, rust/stracciatella_c_api/src/c/logger.rs, src/sgp/Logger.h
An absolute path is assumed but it might be relative.
Coverity was marking it as "Illegal address computation (OVERRUN)" because it was relative there.
Introduced in: #844
=> Remove SOURCE_PATH_SIZE

src/game/Tactical/Points.cc
Coverity detected "Negative array index read (NEGATIVE_RETURNS)" in `GetAPsToAutoReload` when we can't find ammo for the first gun and check if that ammo is compatible with the second gun:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/36148be0d0d9196050c12799c884af9eda7cb256/src/game/Tactical/Points.cc#L1463
`AutoReload` only reloads the second gun if the first one reloads so here we enforce the same behavior, avoiding the check.
=> Make GetAPsToAutoReload agree with AutoReload

src/game/Strategic/Creature_Spreading.cc
Coverity detected "Resource leak (RESOURCE_LEAK)" in `NewDirective`.
The memory of variable `curr` was being leaked when we can't find the underground sector node.
=> Fix memory leak in NewDirective

src/game/Strategic/Map_Screen_Interface_Map.cc
Coverity complained it was a copy-paste error and I agree.
The code that enables zoom is commented out since the original version.
Maybe they were hunting down this hard to spot bug?
=> Fix copy-paste error in DrawMap with zoom enabled.

src/game/Laptop/Mercs.cc
This is equivalent code.
Coverity complained that the `if` test was always true.
`StartSpeckTalking` already checks for the tested values and sets `gusMercVideoSpeckSpeech` to the value we want if they pass.
To make it equivalent we just set `gusMercVideoSpeckSpeech` on failure.
=> Remove constant expression in HandleTalkingSpeck

src/game/Strategic/Map_Screen_Interface_Map.cc
Coverity detected this dead code.
The `else if` 2x before is exactly the same.
~Maybe they wanted to move the code but copy-pasted instead?~
It caused the south-east-north U-turn arrow to show up when it should be
hidden.
Fixed by inverting the signs of the deltas.
Moved to keep simetry of the surrounding code.
=> Fix south-east-north U-turn in TraceCharAnimatedRoute and TracePathRoute

rust/Cargo.lock, rust/stracciatella/Cargo.toml, rust/stracciatella/src/config/cli.rs, rust/stracciatella/src/fs.rs, rust/stracciatella/src/stracciatella.rs, rust/stracciatella_c_api/src/c/misc.rs
On windows the launcher couldn't find the path to `game.json` because the canonicalized base path was in UNC form and the relative part had a `/` path separator.
With a normal base path it works as expected, so crate [dunce](https://crates.io/crates/dunce) is being used to turn UNC paths into normal paths when possible.
Referencce: https://github.com/rust-lang/rust/issues/65397
=> Convert canonicalized UNC paths to normal paths when possible

src/game/Utils/STIConvert.cc
Coverity detected "Resource leak (RESOURCE_LEAK)" in `WriteSTIFile`.
The memory of variable `pSubImageBuffer` was being leaked.
The memory is allocated in `ConvertToETRLE`. To avoid handling exceptions, the caller becomes responsible for the allocated memory.
=> Fix memory leak in WriteSTIFile

src/game/Utils/STIConvert.cc
Coverity detect the copy-paste mistake I made in #881.
I'm glad coverity is working again. :)
=> Fix copy-paste error in WriteSTIFile

src/game/Laptop/AIMHistory.cc
Coverity detect an out of bounds access caused by this test.
The page number could be set to NUM_AIM_HISTORY_PAGES, which is invalid.
=> Fix out of bounds access from BtnHistoryMenuButtonCallback

src/game/Editor/EditScreen.cc
Coverity detected a missing break in switch.
Looking at the previous switch case, it should not fall through.
=> Fix missing break in HandleKeyboardShortcuts

src/game/Editor/NewSmooth.cc, src/game/TacticalAI/Movement.cc, src/game/TileEngine/Lighting.cc, src/game/TileEngine/Render_Fun.cc
Coverity detected an access out of bounds in at least one of these.
NOWHERE must not change to keep compatibility with old saves, so instead all checks with >= NOWHERE and < NOWHERE are changed.
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/b430600fac6648445be19d524551a43d5472b9be/src/game/TileEngine/Isometric_Utils.h#L13
=> Fix checks for validity of the grid number.

src/game/Tactical/Turn_Based_Input.cc
Coverity detected uninitialized data in Object.
DeleteObj is already being used to initialize, so the same is done here.
=> Fix uninitialized data in GrenadeTest1 and GrenadeTest2

src/game/TileEngine/Smell.cc
These macros were not putting parenthesis in all their argument uses.
BLOOD_DELAY_TIME was only interacting with "1" from SET_BLOOD_DELAY_TIME.
As long as Random() does not missbehave, there is no real bug.
=> Silence warning caused by SET_BLOOD_DELAY_TIME

src/game/TileEngine/Structure.cc
When grid no is NOWHERE there was at least one out-of-bounds read.
After the header, the code assumes it is valid so just return.
The print with the generic structure number had an extra argument.
=> Fix coverity bugs in DebugStructurePage1

src/game/Laptop/Insurance_Contract.cc
Coverity complained about an out-of-bounds read when `ubPayoutID` equals `ubNumberLifeInsurancePayout`.
New space is reserved based on `ubNumberLifeInsurancePayoutUsed`.
There was no real bug if `ubNumberLifeInsurancePayoutUsed` was maintained properly.
=> Silence coverity issue in AddLifeInsurancePayout

src/game/Tactical/Keys.cc, src/game/TileEngine/Physics.cc
Coverity detected the use of an uninitialized value of `usTileIndex`.
On the other calls the data is initialized with memset, so do the same here.
=> Fix use of uninitialized value in CreateAnimationTile

src/game/Editor/EditScreen.cc, src/game/Editor/Edit_Sys.cc
Coverity detected out of bounds accesses.
The map index is the grid number, so it should be restricted to GRIDSIZE.
Maybe at some point the map could have 0x8000 grid cells, but not now.
=> Fix map index range checks in the editor.

src/game/Tactical/Rotting_Corpses.cc
Coverity detected a null pointer dereference in GetCorpseAtGridNo when pBaseStructure is null.
=> Fix null pointer dereference in GetCorpseAtGridNo

src/game/Laptop/Mercs.cc
Coverity detected logically dead code when ubCnt is BUBBA.
The BUBBA switch branch was never executed because MERC_LAST_MERC is equal to BUBBA.
=> Fix Speck's reaction to Bubba's death

src/game/Laptop/IMP_Attribute_Selection.cc
Coverity detected a null pointer dereference when val is not set in the switch.
=> Fix null pointer dereference in IncrementStat and DecrementStat.

src/game/Tactical/SkillCheck.cc
Coverity detect a negative array read when bSlot is NO_SLOT.
=> Fix negative array read in SkillCheck

src/game/Tactical/OppList.cc, src/game/Tactical/Overhead.cc, src/game/Tactical/Overhead_Types.h, src/game/Tactical/TeamTurns.cc
Coverity detected at least one out of bounds read in ManSeesMan when the opponent id is 155.
SOLDIERTYPE::bOppList has length 148 and is part of the AI system.
Ids 148 to 155 belonged to the PLAYER_PLAN team, used in the planning mode.
The planning mode was removed by tron because it was unused (not bound to a hotkey).
These soldiers were temporary and only existed during the player turn, they were not meant to have AI interaction.
This commit fixes the range checks that are related to arrays with length 148, there might be more.
Closes #902
=> Fix out of bounds reads/writes

src/game/Tactical/ShopKeeper_Interface.cc
Coverity detected uninitialized data in BeginSkiItemPointer.
When ubSource is PLAYERS_INVENTORY, Rect might not be initialized.
When the mouse is being restricted, that uninitialized data is used.
Here we restrict the mouse only when Rect is initialized.
=> Fix uninitialized data in BeginSkiItemPointer

src/sgp/Smack_Stub.cc
Coverity detected an unintended integer division in SmackDoFrame.
"FramesPerSecond" is actually the number of microseconds per frame.
Therefore "framerate" is the number of milliseconds per frame.
"framerate" is double, so it should not be truncated to integer values.
=> Fix unintended integer division in SmackDoFrame.

src/sgp/PCX.cc
Coverity detected an unintended sign extension in BlitPcxToBuffer.
In the w * h operation, w and h are first promoted to int, then multiplied, then sign-extended to size_t.
When w * h is greater than 0x7FFFFFFF, the int will be negative.
When size_t is 64 bits and the int is negative, the upper bits will be 1. (bigger than UINT32_MAX)
UINT16_MAX * UINT16_MAX = 0xFFFE0001, so a bigger value is a wrong result.
=> Fix unintended sign extension in BlitPcxToBuffer.

src/game/Laptop/BobbyRGuns.cc
Coverity detected an uninitialized scalar variable in DisplayItemInfo.
I'm not sure about this one, it seems to be about sending the uninitialized array items to CreateMouseRegionForBigImage when ubCount is 0.
~If the interpretation is correct, then not calling the function when ubCount is 0 is enough to fix it.~
Fixed by initializing the items array to 0.
=> Fix uninitialized scalar variable in DisplayItemInfo

src/game/TacticalAI/CreatureDecideAction.cc
Coverity detected a possible out of bounds access in CreatureCall.
It is not clear if it actually happens in the current code.
SoldierTriesToContinueAlongPath limits the value of usActionData to 0-25599.
CreatureCall assumes usActionData is 0-4.
=> Fix possible out of bounds access in CreatureCall

src/game/TileEngine/Explosion_Control.cc
Coverity detected a resource leak in ExplosiveDamageGridNo when ppTile goes out of scope.
I don't really understand this code, but turning ppTile into a vector is enough to fix it.
The vector will be freed when it goes out of scope.
=> Fix resource leak in ExplosiveDamageGridNo

src/game/Tactical/Soldier_Create.cc
~Coverity detected an unused value of hair in ChooseHairColor~
~This last line is probably leftover code.~
----
Coverity detected unused values of hair in ChooseHairColor
This last line is overriding them and is probably leftover code.
=> Fix unused values in ChooseHairColor 

src/game/Strategic/Assignments.cc
Coverity detected unreachable code in SquadMenuBtnCallback.
The declaration of buf was unreachable.
I'm surprised this is allowed, it might not be portable...
Fixed by moving buf and DoScreenIndependantMessageBox out of the switch.
An "evil" goto label is also removed.
=> Fix unreachable code in SquadMenuBtnCallback

src/game/Editor/Edit_Sys.cc
Coverity detected an out of bounds access in PasteRoomNumber when iMapIndex too big.
=> Fix out of bounds access in PasteRoomNumber

src/externalized/WeaponModels.cc
Coverity detected a dereference after null check in WeaponModel::deserialize.
An error message is logged when wep is null, but a return was missing.
=> Fix dereference after null check in WeaponModel::deserialize

src/externalized/WeaponModels.cc
Coverity detected uninitialized members in the WeaponModel constructor.
=> Fix uninitialized members in WeaponModel constructor

src/game/TacticalAI/NPC.cc
The purpose of this log message in uncertain, so just remove it.
It was reading out of bounds when pNPCQuoteInfo->ubQuest includes QUEST_DONE_NUM or QUEST_NOT_STARTED_NUM.
The log only accepts valid utf8, so it would crash with the garbade data.
Fixes #927
=> Fix crash from NPCConsiderQuote

src/sgp/PCX.cc
Coverity detected an unintended sign extension in LoadPCXFileToImage.
It would try to allocate more memory than necessary.
=> Fix unintended sign extension in LoadPCXFileToImage

rust/stracciatella/src/bin_resource_pack.rs, rust/stracciatella/src/config/ja2_json.rs, rust/stracciatella/src/config/stracciatella_home.rs, rust/stracciatella/src/fs.rs, rust/stracciatella/src/guess.rs, rust/stracciatella_c_api/src/c/misc.rs, src/launcher/Launcher.cc
This should extract a common functionality used to find a directory case insensitively. Basically now all user editable paths should be canonicalized and made case insensitive with this commit. It also seems to fix one of the issues in #886 where the launcher mishandles spaces.
=> Add function to resolve caseless path to caseful variant

src/game/TileEngine/WorldDef.cc
Non-russian maps can be loaded when playing the russian version of the game.
Russian maps are loaded correctly when playing a non-russian version of the game.
Newer (unknown) versions are not loaded.
The map version is checked against the minor version.
A missmatch implies a bad load.
Warn when an unexpected version is loaded.
Include the description of the exception when setting the error.
Superseeds #706
=> Allow known map versions

src/game/Tactical/Interface_Items.cc
The return value changed when UTF8String was replaced with ST::string.
Probably forgotten because the file didn't reference UTF8String directly.
Bug introduced in #915
The item calibre name would show up as garbage.
=> Fix remaining calls to CalibreModel::getName()

src/game/MessageBoxScreen.cc
It was complaining about converting int to wchar_t.
`'1' + i` promotes to int and wchar_t is compiler dependent.
Reference #857
=> Fix warning C4838

src/game/Utils/Text_Input.cc
Was complaining about comparing bool with BOOLEAN in SetEditingStatus.
Now it's comparing bool with bool.
Reference #857
=> Fix warning C4805

src/game/Editor/EditScreen.cc
`requestGameExit` queues a `SDL_QUIT` event, which later calls `deinitGameAndExit`.
`EditModeShutdown` asks if we want to quit the editor, but the `SDL_QUIT` event won't be stopped.
It is clear that a fallthrough was not intended.
Reference #857
=> Fix unintended fallthrough with ACTION_QUIT_GAME

src/game/Editor/EditScreen.cc
Using enter/escape to accept/reject a dialog window is common practice.
The fallthrough is probably intended.
Reference #857
=> Silence fallthrough warning in WaitForSelectionWindowResponse

src/game/Editor/EditScreen.cc
From the comment of CheckForFences and the structure of the function, the fallthroughs are intended.
Reference #857
=> Silence fallthrough warnings in DoIRenderASpecialMouseCursor

src/game/Strategic/Assignments.cc
Instead of moving the comment, the fallthrough code was copied.
Reference #857
=> Silence fallthrough warning in SetAssignmentForList

src/game/Editor/Sector_Summary.cc
After testing, it's probably an unintended fallthrough.
When you start the editor it mentions quitting with ESC or ALT+x.
Before loading a map, ESC quits the game (expected).
After loading a map, ESC had the same effect as ENTER or clicking the Okay button.
Now it ignores ESC after a map is loaded.
Reference #857
=> Fix unintended fallthrough in HandleSummaryInput

src/game/Tactical/Faces.cc
Eye frames are 0-4, frame 5 has a mouth.
Dying checks were commented out so it's probably handled somewhere else.
Fixes the fallthrough warning of frame 7.
Reference #857
=> Clean up NewEye

CMakeLists.txt
I tried to fix "enumeral and non-enumeral type in conditional expression", but I coun't find of think of a rationale for the warning.
Are they trying to say "stop using C-style enums"?
That's unlikely to happen until there is an auto-numering alternative.
There are three ways to handle the warning:
1) cast enum value to an integer type
2) convert enum to constants
3) remove option -Wextra
The -Wextra warnings seem to be subjective or a matter of taste.
It's a waste of time to worry about them when we don't even have a preferred style.
Anything that actually matters should be covered by coverity, so I'm removing the options related to -Wextra.
Reference #857
=> Remove extra warnings

src/game/Laptop/Laptop.cc
Rename the rectangles, their names were reversed.
Reference  #857
=> Fix variable set but not used warning in LeaveLapTopScreen

src/game/Strategic/Game_Clock.cc
It is only used when DEBUG_GAME_CLOCK is defined.
Reference #857
=> Fix variable set but not used warning in UpdateClock

src/game/Tactical/Interface_Items.cc
I don't understand the implications of the other commented code, so I'm commenting the rest of the code instead of deleting.
Reference #857
=> Fix variable set but not used in InternalHandleCompatibleAmmoUI

src/game/Tactical/LOS.cc
The other commented code seems functional, so I'm commenting instead of deleting.
Reference #857
=> Fix variable set but not used in CheckForCollision

src/game/Tactical/Soldier_Control.cc
There is commented code that uses it, so comment instead of delete.
Reference #857
=> Fix variable set but not used in EVENT_InternalGetNewSoldierPath

src/game/TileEngine/Environment.cc
While playing vanilla I recall the laptop behaved differently during a rainstorm.
Is this related? Just in case, I'm commenting instead of deleting.
Reference #857
=> Fix variable set but not used in ForecastDayEvents

src/game/TacticalAI/NPC.cc
`ubNPC` is 200 here, and this code is clearly meant to process `i`.
=> Fix wrong npc id used in RefreshNPCScriptRecord

src/game/Tactical/DisplayCover.cc, src/game/Tactical/Squads.cc, src/game/Utils/Cinematics.cc, src/launcher/Launcher.cc, src/sgp/SGP.cc
`auto i = 0` always picks `int`, even though it should be another type.
auto resolution is dumb... it only considers the first statement, not the uses of the variable.
To discourage further uses of auto, I'm changing everything except iterators to explicit types.
Fixes some sign-compare warnings
Reference #857
=> Avoid the use of auto

src/game/Laptop/Finances.cc
For negative iCurrentPage values the next page and last page buttons will show up now.
Reference #857
=> Fix sign-compare warnings in Finances.cc

src/game/Strategic/Strategic_Pathing.cc
Strategic pathing (easily visible when trying to use the helicopter; the behavior isn't perfectly consistent, but generally it won't take any paths longer than two sectors) has apparently been broken since 0e013cb67be05e598a3de1fbb245b6e5cff7b49a, which switched from byte assignment with memset to item assignment with std::fill, but keeping the same value (so each element is 0x000000FF instead of 0xFFFFFFFF). This should restore the correct behavior.
=> Unbreak strategic pathing

src/sgp/SGP.cc
In the comparison msPerGameCycle became unsigned, so a negative number would be bigger than INT32_MAX.
Fixes a sign-compare warning.
Reference #857
=> Fix delay when msPerGameCycle is negative

src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Tactical/Vehicles.cc
It is equivalent to TRAVERSE_TIME_IMPOSSIBLE, so it's already handled.
Fixes sign-compare warnings.
Reference #857
=> Remove uiTraverseTime -1

src/game/Tactical/Vehicles.h
All the related variables seem to be INT32, so match that.
Reference #857
=> Fix sign-compare warnings in Vehicles.cc

src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h
=> Fix sign-compare warning in DefaultContentManager::getNewString

src/game/Strategic/Creature_Spreading.cc
I don't know why, but the warning only happened in the double sum...
Since I don't understand, I'm converting the code instead of casting.
Reference #857
=> Fix sign-compare warning in AddCreaturesToBattle

src/game/MainMenuScreen.cc, src/game/Utils/Cinematics.cc, src/sgp/SGP.cc, src/sgp/SoundMan.cc, src/sgp/SoundMan.h
SDL 2.0.6 crashes in SDL_ResampleAudio and does not request enough memory for SDL_Convert_U8_to_F32_SSE2 (corrupts memory).
To avoid problems we use a custom resampler (linear interpolation) and allocate more buffer memory.
The name of the smacker audio streams was useless. Now it has the channel index and the filename.
---
Reference #608 #615
Tested with a manual compile of SDL 2.0.6, no more crashes. ^^
=> Fix sound in SDL 2.0.6

src/sgp/SoundMan.cc
SDL_ConvertAudio says it should be the size of the source data, not the size of the buffer.
Wrong value introduced in #1005
=> Fix wrong value in cvt.len

src/game/Tactical/Points.cc
The FPE is a divide by zero while calculating iHitRate.
MinAPsToThrow warned and returned 0 on unexpected input, now it just warns.
It is unclear how a launcher should be trully handled:
1) GLAUNCHER has item class IC_LAUNCHER.
2) MinAPsToAttack calls MinAPsToShootOrStab for item class IC_LAUNCHER.
3) CalcBestThrow calls MinAPsToThrow and has the comment "NB grenade launcher is NOT a direct fire weapon!"
Fixes  #1006
=> Quick fix for FPE in CalcBestThrow when MinAPsToThrow returns 0

src/game/Strategic/Strategic_Town_Loyalty.cc, src/game/Strategic/Strategic_Town_Loyalty.h
This is not an issue with vanilla, but for future map mods.
Before this change,  `g_town_sectors` in Strategic_Town_Loyalty [limits to 40](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/36708ba01af1564cb6fd4e13cbc58533cd8d0e0d/src/game/Strategic/Strategic_Town_Loyalty.cc#L78). If the world has more than 39 town sectors, `BuildListOfTownSectors` will [iterate past the end of array](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/36708ba01af1564cb6fd4e13cbc58533cd8d0e0d/src/game/Strategic/Strategic_Town_Loyalty.cc#L692), causing a "stack-based buffer overrun"  exception.
This change should bring no side-effects other than wasting a few more CPU cycles [iterating on empty elements](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/36708ba01af1564cb6fd4e13cbc …
=> Allowing more Town Sectors

src/game/Strategic/Strategic_Town_Loyalty.cc
Fixing an embarrassing error in #1016 
The struct is:
```c++
struct TownSectorInfo
{
UINT8 town;
UINT8 sector;
};
```
=> Fixing error in TownSectorInfo construction

src/externalized/DefaultContentManager.cc
Unpacked files inside `data/` used to work. Now it doesn't because the file exist check is not using the full path.
The variable `path`  is unused otherwise, so I believe this (using `path`) was the intended behaviour. See c29759a3
=> Fix opening of unpacked files in data directory

rust/stracciatella/src/config/ja2_json.rs
fixes migration scenario when you still have data_dir.
edit: forgot to add [ci skip], so killed them manually.
=> ja2_json.rs: fixed replacement var error message suggestion

assets/externalized/strategic-map-towns.json, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/strategic/CMakeLists.txt, src/externalized/strategic/TownModel.cc, src/externalized/strategic/TownModel.h, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/StrategicMap.cc, src/game/Strategic/Town_Militia.cc
Externalization of Town and Town Sector data, in a similar manner as #1018. 
See #665 and #1011.
- Externalizing basic town info. See assets/externalized/strategic-map-towns.json for the schema
- Adding TownModel class, which can be retrieved by `townId`
- Replacing the hard-coded tables of `InitializeStrategicMapSectorTownNames`, `sBaseSectorList`, `pTownPoints` and `MilitiaTrainingAllowedInTown`
* Town names - they are defined in translation string files
* Is Town hidden - codebase has very specific logic for Tixa and Orta. It will require a lot of code change to generalize the logic
* Base sector - it is now calculated at init time
This PR conflicts with #1018. I will re-base when it is merged to master.
=> Externalizing Town and Town Sectors data

src/game/Tactical/Keys.h
See the below screenshots. One on top is 0.16.1, the other is HEAD.
This is because LOCK.ubEditorName has type of UINT8[]. Previously it could be interpreted as if it is `char[]`, but `ST::format` prints it as `true`.
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/b22697bf9c53239ddf6d1c35e9ed4b195c0db6d7/src/game/Editor/EditorItems.cc#L322
=> Fixing Key Name display in Map Editor

rust/stracciatella/src/config/cli.rs, rust/stracciatella/src/stracciatella.rs
fixes the the useless -h error antipattern:
> $ build/ja2 -h
> Unrecognized option: 'h'
> $
=> cli: print usage string when invalid arguments are passed

src/game/Tactical/PathAI.cc
> src/game/Tactical/PathAI.cc:1860:34: warning: result of comparison of constant 256 with expression of type 'UINT8' (aka 'unsigned char') is always true [-Wtautological-constant-out-of-range-compare]
>                         for (ubCnt=0; z != 0 && ubCnt < lengthof(guiPathingData); ubCnt++)
Prevents potential overflow.
=> PathAI: fixed tautology warning

rust/stracciatella_c_api/build.rs
The header is removed when you do `make clean`.
Fixes #1039
=> Rerun build.rs when the header changes

src/game/Tactical/Items.cc, src/game/Tactical/World_Items.cc
This is intended to improve map mod support (https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1011#issuecomment-609579529). 
Some items in Wildfire re-use item IDs, that maps to internal items in Vanilla. (e.g. LAW rocket is item#160 which is "Creature Gas" in Vanilla). To better support WF maps, we skip those items, as such items just do not exists in Vanilla.
An assumption here is: if an item is marked `ITEM_NOT_EDITOR`, it is not supposed to placed in the map file as a world item. 
- Adding the `ITEM_NOT_EDITOR` flag to the "creature gas" internal items. Before this PR they do show up in the Map Editor, but they should not.
- Add a check, so when loading from map file, `ITEM_NOT_EDITOR` items are not placed. A warning is logged, because it means the map is not used as it …
=> Skip Invalid Items on Maps

src/game/Strategic/Strategic_Mines.cc
Detected by coverity.
~A zero should never happen but `GetAvailableWorkForceForMineForEnemy` has this check, so we match it.~
=> Fix divide by zero in GetAvailableWorkForceForMineForPlayer

rust/stracciatella/src/fs.rs, rust/stracciatella/src/stracciatella.rs
canonicalize also converts big long names to short names.
=> Fix test parse_args_should_return_the_correct_canonical_game_dir_on_windows

assets/externalized/strategic-map-npc-placements.json, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/strategic/CMakeLists.txt, src/externalized/strategic/NpcPlacementModel.cc, src/externalized/strategic/NpcPlacementModel.h, src/game/Strategic/Campaign_Types.h, src/game/Strategic/Strategic_Event_Handler.cc
Quick PR to get NPC placements to work with map mod, but also a question to ask. I will further test and polish, if we agree on the approach.
See also #665 and #1011.
- Some NPCs (e.g. DEVIN, CARMEN, HAMOUS (and his truck)) are randomly placed in several possible sectors
- Externalizing the random placements to JSON
The Strategic Event handler is very specific to JA2 storyline and campaign. There is not a lot of flexibility even by externalizing the sector list. Not saying we have to follow, but 1.13 allows overriding by Lua script.
Should we also introduce a scripting engine here?
=> Externalizing random NPC placements

src/game/TileEngine/Tile_Cache.cc, src/game/TileEngine/Tile_Cache.h
Detected by coverity.
zName had fixed size and filename unknown size.
=> Fix buffer overflow in GetCachedTile

src/game/Strategic/Map_Screen_Interface_Map.cc
=> Fix divide by zero in BlitMineText

src/externalized/strategic/MovementCostsModel.cc, src/game/Editor/Cursor_Modes.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Strategic_Movement.cc
New defects introduced in #1021.  Detected by Coverity.
This PR removes the meaningless assertions that compares unsigned int to 0.
=> Remove meaningless Assertions on unsigned int

src/game/Strategic/Map_Screen_Interface_Map.cc
Mine income rates going beyond 100% in strategic map. The numerator is a daily rate, but the denominator is a periodic rate. 
Both should have been daily rate. Ref: https://github.com/ja2-stracciatella/ja2-stracciatella/commit/a3df1905455a29f21dbbca2647a0688a40c23e3d 
@flaviojs
=> Fix Mine Text display

assets/externalized/strategic-map-sam-sites.json, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/strategic/CMakeLists.txt, src/externalized/strategic/SamSiteModel.cc, src/externalized/strategic/SamSiteModel.h, src/game/Strategic/Map_Screen_Helicopter.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Meanwhile.cc, src/game/Strategic/StrategicMap.cc, src/game/Strategic/StrategicMap.h, src/game/TileEngine/Explosion_Control.cc
This PR externalizes SAM site locations. The goal is to allow map mods to override SAM site locations. Though the SAM site list is now a `std::vector`, adding or removing SAM sites are not allowed.
See also #1011 and #665.
- `pSamList[]`:  Now dynamically defined by JSON
- `pSamGridNoAList[]`:  This is the "anchor" tile of the SAM computer terminal. This is always the lower tile (the one with higher gridNo)
- `pSamGridNoBList[]`:  The other tile of the SAM computer
- `gbSAMGraphicList[]`:  It is now derived from SAM gridNos
- `fSamSiteFound[]`  Not changing for save compatibility
Restrictions enforced in `SamSiteModel.cc`.
- Must define exactly 4 SAM sites
- Breaks Saves, if more than 4 SAM sites
- Breaks hard-coded references from Skyrider and Meanwhile dialogues, if fewer than 4 SAMs
- …
=> Externalizing SAM site locations

src/game/Tactical/PathAI.cc
Both editor and game crashes when trying to load the Wildfire version of Estoni I6.dat. The exception was array out-of-bounds when the algorithm attempts to access gridNo beyond `WORLD_MAX`(25600)
The error is when the game tries to add a soldier to the map. The soldier is placed very close to bottom-left corner. In this case the soldier is at 24719, which is 5 tiles away from edge.
The algorithm then tries to find a "sweet spot" using FindBestPath without a destination. I believe the algorithm is doing a search a few tiles around the soldier placement tile.
There is a out-of-bounds check in code, but it never took effect. The check happens after the gridNo is used. Though I haven't tried, I suspect it to be reproducible by placing a soldier at the far bottom-left. 
This is an independent …
=> Fixing an Out-of-Bounds check in PathAI

src/game/Tactical/Keys.cc
Loading save for Wildfire sector G8 causes a crash. The crash is caused by dereferencing a NULL point in SynchronizeDoorStatusToStructureData, which is part of load game.
When a game is loaded, it tries to synchronize the door states. If the state mis-matches, it will "swap" the structure with its "partner". I suppose that means switching between the closed and opened states of a door. 
In this case, the room is very packed and the door is placed such that the opened state of the door collides with a wall. Then SwapStructureForPartner returns NULL.
EDIT: The fix now takes reference from 4ee4f52838b and also 3d5ac56adfebf.
Adding a NULL check with a WARN log (like before 3d5ac56adfebf). Then using the GridNo before the Swap (like before 4ee4f52838b), as the swap can return NULL.
The root …
=> Adding null check in SynchronizeDoorStatusToStructureData

src/game/TileEngine/Buildings.cc
The game is stuck in a deadloop in [GenerateBuilding in TileEngine/Buildings.cc](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/fea6115a26906ca08b461489a5eef6099f46f2e6/src/game/TileEngine/Buildings.cc#L42), when loading a Wildfire map (G9.dat). I cannot exactly tell if it is corrupted data or it is a limitation of vanilla JA2.
I knew nothing about the building function before this. Here is my take to explain it: 
When a map is loaded from .dat, the game tries to generate in-memory representation of buildings. It is mainly for rooftop-climbing. The algorithm is to: 
- Scan through all map tiles, starting from top-left
- Generate a building struct when we find a building/room
- Then continue to walk, clockwise, the edges of building until we go back to the starting grid
The …
=> Breaking possible Dead-loop in GenerateBuilding

assets/externalized/strategic-map-towns.json
My bad. The town data I committed in #1020 has an error. Now the town sectors are exactly the same as 0.16.1.
=> Fixing an error with Town data

src/game/Strategic/Strategic_Merc_Handler.cc
Crashed with GetProfile(NO_PROFILE).
Fixes #1068
=> Fix crash when a non-hostile unnamed civilian bleeds out

assets/externalized/strategic-map-underground-sectors.json, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/strategic/CMakeLists.txt, src/externalized/strategic/UndergroundSectorModel.cc, src/externalized/strategic/UndergroundSectorModel.h, src/game/Strategic/Campaign_Init.cc
Visiting an underground sector that has a map .DAT but not corresponding `UNDERGROUND_SECTORINFO`  crashes the game.
See also #1011 and #665.
- Extracted data from Campaign_Init..cc:BuildUndergroundSectorInfoList to JSON
- Generalized the per-DIFLEVEL numbers of enemies as a "base num + random" formula
- Only changed Campaign Init - in-memory linked-list and Save/Load are not touched
- Validation to protect from crash due to missing data
=> Externalizing Underground Sector Info

src/externalized/DefaultContentManager.cc
Missed this when I pulled changes into #1061.
With this commit now we actually load Fact params from JSON.
=> Load Fact params from JSON

src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h
Closes #1072.
- `delete` JSON documents after use
- Properly `delete` pointers in destructor
- Sorted class members
- `static_cast<>` to silence a warning
=> Clean up DefaultContentManager

assets/externalized/strategic-map-underground-sectors.json
My bad again. Somehow I got some typo in the JSON. This does not show up in tests because that field is optional.
This affects the drawing of that particular underground sector on strategic map.
=> Fixing JSON error

src/game/Strategic/Strategic_Mines.cc
This has to be a typo, as this only initializes the value of the first element, and leaves the rest uninitialized
=> Fixing a typo in InitializeMines

.travis.yml, CMakeLists.txt, COMPILATION.md
debians splits the lib out, while the rest is just documentation. Since we use a system fltk on travis, the bundled one isn't used, so we have to deal with their split libraries.
=> fix debian fltk omission

src/game/Tactical/Soldier_Ani.cc
After merc does steal action on another merc, animation is started and busy count is increased but is never decreased, so ui gets locked for 25 seconds until the lock timeout expires.
This fixes that so as soon as animation finishes attack busy count get decreased, and when it reaches zero UI leaves wait state as it should.
=> Fixed delay after stealing items from another merc.

.travis.yml
In recent nightly builds, the linux/mingw64-cross artifacts has zero bytes (https://github.com/ja2-stracciatella/ja2-stracciatella/issues/873#issuecomment-638665861)
The larger artifacts from nightly builds (linux and mingw64-cross) are 30+MB and readily take 120+s to upload. It may need more time if networks are busy.
=> Allow more time for nightly artifact upload

assets/externalized/strategic-mines.json, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/JsonObject.h, src/externalized/strategic/CMakeLists.txt, src/externalized/strategic/MineModel.cc, src/externalized/strategic/MineModel.h, src/game/Strategic/Creature_Spreading.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/StrategicMap.cc, src/game/Strategic/Strategic_Mines.cc, src/game/Strategic/Strategic_Mines.h
For #665, so we can customize mines, incomes, etc. Head miners are not covered in this PR.
- Mine sectors - surface and underground (`gMineLocation`, GetIdOfMineForSector)
- Mine income   (`guiMinimumMineProduction`)
- Town ID (`gMineLocation`)
- Other misc attributes such as mineral type (`gubMineTypes`), and some special attributes mentioned below
1. `mineId == MINE_SAN_MONA` => `mine.isAbandoned`
2. `mineId == MINE_ALMA` => `mine.noDepletion` / `mine.headMinerAssigned`
Alma mine always has Matt as head miner, and is never selected for depletion, due to quests
2. `ubDepletedMineIndex == MINE_DRASSEN`: `mine.delayDepletion`
If Drassen mine is chosen for depletion, we will delay the depletion. I believe this is for early-game game balance
The save file does not carry the number of mines …
=> Externalizing mines

src/game/Strategic/StrategicMap.cc
Bug introduced in #1098. Head miner all assigned to the same (wrong) town ID. 
This affects nightly and master since #1098.
=> Fixing head miner assignment

assets/externalized/strategic-map-creature-lairs.json, assets/externalized/strategic-mines.json, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/strategic/CMakeLists.txt, src/externalized/strategic/CreatureLairModel.cc, src/externalized/strategic/CreatureLairModel.h, src/externalized/strategic/MineModel.cc, src/externalized/strategic/MineModel.h, src/externalized/strategic/UndergroundSectorModel.h, src/game/Strategic/Creature_Spreading.cc, src/game/Strategic/Creature_Spreading.h
Fixes #1087.
See also #1095 and #665.
- Extracted JSON data from Creature_Spreading.cc (`strategic-map-creature-lairs.json`)
- Removed `isInfestible` from Mine. It is redundant. The existence of a CreatureLairModel means the same.
_All data come from Creature_Spreading.cc_
- InitLair`${TOWN}` => `"sectors"`
- InitCreatureQuest: `curr->uiFlags |= SF_PENDING_ALTERNATE_MAP;` => `"entranceSector"`
- ChooseTownSectorToAttack => `"attackSectors"`
- MineClearOfMonsters => MineModel::`mineSectors` (#1098)
- GetWarpOutOfMineCodes => `"warpExit"`
- Hard-coded Tixa dungeon references (in StrategicMap.cc, etc)
=> Externalizing Creature Lairs and Spreading

changes.md
Was looking through old changes today. 
Did a regex substitution, from `^\(r(\d\d)` to  `\- \(r(\1)`, after line 253, so old logs are formatted nicely in Markdown.
=> Tidy up old changelog

src/game/TileEngine/Structure.cc
Fixes #1107 and #722. And probably all helicopter crash issues.
This PR attempts to fix JSD data issues. For detailed explanation refer to the issue and the comments in code. 
The normalization is called after loading structure from file. It does nothing on most structures. It happens only when the structure has no tile of (0, 0) rel position. The function will then shift all tiles so that one of them is (0, 0).
Briefly tested different sectors, so far I only find the normalization taking effect in I6 (Estoni), B13 (Drassen airport) and C13 (dead airstrip). All of them has helicopter structures.
The landed copter looks fine to me in both B13 and I6 after this fix.
=> Normalize structure tiles

src/game/Editor/Item_Statistics.cc
In master/nightly, the textboxes in Ammo GUI seem to be "overflowing" to the next fields, so that first value is "1" (correct), second value is "10" (expected: 0), third value is "10100" (expected: 100).
Ref: https://github.com/ja2-stracciatella/ja2-stracciatella/commit/ebbe2b9bd1fd7f09f6608a6912c00af67194f9f3#diff-9b758624bbb8452e17a64953641ff01dL715-L720
=> Fixing the Ammo GUI in Editor

assets/externalized/strings/shipping-destinations-fr.json, assets/externalized/strings/shipping-destinations-ger.json, assets/externalized/strings/shipping-destinations-it.json, assets/externalized/strings/shipping-destinations-pl.json, assets/externalized/strings/shipping-destinations-rus.json
[ERROR] externalized/DefaultContentManager.cc: Failed to parse 'strings/shipping-destinations-ger.json'
=> Translations: Fix json syntax in shipping destinations

src/externalized/DefaultContentManagerUT.cc, src/externalized/DefaultContentManagerUT.h, src/externalized/DefaultContentManager_unittests.cc, src/externalized/VanillaWeapons_unittests.cc, src/sgp/FileMan.cc, src/sgp/FileMan.h
To prevent JSON syntax errors. Some files are not always processed in loadGameData(), in particular the localization files.
No other JSON problems found other than those already addressed in [#1115](https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1115/files?w=1).
=> Adding unit test to parse every JSON in externalized dir

.github/scripts/ci-build.sh, .github/scripts/ci-publish.sh, .github/scripts/ci-setup.sh, .github/workflows/github-ci.yml, CMakeLists.txt
Attempt to improve on #1101 and #1102. Only covers GitHub CI builds.
- Split the `ci-build.sh` script into 3 steps - setup, build and publish
- Add `ccache` to the CI build process (https://ccache.dev)
- CMake will make use of it if installed
- Cache  C++ objects with `ccache` (`~/.ccache`)
- Prefers the last build from same Git branch, falls back to last master build
- Cache Rust deps and output
- Cache `~/.cargo`, `~/.rustup` and `$PROJECT_DIR/dependencies/lib-stracciatella/target`
- Assuming Rust code not changed often, cache is used only if the entire `rust/` directory is untouched
- Add concurrency in make (`-j 4`)
- `rustup` with `minimal` [profile](https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html#profiles); install `rustfmt` and `clippy` separately
- Linux build with primed …
=> Attempt to improve GitHub CI build time

.github/scripts/ci-build.sh, .github/scripts/ci-setup.sh, appveyor.yml
AppVeyor build broken since #1118, because the script `.github/scripts/ci-buidl.sh` was split. I didn't realize it has been used by AppVeyor msys2-mingw build.
=> Fix msys2-mingw build on AppVeyor

src/game/Editor/EditorMercs.cc, src/game/JAScreens.cc, src/game/Strategic/Strategic_Movement.cc, src/game/Tactical/Overhead_Types.h, src/game/Tactical/Rotting_Corpses.cc, src/game/Tactical/Soldier_Create.cc, src/game/Tactical/Tactical_Save.cc
Cleans up and removes `SET_PALETTEREP_ID`. Replaces with `=` assignment, or `.set()`.
Fixes #1113 and follows up on https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1049#discussion_r415354629. This should clear the one remaining bug before [0.17.x](https://github.com/ja2-stracciatella/ja2-stracciatella/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.17)
I took the patch from https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1113#issuecomment-641044901. On a second thought, I think there is nothing wrong with doing `ST::string::set`. It is part of the public API.
Then I went through each usage of `SET_PALETTEREP_ID`. All other usages are fine with a simple `=` assignment. So I replaced all of them and it should clear things up.
=> Clean up SET_PALETTEREP_ID

src/game/Strategic/Game_Init.cc
Fixes #87. This regression is probably as old as Stracciatella itself.
The music transition is implemented with end-of-sound callbacks. So the next music will start after the current music has faded out. However, during `ReStartingGame()` (called when returning to main menu), it calls `SoundStopAll()`, which forcefully closes all channels and skips the callback.
Then, when main menu comes up, it still think there is a music playing, so it will try to fade out the current music and wait for the callback which will never come.
See the channel state transitions here. It should be case `2`:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/6f1e2e71c022dea7727495e47e1d14154adb4e57/src/sgp/SoundMan.cc#L32-L45
The fix is to properly stop the music before calling `SoundStopAll()`, which …
=> Explicitly stop the music before returning to main menu

src/game/Tactical/Turn_Based_Input.cc
Or else the game will not be able to un-pause and freeze.
Fixes #752. More details in the issue.
=> Disallow hotkey `o` during meanwhile cutscenes

src/game/Tactical/Handle_Doors.cc, src/game/Tactical/Points.cc
the first commit just supercedes #705, while for the second I opted to continue showing the menu.
=> Collapsed mercs shouldn't cheat

rust/stracciatella_c_api/src/c/misc.rs, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/DefaultContentManagerUT.cc, src/externalized/ModPackContentManager.cc, src/externalized/ModPackContentManager.h, src/sgp/FileMan.cc, src/sgp/FileMan.h, src/sgp/FileMan_unittest.cc, src/sgp/SGP.cc
For #707. Building on top of the VFS introduced in #1067.
- Adding VFS_ORDER for user home directory
- The effective VFS order is like https://github.com/ja2-stracciatella/ja2-stracciatella/issues/707#issuecomment-509862638, except the tmp dir
- Adding mods and assets directory in user home (`~/.ja2` or `%userprofile%\documents\JA2`)
- Mods can be loaded from one or more directories. VFS ordering determines which files to use
- User home directory (`~/.ja2/data`) has the higher  priority than Stracciatella assets (`/usr/share/ja2`)
- Update launcher to list mods from both assets and home directories
-------
If this PR is accepted, we may need to update documentations to tell users what they can do. They may need to create `~/.ja2/data/` and copy from `/usr/share/ja2`. We do not support …
=> Supporting more data directories

.github/scripts/ci-build.sh, appveyor.yml
Small improvement for #1102. This should save around 2 minutes on each AppVeyor build. 
`rustfmt` and `clippy` are both static analysis. We only need to run once per commit to rust code, and no point to run on each and every platform.
After this PR rust code checks will only run on the Linux build on GitHub CI, which is currently the fastest build. This should speed up all other builds.
=> Run rust lint and fmt only once

src/game/Laptop/IMP_SkillTraits.cc
For #1127. Adjusting title ("I.M.P. Specialties") by 3 pixels. Now it looks like:
UB [screenshot](https://user-images.githubusercontent.com/63151803/83973310-1a134080-a918-11ea-9304-c24eed2d1450.png) for comparison.
=> Adjusting y-position of Skill Traits title

src/game/Tactical/Handle_UI.cc, src/game/Tactical/Handle_UI.h, src/game/Tactical/Interface_Control.cc
Analysis here: https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1122#issuecomment-650511871
Fixes #1122. Preserves the behavior of #565.
This fix ensures scrolling is un-freezed when we enter combat mode during rubber-banding. Also re-tested #550.
=> Fix tactical screen scroll freeze

src/externalized/DefaultContentManager.cc, src/game/Editor/EditScreen.cc, src/game/Laptop/IMP_Compile_Character.cc, src/game/Strategic/Map_Screen_Interface_Map_Inventory.cc, src/game/Strategic/Queen_Command.cc, src/game/Strategic/Strategic_AI.cc, src/game/Tactical/LOS.cc, src/game/Tactical/Soldier_Ani.cc, src/game/Tactical/Weapons.cc, src/game/TacticalAI/AIMain.cc, src/game/TacticalAI/FindLocations.cc, src/game/TacticalAI/NPC.cc, src/game/TileEngine/Physics.cc, src/game/TileEngine/TileDef.cc, src/sgp/MemMan.cc, src/sgp/SoundMan.cc
This should supersede #899. Changes only logging.
I went through the format string issues flagged by Coverity, and replaced `printf`-style format strings with `ST::format`. I went through the ones under "API usage error", not so sure if I missed any other things.
=> Fix some more coverity issues with format strings

src/externalized/ShippingDestinationModel.cc, src/externalized/army/ArmyCompositionModel.cc, src/externalized/strategic/MineModel.h, src/game/Laptop/IMP_SkillTraits.cc, src/game/Strategic/Creature_Spreading.cc
Fixing some recently introduced GCC warnings: `-Wunused-variable`, `-Wsign-compare` and `-Wreorder`.
=> Fix compiler warnings

CMakeLists.txt, rust/stracciatella/src/logger.rs, rust/stracciatella_c_api/src/c/logger.rs, src/sgp/Logger.h
Fixes #1136 
Should optimize logging performance in general:
- Dont build log record when it is filtered anyways
- Pass filename via Macro to Rust instead of building it from the full path in rust
=> Fix time consuming logging

src/game/Tactical/Soldier_Profile.cc
This is almost the same crash as #1068, but for a civilian in faction. (cf. #1069)
This is a crash of the same thing at a different place. If a non-hostile unnamed civ of faction dies when game is in strategic map, it crashes with uncaught exception `invalid profile id 200`. 
Just any way you get a unnamed civ in faction injured without turning hostile. For example:
- In San Mona, spawn a creature/monster and have it injure one of Kingpin's men. 
- Kill the monster so the civ is left at wounded, bleeding state
- Go to map screen and fast forward still he bleeds out
In Night Ops maps, I got a bloodcat ambush near San Mona. The bloodcats wounded one of civs of Kingpin faction. This should also be possible in vanilla with the Hicks.
```
ja2.exe!WhichBuddy(unsigned char ubCharNum, unsigned …
```
=> Fix a crash when a Civ of faction bleeds out

src/game/TileEngine/Render_Fun.cc
This is a fix for a edge-case handling in `SetGridNoRevealedFlag` (Render_Fun.cc) with possible bad map data, which does not happen with vanilla maps but with mods. 
The sector [I8](https://github.com/ja2-stracciatella/mod-nightops-maps/blob/master/data/Maps/I8.dat) of NightOps map pack crashes with a uncaught `std::logic_error("FindLevelNodeBasedOnStruct failed")` when grid `11937` is revealed. Tried both the debugger and map editor, I have not been able to figure out what's wrong with the map data. The crash analysis is at https://github.com/ja2-stracciatella/mod-nightops-maps/issues/2.
The map would not have crashed in vanilla (see https://github.com/ja2-stracciatella/ja2-stracciatella/commit/a0a4a5a55f8fe2d62711ba24440fa3f8688f0440). This change effectively restores that part of error …
=> Catch and ignore exception with bad map data

src/game/Strategic/Strategic_Mines.cc
Fixes #1144. 
This is about the Drassen mine, if selected for depletion, being inconsistent with other mines. With this PR any depleting mine will always run out in ~2.5 days after head miner's warning (assuming 100% production).
Drassen head miner warns on depletion at around the 15th day, then it doubles the production rate, and runs out in about 2.5 days.
If any other mines are selected for depletion, the head miner warns after ~7.5 days. Production rate stays similar, and mine runs out in about 2.5 days.
Drassen head miner to warn after ~17.5 days. The production rate will stay about the same, and the mine runs out in another ~2.5 days. Total ore supply is the same. This behaviour is now consistent with other mines.
Depletion behaviours of other mines are unchanged.
=> Drassen to be consistent with other mines before depletion

src/game/Strategic/Map_Screen_Helicopter.cc, src/game/Strategic/Map_Screen_Helicopter.h
Fixes #723 , which is test case 2 below.
Before this PR, the Heli is lands if the current sector is a Refuel Site, but without checking if it is player controlled and if refueling is available. 
This PR introduces `IsRefuelAvailableInSector`, which re-uses `NearestRefuelPoint` which considers those other factors. `IsRefuelSiteInSector` is kept and used only for updating refuel site availability.
| # | I6 (Estoni) | I6 has fuel? | B13 (Drassen) | Heli location | Vanilla Behaviour
|--|-- | -- | -- | -- | --
1 |Not visited | No | Player Controlled | C13 | Returns to B13
2 |Not visited | No | Player Controlled | I6 | Returns to B13
3 |Not visited | No | Player Controlled | I7 | Returns to B13
|  |   |   |   |  
4 |Not visited | No | Enemy Controlled | C13 | Returns to B13
5 |Not visited | No …
=> Heli to land only if refuel site is available

src/game/Tactical/Interface_Items.cc, src/game/Tactical/Items.cc, src/game/Tactical/Items.h
Fixes #690. 
This PR is about the `COMBINE_POINTS` merging of the same consumable and stackable items (ammo, first-aid kits).
The game has always allowed merging the on-hand item with the first in stack. In `AttachObject` we only considered `target.bStatus[0]` which is the first in stack, no matter which stack item is selected. 
This PR passes the currently selected item index in stack (`gubItemDescStatusIndex`) to the `AttachObject` so it can do the right thing.
---
Detailed usage (in case not obvious):
1. In inventory view, stack up ammo to be merged into (or first-aid kits)
1. Pick up another ammo to merge in
1. Right-click on the stack to see stack members
1. Right-click on stack member to bring up the merge/attachment panel
1. Left-click on an attachment slot to merge
=> Allow merging stacked item

src/game/Tactical/LOS.cc
Fixes #1140. Commit by @wvx, tested by me.
This brings the pre-conditions of `usShotsHit++` and `usShotsFired++` in sync.
=> Sync usShotsHit with usShotsFired

src/game/Tactical/Animation_Cache.cc, src/game/Tactical/Animation_Cache.h
Fixes #721, which is caused by evicting an in-use animation surface from AnimCache.
Should also fix #139.
- For cache eviction, consider also the current `pSoldier->usAnimSurface`
- We can have up to 2 "reserved" cache slots, the max cache size must be larger than 2
- `guiCacheSize` increased from 2 to 3
- This may lead to higher memory usage, extra ~40 bytes for each soldier
- AnimCache does not get saved, so it does not impact game saves
- Cache size might be made configurable, some day. See also https://github.com/ja2-stracciatella/ja2-stracciatella/commit/235a49d07fb8bf5e5ce1959e7720a6bf6234eda1
Bug described [here](https://github.com/ja2-stracciatella/ja2-stracciatella/issues/721#issuecomment-654258818) can no longer be reproduced. Now it hits the added eviction check as expected, …
=> AnimCache should not evict in-use surface

src/externalized/policy/DefaultGamePolicy.cc
This fixes a memory access violation inside RapidJSON (`obj.HasMember`) that prevents game from launching. The error only happens with Release build (built with Visual Studio 2019 on Win 10). I am not 100% sure about what's wrong, but I suspect it is some temp variables got pre-maturely cleaned up.
Exception thrown during loadGameData:
```
Exception thrown at 0x00007FF723FE1C47 in ja2.exe: 0xC0000005: Access violation reading location 0x000000C74D78000E.
```
Call stack:
```
>	ja2.exe!rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::FindMember<rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>(const rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>> & name) Line 1158	C++
[Inline …
```
=> Avoiding GetObject call on JSON object

src/externalized/strategic/BloodCatPlacementsModel.cc, src/game/Strategic/Game_Init.cc
Bloodcat Lair and Arena are without the cats as a result. All sectors in the lower half of the map has no bloodcat placements (and maybe some invalid memory access with negative index, of unknown effect)
It should have been UINT8 instead of INT8. Requires a new game if game was started with the wrong init.
I did a quick grep (`grep -Ri sectorid src/ | grep -i int8 | grep -vi uint`) and found no other occurrence of `INT8 sectorId`
=> Fix incorrect type used for Sector ID (Bloodcat Spawn)

src/game/Tactical/LoadSaveObjectType.cc
Fixes https://github.com/ja2-stracciatella/mod-nightops-maps/issues/5
Changes `ExtractObject`, which reads `OBJECTTYPE` from saves and maps. 
For example, NightOps maps H13 contains a few items not defined in JA2:S. The principle here is we should be more defensive reading files, as we now have mods. On reading an invalid item index, instead of de-referencing null pointer, the game should issue a warning and continue to load rest of the file.
=> Ignore invalid items when reading files

src/game/LoadSaveTacticalStatusType.cc
To avoid confusion like #1004.
Turn off debug `uiFlags` (i.e. `DEBUGCLIFFS` | `SHOW_Z_BUFFER`) when loading a save - unless we started with `-debug` option.
=> Do not restore debug uiFlags from saves

src/game/Strategic/Creature_Spreading.cc, src/game/Strategic/Creature_Spreading.h, src/game/Strategic/Game_Init.cc
Found bugs when investigating a [bug report](http://thepit.ja-galaxy-forum.com/index.php?t=msg&goto=360622&#msg_360622 ).
- a67c898e6f54dad93d041acfe2051882f776ed35: `gubSectorIDOfCreatureAttack` is not correctly updated, which should mean all attacks will happen at the mine entrance sector. (Bug since #1106)
- fd2b3bea9431109329d7e779105c6898e6e68be1: `giLairID` never got reset during `ReStartingGame`. This seems to be an old issue (v0.16 or earlier). Loading a game with an active lair, then starting a new campaign game cause the next game to have the wrong `giLairID`, and this wrong ID will get saved.
Needs more testing, and further investigation to see if it is related to the reported bug.
=> Fix creature town attack

src/externalized/ShippingDestinationModel.cc, src/externalized/strategic/CreatureLairModel.cc, src/externalized/strategic/MineModel.cc, src/externalized/strategic/UndergroundSectorModel.cc, src/sgp/SGP.cc, src/sgp/SGP.h
Un-handled exceptions on Windows are not logged. It only prints something like "exited with status code X" (e.g. #1165).  
This PR adds a `std::terminate()` handler (`_WIN32` only) which prints `e.what()` and the type, and then continues with `std::abort()`. Example output:
```
2020-08-02T03:14:34 [ERROR] sgp\SGP.cc: Game has been terminated due to an unrecoverable error: Unrecognized mine type: 'SILVER_MINES' (class std::runtime_error)
2020-08-02T03:14:34 [ERROR] launcher\Launcher.cc: Command_execute "D:\\Games\\JA2Classic\\ja2.exe" []: exited with status code -1073740791
```
There are a few cases we log and then throw without a message (e.g. https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1074#discussion_r426923424). All those are updated to throw an exception with message.
=> Print unhandled exception message on Windows

src/sgp/SGP.cc
The Windows console has a feature called "quick edit mode". When activated, it freezes the STDIO and pauses program execution., when user click anywhere on the console. It might be defaulted to enabled in Windows 10, but I am not entirely sure. 
This PR will switch off Quick Edit mode whenever the game starts, in case it is already turned on at that time. User can still manually enable the quick edit mode from the menu.
A minor usability improvement. Not strictly necessary for the 0.17 release
Documentation: https://docs.microsoft.com/en-us/windows/console/setconsolemode
> To enable this mode, use ENABLE_QUICK_EDIT_MODE | ENABLE_EXTENDED_FLAGS. 
> 
> To disable this mode, use ENABLE_EXTENDED_FLAGS without this flag.
=> Turn off console Quick Edit mode (Windows only)

src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/DefaultContentManagerUT.cc, src/externalized/DefaultContentManagerUT.h, src/externalized/DefaultContentManager_unittests.cc
Another usability improvement, but also involves some refactoring.
JSON errors or schema differences (e.g. using 0.16.1 JSON with 0.17) may just result in a "exited with status code <something>". At least on Windows, the exception message does not get printed.
- Centralizes `rapidjson` parsing and error handling in one function
- Logs and throws an error message with parse error code and byte offset
- Wraps the `rapidjson` document in a `shared_ptr`; `delete` no longer required
=> Better error messages on JSON parse errors

src/launcher/main.cc
Same as #1166 but for the launcher. Quick-edit mode on Windows can also freeze the launcher.
This PR forces Quick-Edit mode to be off when launcher starts. When JA2.exe starts, it will try to disable it again. This is necessary, because they are independent executables sharing the same console window.
=> Disable quick edit mode when Launaher start (Windows only)

assets/externalized/game.json, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/game/Utils/Timer_Control.cc, src/game/Utils/Timer_Control.h
Vanilla JA2 has no speed control, so animations and UI transitions run as fast as the computer can handle; In JA2:S we have the `GetJA2Clock()`, which ticks by 10 for each 10ms of system time.
This PR adds a `ms_per_time_slice` (Suggestions for better names are welcome) to the game policy. The player can double the JA2Clock speed, by setting it to 5ms per time slice. It affects everything that waits on JA2Clock. From what I see, soldier animations and laptop transition are the most noticeable.
And we removed `CALLBACKTIMER`, since it's a useless define.
Resolves #148.
=> Configurable BASETIMESLICE duration

src/game/Strategic/Map_Screen_Interface.cc, src/game/Strategic/Map_Screen_Interface_Bottom.cc
Fixes #412.
This PR disallows changing sector, time compression and strategic squad movement during a bloodcat ambush, as if sector is hostile.
Before this PR, the hostile sector check only checks for :
- `INCOMBAT` in gTacticalStatus.uiFlags
- gTacticalStatus.`fEnemyInSector`
- `InAirRaid` _(to be cleaned up)_
Bloodcats in the wild are neutral before they are spotted, similar to hostile civilians. So during an ambush but before seeing a bloodcat, player could still do strategic actions, as combat (turn-based) mode is off and there are no enemies in sector.
Bloodcat ambush is checked by ` gubEnemyEncounterCode == BLOODCAT_AMBUSH_CODE && HostileBloodcatsPresent()`. The check is specific to ambushes. All other kinds of bloodcat encounters are not covered by this check.
=> No strategic movements during bloodcat ambush

src/sgp/Video.cc
Resolves #1169.
In Pixel-Perfect mode:
1.  Throws can error if the desktop is too small for the requested game resolution. Pixel-perfect mode cannot scale down. It will result in an empty black screen.
2. Limits the minimize size in Windowed mode. Resizing the window to anything smaller will result in an empty black screen.
=> Improve Pixel-Perfect scaling usability

docs/Release-checklist.md
merged with the one for 0.17 and cleaned up
=> docs/Release-checklist.md: converted to github checklist

src/externalized/DefaultContentManager.cc, src/game/Strategic/MapScreen.cc, src/game/Strategic/Scheduling.cc, src/game/Tactical/Interface_Dialogue.cc
Reducing the log levels of those that does not affect anything, or those that players do not need to know:
1. `Adding directory to VFS` - unless developing mods or changing VFS, I don't think players need to know about this
2. `Skipped adding to VFS` - the caller has already requested to skip errors, so loading this is totally optional
3. `Can't compress time, pause state locked (reason %d). OK unless permanent...` - this happens when you press `+` during a message popup
4. `Schedule callback occurred outside of tactical -- Auto processing!` - this is a normal case, nothing to worry (https://github.com/ja2-stracciatella/ja2-stracciatella/commit/34f35318764671a121239543b9e86554ded499aa#diff-7715cba6d43e93a9ffead03797722f0bL201-L203)
5. `No code support for NPC action` - several NPCs at San …
=> Reduce noise in logs

assets/externalized/weapons.json, src/externalized/WeaponModels.cc, src/externalized/WeaponModels.h, src/game/Tactical/Weapons.cc
Externalizing the monster-spit to gas-effect mapping, so the code do not have a dependency on the MONSTER_SPIT pseudo-weapons. Some mods (I mean Unfinished Business) re-purpose the monster spits' item ID to be actual weapons.
The new field `usSmokeEffect` is an item index, mandatory for monster "weapons". Values should be one of the CREATURE_GAS items:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/6f2ec3397094cdac5cd3e7efaeb4304831029113/src/game/Tactical/Items.cc#L96-L98
=> Adding the monster spit effect to weapons.json

assets/externalized/loading-screens-mapping.json, assets/externalized/loading-screens.json, src/externalized/CMakeLists.txt, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/LoadingScreenModel.cc, src/externalized/LoadingScreenModel.h, src/game/Loading_Screen.cc, src/game/Loading_Screen.h, src/game/Strategic/StrategicMap.cc
At the high level, there are 2 ways to determine the loading screen for a sector:
1. Specific mapping from sector to loading screen (e.g. P3 => `DAYPALACE`,  A2 => `NIGHTCHITZENA`)
2. If no mapping found, there are rules for land types, SAM sites, underground caves, etc
This PR externalizes part 1 of the loading screen logic. There are 2 kinds of data externalized:
1. Loading screen details, which has an index (`LoadingScreenID`), and points to a resource file (.STI) 
2. Mapping from `sector + night/day` to `LoadingScreenID`
With this, mods can freely add new loading screens and then maps specific sectors to them. Though it is not possible to change the rules via JSON, the mods can resort to adding a mapping for every single sector.
Part of #665.
=> Externalize sector Loading Screens

src/externalized/Soldier.cc, src/externalized/Soldier.h
Resolves #649.
Re-worked the goggle auto-switch (Ctrl-N). Now it swaps the goggles as requested, be it in an inventory slot or as a helmet attachment.
It does not put away the wrong goggle, if there is no appropriate gear. It does not put away the Sun Google at night or Night Goggles in daylight. There is no penalty for wearing the wrong goggles.
(See cd8ff3c7a3e63e7004e3351e5135e1c255315bbe, 801fdfb0a44b85607fff0bf099b8bdd715da4793) This is simpler, that it does not require IME stuff, does not consider time of day, sector level, lighting or gas.
- If wearing GASMASK, return
- Find the optimal gear to wear:
- If gear is present in inventory, pick it
- Else, if gear is present in helmet attachment, detach
- If not yet found, continue with the next preferred gear
- Find the currently …
=> Auto-switch attached goggles

src/externalized/DefaultContentManager.cc, src/game/Strategic/Creature_Spreading.cc
Warp exit is not working in some cases (since 0.17.0). After finishing the quest, but before leaving the lair, save and load the game. It no longer prompts for "Travel to surface"
When the creature quest is finished, `giLairID` becomes -1. On the next game load, `gLairModel` becomes NULL, and we must rely on `giDestroyedLairID` instead.
=> Fix warp exit from mine

assets/externalized/dealers.json, src/externalized/CMakeLists.txt, src/externalized/ContentManager.h, src/externalized/DealerModel.cc, src/externalized/DealerModel.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/game/Tactical/Arms_Dealer_Init.cc, src/game/Tactical/Arms_Dealer_Init.h, src/game/Tactical/ShopKeeper_Interface.cc
Externalizes (#665) `ARMS_DEALER_INFO`, which is the info for all bartenders/traders/repairmen in game. Dealer inventory are already externalized, and this PR externalizes the dealers themselves.
The first few commits are method extraction that should not change any functionalities.
The next commits are adding the JSON data, adding model classes, and replacing `ARMS_DEALER_INFO&` with `const DealerModel*`. New dealer flags are added but not yet used in this PR.
This PR avoids any non-essential changes, as it already has many lines changed. I intend to make further PRs to generalize some hardcode logic (e.g. repairmen check, electronics repairer (Fredo) check, and so on), and maybe to relax the limit on number of dealers.
I will do a full round of testing after the follow-up PRs.
=> Externalize (arms) dealer info

src/externalized/DealerModel.h, src/game/Tactical/Arms_Dealer.h, src/game/Tactical/Arms_Dealer_Init.cc, src/game/Tactical/Arms_Dealer_Init.h, src/game/Tactical/ShopKeeper_Interface.cc
This PR generalizes some hard-coded dealer logic with dealer flags. The ultimate goal should be removing all `ArmsDealerID` enum references in code, but this PR only covers the obvious ones. 
The other references couple with quests and facts. We can generalize or externalize those when mods require, or when we have some kind of scripting.
- `REPAIRS_ELECTRONICS`: replaces checks for `FREDO`
- `DELAYS_REPAIR`: only `PERKO` and `FREDO` can delay repair jobs
- `BUYS_EVERYTHING`: `JAKE`, `KEITH` and `FRANZ` buys things not in their inventory list
- `SELLS_FUEL` : replaces checks for `JAKE`
- `SELLS_ALCOHOL`: replaces the hard-coded bartender list
=> Generalizing hard-coded dealer logic

src/externalized/MagazineModel.cc, src/externalized/MagazineModel.h, src/externalized/WeaponModels.cc
The editor displays the "unused", "NOWEAPON", "CLIP_NOTHING" at the end of the item display.  Those are item slots reserved for weapons or magazines, but not used. 
In Vanilla they are of class `IC_NONE` and hence ignored by the editor. In Stracc, it was changed during the externalization and they are currently of class `IC_PUNCH` and `IC_AMMO` (see https://github.com/ja2-stracciatella/ja2-stracciatella/commit/1aa7ef5e6ae2d40ed88e87910555f225fabf9d23).
This PR changes those "items" back to `IC_NONE`, so they will be ignored by the editor.
=> Unused items slots should be IC_NONE

assets/externalized/weapons.json, src/externalized/WeaponModels.cc, src/externalized/WeaponModels.h
Resolves #1192. 
There were some minor data errors in the weapons data. 
- Punch is done with the "Nothing" item, which should have class `IC_PUNCH` with `PUNCHCURS` cursor
- Rocks (for throwing) should have class `IC_THROWN` with `TOSSCURS` cursor
- Unused items should  be of class `IC_NONE` with `INVALIDCURS` (the question mark cursor).
Commit for reference: https://github.com/ja2-stracciatella/ja2-stracciatella/commit/1aa7ef5e6ae2d40ed88e87910555f225fabf9d23
- Added new internalTypes for the "punch" and rocks.
- `ROCK` and `ROCK2` now uses internalType of `THROWN`, and removed the flag `thrown`
- The internalType `NOWEAPON` now indicates only unused item slots.
=> Fix punching and throwing rocks

src/game/Tactical/Handle_Items.cc, src/game/Tactical/Soldier_Control.cc, src/game/TileEngine/Physics.cc
This PR ports 3 of the most straight-forward patches from Unfinished Business (#1198). They fix bugs present in vanilla.
- PATCH200: Light up soldier body if fake light is off
- PATCH208: Disarming trap when inventory is full
- PATCH029: Disallow breaklights on rooftop
=> Small bug-fixes from Unfinished Business

src/game/TacticalAI/NPC.cc
The previous commit was wrong due to unsigned int underflow (https://github.com/ja2-stracciatella/ja2-stracciatella/commit/8f82d7c8863a32d7b819030783071eb58e8dbe5f#diff-d7b592fe9648bce54f92b4be00bf2c48L1163-L1177). Fatima won't talk or accept the letter as a result of this bug.
This commit first checks if the subtraction is valid for the unsigned int, before comparing.
=> Correcting unsigned int comparison in NPC.cc

appveyor.yml, dependencies/lib-fltk/CMakeLists.txt, dependencies/lib-fltk/builder/CMakeLists.txt.in, dependencies/lib-gtest/CMakeLists.txt, dependencies/lib-string_theory/CMakeLists.txt, dependencies/lib-string_theory/builder/CMakeLists.txt.in
Currently all builds on appveyor fail because fltk cannot be compiled. There are a bunch of errors of the following kind, within `winbase.h`.
```
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(9036,31): error C2065: '_InterlockedOr64': undeclared identifier [C:\projects\ja2-stracciatella\ci-build\dependencies\lib-fltk\builder\fltk-prefix\src\fltk-build\src\fltk.vcxproj] [C:\projects\ja2-stracciatella\ci-build\dependencies\lib-fltk\builder\fltk.vcxproj]
```
Since we didn't change anything about fltk or how it is built, my guess this is due to external changes.
According to https://developercommunity.visualstudio.com/content/problem/1139955/c-builds-with-windows-sdk-81-fail-after-upgrade-to.html there is an issue with windows sdk in version 8.1 and Visual Studio 16.7. Since …
=> Use fixed Windows SDK version on appveyor

src/externalized/scripting/ScriptingExtensionsLua.cc
- Errors in lua scripts now include the filename where the error happened
- Log messages from lua now print the lua filename where they are triggered from (unfortunately not the exact location as it only prints the vfs filename right now, e.g. `main.lua` instead of `mods/mod_name/scripts/main.lua`).
References: #1205
=> Better lua debugging functionality

src/game/Editor/PopupMenu.cc, src/game/TileEngine/Overhead_Map.cc, src/game/TileEngine/WorldDat.cc, src/game/TileEngine/WorldDat.h, src/game/TileEngine/WorldDef.cc, src/game/TileEngine/WorldDef.h, src/game/TileEngine/World_Tileset_Enums.h
This PR allows us to load both JA2 Vanilla and JA2.5 Unfinished Business maps.
Vanilla has 50 tilesets. Unfinished Business adds another 20, a total of 70. I believe there are no dispute that tilesets 50~69 are for UB.
- `gTilesets` is now 70 elements long
- This is fully compatible with vanilla data; With vanilla data, we only load first the 50 tilesets and the maps only reference those.
- `NUM_TILESETS` is now a variable `ubNumTilesets` read from Tileset DB; it must be either 50 or 70.
- There is a "default tileset" (`GENERIC_1` in vanilla) which has the special tiles such as doors; JA2.5 tilesets (index > 50) uses a different "default"
This is ported from UB source code: 
- [PATCH020](https://github.com/ja2-derek/ja2-ub-comparison/commit/c41920c5)
- …
=> Support Unfinished Business ("JA 2.5") tilesets

src/game/TileEngine/WorldDef.cc
The comparison is on the TileSetID not the TileType. It should be some copy-and-paste mistake I made during the refactor.
This commit has been tested and the game loads Vanilla maps correctly.
=> Fix the Tileset defaulting logic

.ci/ci-publish.sh, .github/scripts/ci-build.sh, .github/scripts/ci-setup.sh, .travis.yml, CMakeLists.txt, COMPILATION.md, rust/stracciatella/src/stracciatella.rs, rust/stracciatella_c_api/src/c/misc.rs, src/externalized/TestUtils.cc, src/sgp/SGP.cc
Some changes to currrent logic were necessary:
- Always search EXTRA_DATA_DIR relative to binary (makes binary relocatable)
- Install linuxdeploy in CI, to build the AppImage
- Add cmake task `package-appimage` that is executed instead of `package` for linux
Closes #1213. Closes #138.
I will wait for build and test the resulting AppImage on multiple distros before merging.
=> Build AppImage for linux

rust/Cargo.lock
Mac build is currently broken. Also noticed there is a new crate release of serde. It might have caused inconsistency in the cargo lock.
Trying `cargo update` to see if it helps with the Mac build problem.
<details>
<summary>List of crates updated</summary>
<pre>
Updating aho-corasick v0.7.10 -> v0.7.13
Updating autocfg v1.0.0 -> v1.0.1
Updating base64 v0.11.0 -> v0.12.3
Updating chrono v0.4.11 -> v0.4.15
Updating clap v2.33.0 -> v2.33.3
Adding crossbeam-channel v0.4.4
Removing crossbeam-queue v0.2.1
Updating dunce v1.0.0 -> v1.0.1
Updating either v1.5.3 -> v1.6.0
Updating getrandom v0.1.14 -> v0.1.15
Adding hashbrown v0.9.0
Updating hermit-abi v0.1.10 -> v0.1.15
Updating indexmap v1.3.2 -> v1.6.0
Updating itoa v0.4.5 -> v0.4.6
Updating libc v0.2.68 -> v0.2.77
Updating log v0.4.8 -> …
=> Updating cargo deps

.travis.yml
It always installs AppDir for linux now and runs tests from there. I also removed a duplicate `BUILD_SWITCHES` setting from mingw.
=> Another try at fixing travis build

.github/workflows/github-ci.yml, rust/Cargo.lock
Changes so far:
- Update cargo.lock - `cargo update` again
- Changing the paths to cache
- Cache only some directories under `~/.cargo`, as per [docs](https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci)
- Do not cache lib-stracciatella/target/, we rebuild every time
=> Try to fix Mac build

CMakeLists.txt, appveyor.yml
Enabling build cache on AppVeyor so we can re-run stuff between builds (#1102). It should save up to 3 minutes per build 
- Caching the [cargo home directory](https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci)
- Caching rustup install (`~/.rustup`)
- Caching and re-using the lib-fltk working directories
- Use [sccache](https://github.com/mozilla/sccache) to speed up rustc ~and VC++~ compilations
=> Build caching on AppVeyor

src/game/Strategic/StrategicMap.cc, src/game/Strategic/StrategicMap.h, src/game/TileEngine/Explosion_Control.cc, src/game/TileEngine/Explosion_Control.h, src/game/TileEngine/Structure.cc, src/game/Utils/CMakeLists.txt, src/game/Utils/Observable.cc, src/game/Utils/Observable.h
Further to the discussion at https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1205#issuecomment-689418616. This is a proposal to implement the "Observer" pattern, for 1) dependency inversion, and 2) allow registering callback at runtime.
This is conceptually similar to event/delegate of C#. The subject ("observable") allows registering of typed callback functions, and the subject need no knowledge of what's inside the callbacks. Typically it is the core engine calling back a campaign or sector specific logic.
In contrast to the Strategic_Event_Handler implementation, the Observable class is strong-typed. But that means each callback must be registered explicitly, you cannot have a single handler function switching on event type. This could mean quite a lot of boilerplate code …
=> Dependency inversion with Observable and notify

rust/stracciatella/Cargo.toml, rust/stracciatella/src/bin/resource_pack.rs, rust/stracciatella/src/file_formats/mod.rs, rust/stracciatella/src/file_formats/slf.rs, rust/stracciatella/src/vfs/mod.rs, rust/stracciatella/tests/test_vfs.rs, rust/stracciatella_c_api/src/c/vfs.rs, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/DefaultContentManagerUT.cc, src/externalized/ModPackContentManager.cc, src/externalized/ModPackContentManager.h, src/sgp/SGP.cc
This is a proposal to move VFS initialization to a single place: The rust vfs module. Imho this makes it easier to grasp how the VFS is initialized compared to the VFS initialization at multiple places in C++ code using the order enum.
It also allows for SLF files in the mods directories.
The first two commits are cleanup commits that are kind of unrelated.
=> Initialize VFS at a single place from EngineOptions

src/game/Strategic/SAM_Sites.cc, src/game/Tactical/End_Game.cc, src/game/Tactical/End_Game.h, src/game/Tactical/Overhead.cc, src/game/TileEngine/Explosion_Control.cc, src/game/TileEngine/Explosion_Control.h, src/game/TileEngine/Structure.cc, src/game/TileEngine/Structure.h
Follow up after our discussion in [#1223](https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1223#issuecomment-694161770). Further cleaning up TileEngine by removing sector-specific code.
- TileEngine to do callback just before and right after a structure being damaged
- Added `STRUCTURE*` and `fIsDestroyed` to `OnStructureDamaged` callback
- Moved away SAM sites, brothel and statue logic from TileEngine
- Replaced an abused BOOLEAN return value with enum
=> More TileEngine refactoring

src/game/Strategic/Strategic_Movement.cc, src/game/Strategic/Strategic_Movement.h, src/game/Tactical/Vehicles.cc
Minor refactoring.
SetGroupArrivalTime() is a method to set `uiArrivalTime` in the struct `GROUP`. This method is very tightly coupled to a single field in `GROUP` and it should also be located at the same place.
Look at this example:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/b413e4d66eefec9c98db4bb28e4b22d88d0bb726/src/game/Strategic/Strategic_Movement.cc#L1547-L1555
=> SetGroupArrivalTime to be a member of GROUP

assets/externalized/mercs-MERC-listings.json, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/mercs/CMakeLists.txt, src/externalized/mercs/MERCListingModel.cc, src/externalized/mercs/MERCListingModel.h, src/externalized/mercs/MERCSpeckQuote.h, src/game/Laptop/Laptop.cc, src/game/Laptop/LaptopSave.h, src/game/Laptop/Mercs.cc, src/game/Laptop/Mercs.h, src/game/Laptop/Mercs_Account.cc, src/game/Laptop/Mercs_Files.cc
This PR externalizes (#665) and generalizes the merc profile handling in M.E.R.C. The goal is to allow mods to add new mercs in M.E.R.C., and let them change the availabilities (e.g. make everybody available right from the start). Quite a few parts of the M.E.R.C. code was re-written.
- Soldiers' availability on M.E.R.C. (`CONTITION_FOR_MERC_AVAILABLE`, not my typo) are fully controlled from JSON data
- Speck's merc-specific quotes are also controlled from JSON data
- The save game data field `ubLastMercAvailableId` is no longer used
Larry (`LARRY_NORMAL` and `LARRY_DRUNK`) handling has been quite ugly. The old code has 2 Larry profiles in the MERC array, and will use only of them depending on whether Larry has relapse or not. In some places (e.g. Mercs_Files page), `LARRY_DRUNK` is …
=> Externalization and generalization of M.E.R.C.

assets/externalized/game.json, src/externalized/JsonObject.h, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/game/Strategic/Game_Init.cc
Externalizes (#665) the day when M.E.R.C. goes online.
When set to [0, 0], we can hire M.E.R.C. people in the starting squad. Use #1244 if you want the better ones at the start.
=> Adding game policy options to customize when M.E.R.C. goes online

dependencies/lib-lua/CMakeLists.txt, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/DefaultContentManagerUT.cc, src/externalized/DefaultContentManagerUT.h, src/game/Tactical/Animation_Cache.cc, src/game/Tactical/Dialogue_Control.cc, src/game/TileEngine/Ambient_Control.cc, src/game/TileEngine/Render_Fun.cc, src/game/TileEngine/SaveLoadMap.cc, src/sgp/Logger.h
Fixes several compiler warnings, and apply the correct practices.
- Fixes the compiler warnings in Mac builds (https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1137#discussion_r453317787)
- Replaces `std::shared_ptr` with `std::unique_ptr` whenever applicable. `std::unique_ptr` should be used if pointer is to be owned by one. It also have much less overhead
- Fixes a number of compiler warnings
=> Cleaning up some C++ code

assets/externalized/mercs-profile-info.json
Some mercs are not defined in the enum `NPCIDs` or anywhere in the code. I used the enums to generate the JSON file in #1247, so some A.I.M. mercs had missing profile info data. As a result, those mercs are displayed like an enemy or NPC in tactical.
This PR adds all of the missing profile info data.
=> Adding back the missing Merc Profile info

assets/externalized/mercs-MERC-listings.json, src/externalized/mercs/MERCListingModel.cc, src/externalized/mercs/MERCListingModel.h, src/game/Laptop/Mercs.cc, src/game/Laptop/Mercs_Files.cc
The index/offset of M.E.R.C. profile text in `mercbios.edt` was determined by `profileID - BIFF`. It assumes the mercs are in a continuous range after `BIFF`. 
This PR externalizes the bio offset in JSON.
=> Externalizing M.E.R.C. profile bio index

assets/externalized/imp.json, src/externalized/policy/DefaultIMPPolicy.cc, src/externalized/policy/DefaultIMPPolicy.h, src/externalized/policy/IMPPolicy.h, src/game/Laptop/IMP_Compile_Character.cc
For #665. 
Allows I.M.P. mercs to start at higher levels, by changing the settings at `imp.json`. 
Added a field `initial_level` which has default of 1.
=> Externalizing I.M.P. initial level

android/app/src/main/java/io/github/ja2stracciatella/LauncherActivity.kt, android/app/src/main/java/io/github/ja2stracciatella/StracciatellaActivity.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/DataTabFragment.kt
The warnings look weird as it shows in every github actions build. I added a supression decorator and some comment explaining why we use deprecated APIs here.
=> Suppress or fix warnings for Android build

src/externalized/scripting/FunctionsLibrary.h, src/externalized/scripting/ScriptingExtensionsLua.cc, src/game/Tactical/End_Game.cc, src/game/Tactical/End_Game.h, src/game/TileEngine/Explosion_Control.cc, src/game/TileEngine/Explosion_Control.h, src/sgp/Types.h
The observable [BeforeStructureDamaged](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/63eb7a5b1a066db795dcb314ae72184539043f0b/src/game/TileEngine/Explosion_Control.cc#L363) is an example of sharing a variable with all listeners via a pass-by-pointer argument.
But such a simple pointer to primitive does not work as intended with Lua. In Lua, all primitives arguments (including pointers to primitive types) are always passed by value and all complex types are passed by reference. To implement pass-by-reference, I have created a simple struct to wrap around the primitive type. You can think of it like the variable boxing in [Java](https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html) or [C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxi …
=> Implement primitive value boxing for Lua listeners

android/app/src/main/java/io/github/ja2stracciatella/LauncherActivity.kt, rust/Cargo.lock, rust/stracciatella/Cargo.toml, rust/stracciatella/src/android.rs, rust/stracciatella/src/config/stracciatella_home.rs, rust/stracciatella/src/vfs/android.rs, rust/stracciatella/src/vfs/mod.rs, rust/stracciatella_c_api/src/c/config.rs, rust/stracciatella_c_api/src/c/misc.rs, rust/stracciatella_c_api/src/c/vfs.rs, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/sgp/SGP.cc
This fixes 2 out of 4 issues in #1248.
- Makes Android Asset VFS case insensitive
- Stores pointer to JNI globally in Rust
One thing to note is thatI needed to implement case insensitive matching via JNI, as it is not possible to list asset directories through the NDK asset manager. It can only list files in directories not directories.
Supporting mods from assets is gonna be a little trickier, as mods may also contain SLF files, so we have an SLF VFS within another VFS.
=> Android asset manager rehault - Part 1

assets/externalized/strategic-map-cache-sectors.json, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/JsonUtility.cc, src/externalized/JsonUtility.h, src/externalized/army/GarrisonGroupModel.cc, src/externalized/army/GarrisonGroupModel.h, src/externalized/army/PatrolGroupModel.cc, src/externalized/army/PatrolGroupModel.h, src/externalized/strategic/BloodCatPlacementsModel.cc, src/externalized/strategic/BloodCatSpawnsModel.cc, src/externalized/strategic/CMakeLists.txt, src/externalized/strategic/CacheSectorsModel.cc, src/externalized/strategic/CacheSectorsModel.h, src/externalized/strategic/CreatureLairModel.cc, src/externalized/strategic/MineModel.cc, src/externalized/strategic/MineModel.h, src/externalized/strategic/NpcPlacementModel.cc, src/externalized/strategic/SamSiteModel.cc, src/externalized/strategic/StrategicMapSecretModel.cc, src/externalized/strategic/TownModel.cc, src/externalized/strategic/UndergroundSectorModel.cc, src/externalized/strategic/UndergroundSectorModel.h, src/game/Strategic/Strategic_AI.cc
Externalizes the cache sectors data (#665). The game randomly chooses one of the five possible sectors to put a weapon cache.
This PR also includes some minor refactoring, for better code re-use and good general practice of passing const-ref (recommended by clang-tidy, might also be trivial marginal performance improvement).
=> Externalize cache sectors

rust/stracciatella/src/vfs/android.rs, rust/stracciatella/src/vfs/dir.rs, rust/stracciatella/src/vfs/mod.rs, rust/stracciatella/src/vfs/slf.rs, rust/stracciatella/tests/test_vfs.rs, rust/stracciatella_c_api/src/c/vfs.rs
Next step for proper AssetManagerFs support: Allow to load mods from Android assets.
This kind of got out of hand because now we have to support to create an `SlfFs` from another Vfs layer. I fixed this by introducing a trait for `VfsLayer` which allows to abstract away the `VfsLayer` (which also allowed me to remove a bunch of wrapper code). Currently it allows `open` for files and `read_dir` for directories. This allows to use `read_dir` on a VfsLayer to list all SLF files and `open` to open the `SlfFs` from the other VfsLayer. This is currently used for `DirFs` and `AndroidAssetFs`.
From the C++ side there were no changes needed, although I needed to wrap the `Box<VfsFile>` into another struct in the API, because it seems like we need to return concrete types to C++. But since this is …
=> Android VFS Rework Part 2

src/externalized/DefaultContentManager.cc, src/game/GameScreen.cc, src/game/TileEngine/Render_Dirty.cc, src/sgp/Video.cc
Fixes some memory leaks found with the `valgrind` tool. This is especially important for Android, as we use `ja2-stracciatella` as a library there, so memory leaks will accumulate over time. I omitted leaks in `SoundMan.cc`, as I have another branch (that I wanted to actually test for memory leaks) that does a big refactoring there...
=> Fix some memory leaks

.github/workflows/nightly.yml
I made some bad last-minute tidy-up on the previous PR.
The workflow is supposed to push nightly to remote with madlab-bot's credentials.
=> Fixing Nightly workflow 

src/externalized/AmmoTypeModel.cc, src/externalized/AmmoTypeModel.h, src/externalized/CalibreModel.cc, src/externalized/CalibreModel.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManagerUT.cc, src/externalized/DefaultContentManagerUT.h, src/externalized/DefaultContentManager_unittests.cc, src/externalized/ItemModel.cc, src/externalized/ItemModel.h, src/externalized/JsonUtility.cc, src/externalized/JsonUtility.h, src/externalized/MagazineModel.cc, src/externalized/MagazineModel.h, src/externalized/WeaponModels.cc, src/externalized/WeaponModels.h, src/externalized/army/ArmyCompositionModel.cc, src/externalized/army/ArmyCompositionModel.h, src/externalized/army/GarrisonGroupModel.cc, src/externalized/army/GarrisonGroupModel.h, src/externalized/mercs/MercProfileInfo.cc, src/externalized/mercs/MercProfileInfo.h, src/externalized/strategic/SamSiteModel.cc, src/externalized/strategic/UndergroundSectorModel.cc, src/game/Strategic/Campaign_Types.h
Continuing #1056.
Replacing `const char *` with `ST::string` in all model classes in `src/externalized`. Also a little clean up in WeaponModel.
- `const char*` => `ST::string`
- `if (!strcmp(s1, "STR"))` => `if (s1 == "STR")`
- `strlen(str)` => `str.size()`
- `#include "game/Tactical/Item_Types.h"` => `#include "Item_Types.h"`
- `ST::string str` (constructor args) => `std::move(str)` (see also [performance-unnecessary-value-param](https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-value-param.html))
- `Class::~Class() {}` => `Class::~Class() = default;`
- `std::map<ST::string, const ModelClass*>::const_iterator` => `auto`
=> Replacing const char* in model classes

assets/externalized/imp.json, src/externalized/policy/DefaultIMPPolicy.cc, src/externalized/policy/DefaultIMPPolicy.h, src/externalized/policy/IMPPolicy.h, src/game/Laptop/IMP_HomePage.cc
This PR externalizes the activiation code to `imp.json`. Player can proceed to I.M.P. creation if the given code matches any.
You usually do not want to change the activation code, because it is fixed in the email text. Unless you are playing [Unfinished Business](https://github.com/ja2-derek/ja2-ub-comparison/commit/9770aba9), in which the `email.edt` is changed as well.
And also, if you insist (I don't know why), you can name your IMP character `XEP624` and still use [I.M.P. import](https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1133).
=> Externalizing I.M.P. activation code

.github/workflows/coverity-scan.yml
Coverity expects analysis results under `cov-int/`. See https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1276#issuecomment-735913970
=> Fixing Coverity scans

CMakeLists.txt, src/sgp/CMakeLists.txt, src/sgp/Logger.h, src/sgp/Logger_unittest.cc, src/sgp/Platform.h
This should clear up all the "Illegal address computation" defects on Coverity.
Coverity is flagging problems with log statements and `SOURCE_PATH_SIZE`. In CMake everything is absolute path, but somehow the Scan analysis uses relative path for `__FILE__`:
This PR moves the `SOURCE_PATH_SIZE` into C++ using `constexpr` with bound checks. The `SOURCE_PATH_SIZE` is calculated at compile-time for every source file.
=> Safer method to determine source path length

.github/workflows/coverity-scan.yml
Now we are using C++ 17 and should need a newer builder image.
Last build failed because of `string_view` (added in C++ 17), built on Ubuntu 16.04:
```
Building CXX object CMakeFiles/ja2.dir/src/externalized/army/ArmyCompositionModel.cc.o
In file included from /home/runner/work/ja2-stracciatella/ja2-stracciatella/src/sgp/Debug.h:4:0,
from /home/runner/work/ja2-stracciatella/ja2-stracciatella/src/game/Strategic/Campaign_Types.h:4,
from /home/runner/work/ja2-stracciatella/ja2-stracciatella/src/externalized/army/ArmyCompositionModel.h:3,
from /home/runner/work/ja2-stracciatella/ja2-stracciatella/src/externalized/army/ArmyCompositionModel.cc:1:
/home/runner/work/ja2-stracciatella/ja2-stracciatella/src/sgp/Logger.h:6:23: fatal error: string_view: No such file or directory
compilation …
```
=> Fixing Coverity scan build

src/game/TileEngine/Overhead_Map.cc, src/game/TileEngine/WorldDef.cc, src/game/TileEngine/WorldDef.h
Resolves #1288. Thanks to @JRF-github for reporting and @selaux for the fix!
As mentioned in #1288, the bug was introduced in a previous tileset refactor and UB support work. The refactor only handled one of the cases. When a tileset filename is missing for a certain tileset, it can fall back to the corresponding entry in tileset `0`. 
However, it missed and actually broke the support for the other case. When the filename is defined in the tileset database (for example `17/a-sign4.sti`) but has no corresponding file for the overhead map (`17/t/a-sign4.sti`), we should fall back to the generic `0/t/grass.sti`.
The commit fixes the crash, and it should now match vanilla behaviour.
=> Fixing tileset files fallback logic

src/sgp/LoadSaveData.cc, src/sgp/LoadSaveData.h, src/sgp/LoadSaveData_unittest.cc
There are currently several reinterpret_casts from void* to uint8_t* in the DataReader and DataWriter classes, all of which can easily be avoided by declaring the member variables as uint8_t*.
I decided to change char[] to BYTE[], not uint8_t[] in LoadSaveData_unittest.cc because that's what all the users of DataReader and DataWriter currently use.
=> Remove reinterpret_casts in LoadSaveData.cc

assets/externalized/items.json, src/externalized/ItemModel.cc, src/externalized/JsonObject.h
I made an error in the serialization in #1295, that item class longer than 2 bytes were not serialized properly. This affected `IC_MISC`, `IC_MONEY`, `IC_KEY`.
=>  Fixing errors in items.json

src/game/Utils/Cinematics.cc
This code throws pointers to runtime_error and then tries to catch them by reference, which just doesn't work. Fortunately there errors are very unlikely to occur, otherwise the exceptions would be caught by the catchall in main() and the game be terminated.
=> Do not throw pointers to std::runtime_error in Cinematics.cc::SmkOpenFlic

src/game/Tactical/OppList.cc, src/game/Tactical/OppList.h, src/game/Utils/Event_Pump.cc, src/game/Utils/Event_Pump.h
After selaux's question in #1302 about `RemoveEvent` I had a closer look at the rest of the event pump code and found quite a bit of questionable logic. I am unsure whether any of these issues could cause actual problems in the game but since a more robust implementation isn't that hard and also more concise and more performant, why not?
Copy and paste of my commit message:
- `PeekEvent` and `RemoveEvent` were using try-catch blocks to return NULL in case they were called with an out-of-bounds-index but vector::operator[] does not throw an exception in that case.
- So, all null checks after `PeekEvent` and `RemoveEvent` were pointless.
- Removing all expired events in `DequeAllGameEvents` can be written more concisely and more performant with an STL algorithm.
- This eliminates the only …
=> Clean up the event queue management

.ci/ci-functions.sh
brew is complaining: `Error: Calling brew cask install is disabled! Use brew install [--cask] instead.`
=> Fix brew-install in Mac build

src/game/Tactical/Arms_Dealer_Init.cc
Fixes  #1309.
Bitwise-and operator returns `16384` in this case, and it does not convert well back to `BOOLEAN` (which is 8-bit char). Tested with Fredo and Arnie with the attached save.
=> Fixing incorrect item flags checks

src/game/Editor/Sector_Summary.cc, src/game/Tactical/Interface_Panels.cc, src/game/Tactical/Interface_Panels.h, src/game/Tactical/ShopKeeper_Interface.cc
The saved game from #1309 can be used to see this bug: give Fredo or Arnold something to repair and finish the transaction. The buttons that were disabled when you enter the interface stay disabled.
git bisect says this bug was introduced by 97e943d9b01692eb305f14e43f669223d312911b, so this bug is quite old and in the 0.17.0 release. Since that commit supposedly was needed to fix other bugs I took another approach to fix this one.
Btw., ShopKeeperInterface_SetSMpanelButtonsState isn't the prettiest function name I've ever written. Have your considered adding some namespaces?
=> Fix: Buttons stay disabled after leaving the shop keeper interface

src/game/Tactical/Turn_Based_Input.cc, src/game/TileEngine/WorldMan.cc, src/game/TileEngine/WorldMan.h
These two variables are only used by DebugLevelNodePage() and therefore it is not necessary to have them as globals. This also avoids constructing the string objects immediately and should help improving the startup time a tiny bit.
=> Move two debug-only global variables

src/game/TileEngine/Tile_Surface.cc, src/game/TileEngine/Tile_Surface.h, src/game/TileEngine/WorldDef.cc, src/game/TileEngine/WorldDef.h
Several locations made string copies where a reference could have been used instead.
The most egregious case is `LoadTileSurfaces(), which copies an array of 151 strings it does not even use. I was surprised what a difference ST_LITERAL makes, that change alone reduced the size of a release build by about 8 KB.
=> Avoid unnecessary string copies in Tile_Surface.cc and WorldDef.cc

src/game/SaveLoadGame.cc
This reduces the code size. In my case (Linux x64, GCC 9.3.0) the executable shrinks by about 3800 bytes.
=> Turn BAR macro in LoadSavedGame() into a lambda.

src/game/Tactical/Enemy_Soldier_Save.cc, src/game/Tactical/Keys.cc, src/game/Tactical/Tactical_Save.cc, src/game/Tactical/Tactical_Save.h, src/game/TileEngine/LightEffects.cc, src/game/TileEngine/SaveLoadMap.cc, src/game/TileEngine/SmokeEffects.cc
This function constructs a filename in an out char array. Since almost all of its users then pass that char array to functions taking ST::string it makes sense to construct a string directly.
This also fixes a format-overflow warning where GCC complains about the fact that we try to `sprintf()` a 512 char buffer into a 128 char buffer. It's not really a problem because the filenames cannot get that long but ironically the warnings generated are so huge they overflow my terminal window buffer.
=> Change signature of GetMapTempFileName()

dependencies/lib-smacker/libsmacker/smacker.c, src/game/Intro.cc
- Fix crash in libsmacker
- Change Intro.cc to continue with the next video after an invalid one
With this commit the Urban Chaos intro sequence plays as intended.
=> Address #1292 item 1: support Urban Chaos quasi-empty smacker files

src/game/Utils/Cursors.cc
Put the hot spot of CURSOR_WWW where you would expect it to be, at the top of the index finger.
Fixes #683
=> Fix the hot spot of the hand cursor

src/externalized/VanillaWeapons_unittests.cc, src/game/Tactical/Items.cc
Summary of these commits:
- Replace old school lookup with standard container methods
- Replace classic for loops with ranged-for
- Remove outdated comments, commented-out code, a pointless function and a duplicate entry in `AttachmentInfo`
- Add unit tests for `ValidLaunchable`, `GetLauncherFromLaunchable`, `GetLauncherFromLaunchable` and `CompatibleFaceItem`
- Remove code duplication in `g_attachments_mod`
=> Cleanup Items.cc a bit

src/game/Strategic/Quest_Debug_System.cc, src/game/Strategic/Strategic_Merc_Handler.cc, src/game/Tactical/Handle_Items.cc, src/game/Tactical/Interface.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/OppList.cc
Creating MercProfile object with invalid ID will result in an exception. This has caused problems in the QDS (and maybe some other places).
Resolves #1332.
=> Adding NO_PROFILE checks before creating MercProfile object

CMakeLists.txt, src/sgp/SGP.cc
Addresses #1257
Quoting [cppreference](https://en.cppreference.com/w/cpp/filesystem/temp_directory_path):
> On POSIX systems, the path may be the one specified in the environment variables TMPDIR, TMP, TEMP, TEMPDIR, and, if none of them are specified, the path "/tmp" is returned.
> 
> On Windows systems, the path is typically the one returned by GetTempPath
=> Create ja2.log in temp directory

.ci/ci-functions.sh, .ci/ci-setup.sh, CMakeLists.txt, src/launcher/main.cc
For #1257, see also https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1335#issuecomment-795058271.
We have changed log location of the main process. This updates the same for the `ja2-launcher`.
=> Create ja2-launcher.log in temp directory

android/app/build.gradle
com.github.noelchew:storage-chooser is a fork of the old dependency with a patch for Android 11 applied.
Closing #1348.
=> Fix directory chooser on Android 11

assets/externalized/game.json, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/game/SaveLoadGame.cc, src/game/Strategic/Campaign_Init.cc, src/game/Strategic/Game_Init.cc, src/game/Strategic/MapScreen.cc, src/game/Strategic/Map_Screen_Interface.cc, src/game/Strategic/Merc_Contract.cc, src/game/Strategic/Quests.h, src/game/Strategic/StrategicMap.cc, src/game/Tactical/Merc_Entering.cc, src/game/Tactical/Merc_Hiring.cc
This adds 2 new configuration in `game.json`. These only takes effect for new campaigns 
It may not make much sense on a vanilla campaign, and this is intended for full map mods. Mercs are arrives on heli at the designated sector, so the sector must also be outside of SAM site coverage.
=> Externalizing starting sector

.ci/ci-build.sh, .ci/ci-functions.sh, .ci/ci-setup.sh
For #1360.
The problem is that JA2:S, being a maintained runtime of an old video game, does not run on a relatively old Linux (Debian 10). The current CI build on GitHub Action uses Ubuntu 18:04 and gcc-9.
We do not have much choice over the build environment on GitHub Action. Ubuntu-16.04 is [scheduled to be decommissioned later this year](https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/), so the only reasonable choice now is Ubuntu-18.04.
If the build still doesn't work, we may need to do the build inside a docker container of an old-stable Debian or CentOS.
- Downgraded CI build to use `gcc-8` (on Ubuntu 18.04, GLIBC 2.27)
- Smoke test to run `./ja2 -help` on Debian 10
- `gcc` major version can be set via …
=> CI-build with gcc-8

CMakeLists.txt, cmake/target-download-editor-slf.cmake.in, rust/stracciatella/src/fs.rs, rust/stracciatella_c_api/src/c/fs/mod.rs, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/game/Editor/EditScreen.cc, src/game/Editor/Editor_Taskbar_Utils.cc, src/game/Editor/LoadScreen.cc, src/game/Editor/LoadScreen.h, src/game/Editor/Sector_Summary.cc, src/game/Editor/Sector_Summary.h, src/game/GameLoop.cc, src/game/Init.cc, src/game/Sys_Globals.cc, src/game/Sys_Globals.h, src/game/TileEngine/WorldDef.cc, src/game/TileEngine/WorldDef.h, src/sgp/FileMan.cc, src/sgp/FileMan.h
This is also part of #1275.
The main issue was that maps were always saved in the vanilla game directory. So for creating a mod you needed to always copy files back and forth between vanilla game dir and mods. At the same time listing all maps was broken, so no existing files were actually shown in the file list, leading to issues like #667.
For now I changed the editor load/save dialog to work on absolute paths. It is still possible to load a map from resources via the summary view in the editor, the save button in the summary view will now open the save dialog though.
- Navigation between folders is possible
- Start folder is the stracciatella home directory
Before:
After:
This also closes #667.
=> Better editor save load dialog

rust/stracciatella/src/vfs/mod.rs, rust/stracciatella_c_api/src/c/vfs.rs, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/game/GameRes.cc, src/game/GameRes.h, src/sgp/FileMan.cc, src/sgp/FileMan.h, src/sgp/FileMan_unittest.cc
Also a part of #1275. This reads tile cache files from VFS, not by listing the data directory directly.
=> Read tilecache names from VFS

assets/externalized/game.json, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/game/Tactical/Interface_Cursors.cc, src/game/Utils/Cursors.cc, src/sgp/Cursor_Control.cc, src/sgp/Cursor_Control.h, src/sgp/Video.h
Under certain circumstances, the mouse cursor is not rendered. Ie, when highlighting a tile for movement in real-time mode or hovering mouse cursor over a mercenary. It still behaves the same behind the scenes, so I feel it's nice to actually see the exact location of it at all times.
This adds a toggle ("always_show_cursor_in_tactical" in game.json) to make mouse cursor always be visible.
Examples of what the change looks like (with default JA2 behaviour, the cursor would be invisible in all of these samples):
I haven't done exhaustive testing of this, but based on the code changes, I think this is unlikely to cause any issues.
=> Added option for mouse cursor to always be visible in tactical view

src/game/TileEngine/Overhead_Map.cc, src/game/TileEngine/WorldDef.cc
My guess was right, they didn't get a chance to expire and the Reset* functions just clear some internal state.
fixes #95
=> make sure to expire break lights/smoke when trashing the area

rust/stracciatella/src/android.rs, rust/stracciatella/src/fs.rs, rust/stracciatella_c_api/Cargo.toml, rust/stracciatella_c_api/src/c/fs/tempdir.rs, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/DefaultContentManager_unittests.cc, src/game/Directories.h, src/game/Laptop/Files.cc, src/game/Laptop/Files.h, src/game/Laptop/Finances.cc, src/game/Laptop/Finances.h, src/game/Laptop/History.cc, src/game/Laptop/History.h, src/game/Laptop/Laptop.cc, src/game/SaveLoadGame.cc, src/game/Tactical/Enemy_Soldier_Save.cc, src/game/Tactical/Keys.cc, src/game/Tactical/Tactical_Save.cc, src/game/TileEngine/LightEffects.cc, src/game/TileEngine/SaveLoadMap.cc, src/game/TileEngine/SmokeEffects.cc, src/game/TileEngine/WorldDef.cc, src/game/TileEngine/WorldDef.h, src/sgp/SGP.cc
Split out of #1275. Closes #1255. Closes #135.
This changes temp file interaction logic to use a "proper" temporary directory in the OS-specified location of the temporary files. The temporary directory is unique per process, so multiple instances of the game can run in parallel. An example on linux would be `/tmp/ja2-stracciatella-hufmWU3N`. Some special handling needed to be introduced for Android where there is no temp dir, only an app specific cache dir, which is then used as temp dir.
All interactions with this temporary directory are now done through `ContentManager`. When the content manager deallocates, the temp directory is automatically removed. Some adaptions were necessary here to ensure that the `ContentManager` is always properly deallocated when exiting the game.
The whole …
=> Read and write to a proper temporary directory

assets/externalized/game.json, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/game/Tactical/DisplayCover.cc, src/game/Tactical/Handle_UI.cc, src/game/Tactical/UI_Cursors.cc, src/game/Tactical/Weapons.cc, src/game/Tactical/Weapons.h, src/game/Utils/Cursors.cc, src/game/Utils/Cursors.h, src/sgp/Video.cc, src/sgp/Video.h
Here's my work-in-progress implementation for showing chance-to-hit when aiming (this resolves https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1368).
Some notes:
- I'm using `st_format_printf("%d%%", uiHitChance)` to generate the string with the hit chance. I haven't looked into how st_format_printf works, but I noticed other code did something similar, so I figure and hope this is the way to go.
- gusMouseCursorHeight contains the size of the mouse image data. This isn't big enough to contain body location string and hit chance string. I ended up using a rather hacky solution (whenever the hit chance string is used, then a value gsMouseSizeYModifier is increased so that the mouse rendering routine include the hit chance string). Another solution I'm considering is when …
=> Show chance-to-hit next to mouse cursor

src/externalized/scripting/STStringHandler.h, src/externalized/scripting/ScriptingExtensionsLua.cc, src/game/Tactical/Enemy_Soldier_Save.cc, src/game/Utils/Observable.h
Fixes #1379.
Reinstitutes `RemoveTempFile`, which reads/sets sector flags when removing a map temp file.
Also fixes compilation with GCC 11. Due to header changes within the GCC standard library, some headers are less likely to be included by default. This caused an issue with sol which was missing the `<limits>` include. See "Header dependency changes" section in https://gcc.gnu.org/gcc-11/porting_to.html.
Also fixes a warning in `Observable.h`, which warned about an if that does (and should) not guard:
```
In file included from /home/stefan/workspace/ja2-stracciatella/src/game/Strategic/SAM_Sites.h:3,
from /home/stefan/workspace/ja2-stracciatella/src/game/Strategic/StrategicMap.h:6,
from /home/stefan/workspace/ja2-stracciatella/src/game/Strategic/Quests.h:6,
from …
```
=> Fix #1379: Read and reset sector flags when removing temp files

assets/distr-files-linux/ja2_manpage, rust/stracciatella/src/config/cli.rs, rust/stracciatella/src/config/engine_options.rs, rust/stracciatella_c_api/src/c/config.rs, src/launcher/Launcher.cc, src/sgp/Video.cc
During the investigation of #1382, I found that the ICC profile is reset when JA2 sets the brightness. 
The [SDL_SetWindowBrightness](https://wiki.libsdl.org/SDL_SetWindowBrightness) function adjusts gamma of the whole screen. On Windows it also resets the system's active color profile and undoes some other display options like those available on the NVIDIA Control Panel.
The launcher does not allow changing the brightness. Users may be better off adjusting the brightness at the device or OS / driver. The EngineOption of brightness defaults to 1.0, meaning no adjustment is requested (since #734):
```
-brightness GAMMA_VALUE
Screen brightness (gamma multiplier) value to set
where 0.0 is completely dark and 1.0 is normal
brightness. Default value is 1.0
```
Or, should we just remove the …
=> Do not adjust screen brightness unless requested

assets/externalized/vehicles.json, src/externalized/CMakeLists.txt, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/VehicleModel.cc, src/externalized/VehicleModel.h, src/game/Strategic/Campaign_Types.h, src/game/Tactical/Vehicles.cc, src/game/Tactical/Vehicles.h
For #665. This externalizes the table data of [g_vehicle_type_info](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/e23678b74af7e7fa2ccaf067eb44993184af0a33/src/game/Tactical/Vehicles.cc#L68) into JSON and model class. 
- Change the number of seats, to fit in more soldiers
- Change the movement type, so the vehicle can traverse more terrains types other than roads (e.g. plains).
- Change the armour type, to make it tougher or easier to destroy
- Adding new vehicles or re-ordering elements is likely not to work without code support
- `class VehicleModel` is a direct replacement of the old `struct VehicleTypeInfo`
- The helicopter does not seem to use the `enterSound` or `moveSound`
- Adding the `Eldorado` might work if it is also placed in a sector. I haven't tried.
=> Externalize vehicles

assets/mods/generous-rebels/data/scripts/main.lua, src/externalized/scripting/FunctionsLibrary.h, src/externalized/scripting/ScriptingExtensions.h, src/externalized/scripting/ScriptingExtensionsLua.cc
A bit of cleanup in the scripting area:
- Require the use of `require` function instead of custom `JA2Require`
- Errors that happen when `main.lua` is executed are catched correctly
=> Use require function instead of custom require

src/game/Tactical/Interface_Panels.cc, src/game/Tactical/Interface_Panels.h, src/game/UILayout.cc, src/game/UILayout.h
To dynamically draw the bottom bar panels, to support different squad sizes.
When squad size is 6 or below it is same as before. When the squad size is 7 or above, we will "assemble" the panel with multiple blits at init. Below shows the panels for squads of 8:
Squad size externalization is yet to be implemented. For now you can only do it with a custom build from source with a changed `NUMBER_OF_SOLDIERS_PER_SQUAD` (and that will break save game too).
Squad size of `n` requires horizontal resolution of `640 + (n - 6) * 83`. Squad size of 8 requires screen width of at least 806 px.
If the screen is not wide enough to show all squad slots, the last few mercs will not have a slot in the team panel. The merc can only be selected with mouse click in tactical, but works otherwise normally. The …
=> Dynamic tactical bottom bar

src/game/Tactical/Squads.cc
Found a bug with the `sDeadMercs` logic when I was experimenting with squad sizes. This should be a minor regression from vanilla.
The bug was introduced in https://github.com/ja2-stracciatella/ja2-stracciatella/commit/71c563428ea8ebb19053faa52ee38ffe6caccfeb. When someone on squad is killed, the same profile ID is added to all of the slots in the `sDeadMercs` list, so the subsequent deaths on squad cannot be added to the `sDeadMercs` list. 
Most of the soldier death logic is not affected. The skull animation is triggered. But after the death sequence is finished, leaving the tactical screen (switching to strategic or saving), the later-dead soldiers would be silently removed from squad.
=> Allow more than 1 dead mercs on squad

src/game/Strategic/Merc_Contract.cc
Broken since 1cd87b6770df7ef318be19ac293e150629306e73. I got full refund even Gus has lost half his health. Feels like cheating.
The formula should give a partial amount depending on the health left when the merc leaves.
The original formula: 
```c++
iRefundAmount = (INT32) ( ( pSoldier->bLife / ( FLOAT ) pSoldier->bLifeMax ) * pSoldier->usMedicalDeposit + 0.5 );
```
=> Refund the correct amount of medical deposit

src/game/SaveLoadGame.cc, src/game/Tactical/Squads.cc, src/game/Tactical/Squads.h
This is a proposal to update the Squad save format, to allow squad sizes other than 6 in the save and to allow loading saves done with different squad sizes. It retains some compatibility to all old versions down to 1.12 vanilla.
In the current (old) save format, squad size is always 6. The full squads list is a simple list of 120 (20 squads * 6) slots, each containing one `pSoldier->ubID` followed by 10 bytes of unused space.
To support dynamic squad sizes, we store also the squad ID with each slot in the unused space, instead of assuming fixed-size lists.
At squad size of 6 or lower, the data layout is unchanged, and so it is fully compatible with all previous versions; At higher squad sizes, there are not enough space in the data region to store all unused the squad slots.
For …
=> Change the squad save format

src/game/Tactical/Soldier_Control.cc
Fixes #1367. 
This is a logic error introduced in #1325([diff](https://github.com/ja2-stracciatella/ja2-stracciatella/pull/1325/files#diff-5c7a7fd92593a4c65764acb3fec8e25342b7d717db783924d012b1761cf8f9baR7464)), the original condition to unlock the UI (`UnSetUIBusy`) checks for:
```c++
pSoldier->pTempObject == NULL
```
And `fIsThrowing` is defined as:
https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c75a2773eb1905c82111b9bb294ca7ecf5fb5bb0/src/game/Tactical/Soldier_Control.cc#L7383
=> Fix UI locking up when item is spotted during movement

src/game/Tactical/Interface_Items.cc
Fixes #1336. The bug has been there since the initial import.
=> Display the correct amount for ammos in pop-up

src/game/Tactical/LOS.cc
Fixes #1365. 
Adds a NULL check, and skips the `usShotsHit++` if the current `pFirer` does not have a target. In this case the firing soldier is not aiming at people but at grids, and the `tgt` just happens to be standing there.
=> Add NULL check when counting shots hit

src/game/Editor/LoadScreen.cc, src/game/Editor/Sector_Summary.cc, src/game/JAScreens.cc, src/game/Laptop/Laptop.cc, src/game/SaveLoadGame.cc, src/game/Strategic/MapScreen.cc, src/game/Strategic/Map_Screen_Interface.cc, src/game/Strategic/Map_Screen_Interface_Bottom.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Map_Screen_Interface_Map_Inventory.cc, src/game/Tactical/Overhead.cc, src/game/Utils/Timer_Control.cc, src/game/Utils/Timer_Control.h
This is a find-and-replace update to ensure we use `UINT32` variables to handle clock time. I searched for keywords including `GetJA2Clock` and `timer`, and replaced the usage of `INT32` if it is not appropriate.
None of the variables are persisted in saves, so it is safe to change the variable type.
Related to #1386.
=> Use UINT32 to handle GetJA2Clock time

src/game/Strategic/Strategic_AI.cc
As mentioned in #1419, there are some regression in Strategic AI behaviour since 0.17.0. It is caused by underflow of unsigned integers.
- Variables dealing with group weights are changed back to signed (`INT32`)
- Renamed some variables to be consistent with the type, so it is easier to spot similar issues going forward
- Reverted a change (`UINT32` back to `INT32`)in LoadStrategicAI. This does not seems to have caused any problems, but it is an implicit cast from unsigned to signed. It might have an effect if we have platforms of different endianness.
=> Fixing signedness errors in Strategic AI

assets/externalized/strategic-ai-policy.json, src/externalized/policy/DefaultStrategicAIPolicy.cc, src/externalized/policy/StrategicAIPolicy.h, src/game/Strategic/Strategic_AI.cc
The second issue in #1419.
The vanilla Strategic AI seems not replacing a totally defeated patrol group. It is able to reinforce if the group has some of the soldiers killed but the group is still active. But if the group is destroyed, it will never get replaced.
Here we have a new option `refill_defeated_patrol_groups` in the Strategic AI policy. I set it to disabled by default for consistency with vanilla, though I would personally always play with it enabled.
=> Option to refill totally defeated patrol groups

src/game/Tactical/Interface_Control.cc
Bug since #1404, reported on Discord. 
Using widescreen resolution, in the far-left side in the tactical UI, the UI overlay elements (cursors, soldier names, etc) are not properly drawn and cleaned, causing artifacts on screen.
The problem is in Interface_Control.cc, which handles the UI overlay elements. It uses clipping to prevent drawing elements over of the bottom bar. The bottom bar was moved to the center, but the clipping rectangle uses `INTERFACE_START_X` which I think is wrong.
`INTERFACE_START_X` is now used as the "leftmost X-position of the tactical bottom bar". It used to be zero as everything had been aligned to the left. 
`gsVIEWPORT_START_X` is the correct one to use. The value is currently always zero, because the tactical viewport takes the entire screen width.
=> Fix UI overlay glitches in tactical UI

COMPILATION.md, rust/stracciatella_c_api/src/c/vfs.rs, src/sgp/SGP.cc
Closes #1433.
Fixes error message being truncated on unhandled exception (`SLOGE` truncates to 256 characters).
Also makes the specific error message in #1433 shorter (does not include the whole EngineOptions struct anymore, the error message itself is specific enough: `Error initializing VFS for "/data/data_gold2/data": No such file or directory (os error 2) (St13runtime_error)`).
Adds a line about creating an installable linux build to `COMPILATION.md`
=> Fix truncated error message

src/game/Strategic/MapScreen.cc
Normally the map inventory screen only highlights compatibles when hovering on an item that is in the map inventory, showing compatibles in the map and on the current merc.
This patch makes it so that hovering over a merc item shows compatibles in the map inventory as well.
=> Highlight compatible items in sector inventory

src/game/TileEngine/Overhead_Map.cc
Clicking the overhead map was broken and often ended up in strange places. This should fix it.
=> Fix camera focus when clicking on overhead map

src/game/GameScreen.cc, src/game/TileEngine/RenderWorld.cc
This seems to fix the bad glitches during camera scrolling while mercs are moving and the "merc lights during movement" option is enabled.
It's kind of a workaround-y way to do it i guess, until a better fix comes along.
Related issues : #551
=> Fix graphical glitching during scrolling when merc lights are enabled

.ci/ci-functions.sh, .ci/upload-artifact.sh
This should fix google-cloud-sdk on AppVeyor, where Python 3.10 is now installed, which is not supported by the google cloud SDK version we use.
See: https://issuetracker.google.com/issues/202172882
Edit: Well it seems that the latest version does not support Python 3.10 either. So I pinned the version to 3.9...
NB: The MingGW issue seems to be caused by updated CMake (3.22.0).
=> Update google sdk on AppVeyor for Python 3.10 compatibility

.ci/ci-setup.sh
The GitHub Action ubuntu image always [installs](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/cmake.sh) the latest CMake release, but the MinGW packaging target fails since CMake 3.22. Check #1451 for details.   
This is a temporary work-around and should fix the builds for now.  If CMake can address this problem in a future release, we should revert changes in this PR.
=> Install CMake 3.21 for MinGW builds

src/launcher/Launcher.cc
Fix for the below build error:
```
Consolidate compiler generated dependencies of target ja2-launcher
Building CXX object CMakeFiles/ja2-launcher.dir/src/launcher/Launcher.cc.o
/home/aleh/downloads/build/ja2-stracciatella-git/src/ja2-stracciatella/src/launcher/Launcher.cc: In member function ‘void Launcher::startExecutable(bool)’:
/home/aleh/downloads/build/ja2-stracciatella-git/src/ja2-stracciatella/src/launcher/Launcher.cc:333:25: error: format not a string literal and no format arguments [-Werror=format-security]
333 |                 fl_alert(message.c_str());
|                 ~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [CMakeFiles/ja2-launcher.dir/build.make:146: CMakeFiles/ja2-launcher.dir/src/launcher/Launcher.cc.o] Error 1
make[1]: *** …
```
=> Bugfix for Launcher build format-security error

src/game/Strategic/Town_Militia.cc
Training militia in a city that is already full of green militia in every sector causes a crash. Fixed by an extra check on the index value.
```
2022-01-09T13:27:29 [INFO] game/GameLoop.cc: Version Label: Stracciatella v0.19.0-git+72eeb77c7
2022-01-09T13:27:29 [INFO] game/GameLoop.cc: Version #:     Build 04.12.02
2022-01-09T13:27:51 [WARN] game/Tactical/Tactical_Save.cc: SynchronizeItemTempFile() Reported 0, should be 24
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = TownSectorInfo; _Alloc = std::allocator<TownSectorInfo>; std::vector<_Tp, _Alloc>::reference = TownSectorInfo&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' …
```
=> Bugfix: training militia in a city already full of militia

.ci/ci-setup.sh
This reverts commit c1165e0d63e73285b849cd98ab07c26137cf307f.
Resolves #1451. The MinGW build should work again since [v3.22.2](https://github.com/Kitware/CMake/releases/tag/v3.22.2). The workaround introduced in #1455 is no longer needed.
=> Revert "Install CMake 3.21 for MinGW builds"

src/game/Tactical/OppList.cc
Closes #1463.
I decided to remove the condition completely as later `ubSourceTerrType` is compared against `FLAT_FLOOR` anyways, so the condition does not really need `bCheckTerrain`, to know whether it has to check for the terrain.
=> Remove condition for checking terrain

src/game/Tactical/OppList.cc
I think this code path got introduced when fixing the non-expiring breaklights and gasses.
=> AllTeamsLookForAll: skip misplaced soldiers, #1387

src/game/Tactical/Interface_Items.cc
fixes #1397
Co-authored-by: Seven <sevenfm@gmail.com>
=> HandleItemPointerClick: target grenade throws at the correct tile level

rust/Cargo.lock
The goal is to get the new version 0.2.1 for json-comments which fixes multiple subsequent asterisks in json comments
(https://github.com/tmccombs/json-comments-rs/pull/9).
=> Update rust lockfile

src/game/Utils/_GermanText.cc
This concatenated the two translation strings instead of defining them separately. Fixes bug mentioned in https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1356
=> Fix german translation on saveload screen

src/game/Tactical/Squads.cc
Fixes #1512 and #1476.
The game crashes during squad assignment, when `iCurrentTacticalSquad` has the value of `NO_CURRENT_SQUAD (20)`. The code attempts to check the squad slots of `Squad[20]`, which is out of bounds. Debug build seems to be protected from this crash.
At the crash, there is a squad selected in the UI (the red arrow(s) next to mercs). But other than this crash, I see no issues in squad assignment. The `AddCharacterToSquad` function has not be changed for more than 10 years, but the crash was never reported in previous releases. It might be a side-effect of #1415.
Adding an assertion in the squad empty check, so should there are similar crashes the logs would have more information.
=> Do not check for empty squad if none is selected

src/game/SaveLoadScreen.cc
This should address the issues in the save load screen mentioned in #1508.
- No crashes anymore when deleting / saving without having a save game slot selected
- Make save button work while entering text in new save game
=> Fix save load screen issues

.ci/ci-build.sh, .ci/ci-functions.sh, .ci/ci-setup.sh, .github/workflows/github-ci.yml, android/app/build.gradle
I added some secrets to the CI to provide a keystore for Android builds, so they always have the same signature. Should close #1503.
I also switched to release builds in the CI, as it seemed simpler to use different signing mechanisms for debug/release so local development with debug builds is still easily possible.
I still have to test the resulting builds.
=> Build signed release APKs instead of debug APKs for Android

src/game/Strategic/Map_Screen_Interface_Bottom.cc
This went unnoticed for quite some time :laughing: 
Closes #1517.
=> Fix missing offset for start/stop time mouse region

.mailmap, cmake/target-rebuild-contributors-list.cmake.in, contributors.txt
- simplifies the code by letting git deduplicate and removing legacy logic
- handles coauthorship (why Seven was uncaught in 0.19)
- minor cleanup afterwards
=> cmake: rewrite the contributor tracking target

rust/Cargo.lock, rust/stracciatella/Cargo.toml, rust/stracciatella/src/android.rs
The SDL2 update seems to allow this now. Last part of https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1248.
Closes #1248.
=> Get rid of ndk fork in rust dependencies

appveyor.yml
It seems like otherwise the builds for `0.19.1` are not triggered on AppVeyor. I hope this fixes it. We can remove it once `0.20.0` is released.
=> Add 0.19.x to branch filter for appveyor

rust/stracciatella/src/fs.rs
This EXDEV error can happen on all Unix-like OS's that have a rename(2) that
conform to POSIX.1. So, go with the more inclusive "target_family"
instead of target_os.
Makes JA2 work with FreeBSD (and likely all the other OS's that may have their
tmp on another file system).
This is the more general fix to #1478.
=> Handle the EXDEV error on all OS's where it can happen

dependencies/lib-miniaudio/getter/CMakeLists.txt.in, src/sgp/SoundMan.cc
In general I'd like to have an ability to pick up miniaudio dependency from the system during ja2 build process.
See also https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1377
And the first step I'd like to be done is to update the needed miniaudio version to latest in 0.10.x branch (0.11.x has broken a lot of APIs).
Besides that provide a comment in the cmake file telling what miniaudio version ja2 needs now.
Also provide small patch to make ja2 compatible with miniaudio 0.10.36+
=> Upgrade miniaudio dependency to latest version in 0.10.x branch

.ci/ci-build.sh
External contibutors CI runs dont have access to secrets, so we need to build a debug android build for those cases, as the signing keys will not be present for release builds.
=> Fix Android CI build for external contributors

CMakeLists.txt, rust/stracciatella/src/logger.rs, rust/stracciatella_c_api/cbindgen.toml, rust/stracciatella_c_api/src/c/logger.rs, rust/stracciatella_c_api/src/c/misc.rs, rust/stracciatella_c_api/src/c/mod.rs, rust/stracciatella_c_api/src/c/subprocess.rs, src/launcher/Launcher.cc, src/launcher/Launcher.h, src/launcher/StracciatellaLauncher.cc, src/launcher/StracciatellaLauncher.fl, src/launcher/StracciatellaLauncher.h, src/launcher/main.cc, src/sgp/SGP.cc
This PR changes the way the launcher runs the game itself.
Previously it was blocking the whole time while the game was running.
With this PR the game subprocess is started in a non-blocking way and is polled each second to determine whether it has finished. When the game subprocess has finished, the resulting logs are displayed in a new tab in the launcher. If an error occured the active tab is automatically switched to the "Logs" tab, so the user might be able to determine the reason for the crash. While the game is running the reachable buttons/tabs in the launcher are disabled.
Closes #1507 
New Logs Tab:
Disabled state while game is running:
New error message after running game:
=> Run game without blocking the launcher and add logs as a launcher tab

src/sgp/SoundMan.cc
The newer version of miniaudio we introduced seems to [return MA_AT_END](https://github.com/mackron/miniaudio/commit/9be681b84829d0247ea00dd23db22c95d71b56aa) when the ringbuffer is fully read. This PR fixes the annoying log when a sound has finished:
> 2022-05-20T09:44:25 [ERROR] sgp/SoundMan.cc: Could not commit read pointer for channel 1: At end
Functionally there should be no differences.
=> Fix error messages when commiting read pointer in sound system

src/game/Tactical/DisplayCover.cc
bPercentCoverForGridno was set up in such a way that the minimum between 0 and 100 - iTemp could be a negative number, causing the assertion errors mentioned in #1548
=> Fix bPercentCoverForGridno values going out of 0-100 bound

src/game/Editor/SelectWin.cc, src/game/Strategic/Meanwhile.cc, src/game/Utils/WordWrap.cc
The unused variable in WordWrap.cc is currently one of two warnings I get while building apart from the deprecated declarations. The other one is in miniaudio.
SelectWin.cc stores 16-bit values in an array of 32-bit integers for no good reason.
LocateMeanWhileGrid is used just once and does nothing but call another function.
=> Small cleanups

rust/Cargo.lock, rust/stracciatella/Cargo.toml, rust/stracciatella/src/file_formats/mod.rs, rust/stracciatella/src/file_formats/stci/color.rs, rust/stracciatella/src/file_formats/stci/etrle.rs, rust/stracciatella/src/file_formats/stci/indexed.rs, rust/stracciatella/src/file_formats/stci/mod.rs, rust/stracciatella/src/file_formats/stci/rgb.rs
I've had this code lying around a bit and don't want to let it go to waste. It adds support for reading and writing STCI files in Rust.
If you have concerns regarding compile times (as the code is currently not used by the engine) let me know. I can adapt it to not compile by default, only if explicitly enabled.
=> Add read/write functionality for STCI to rust

src/game/Tactical/Keys.cc, src/game/Tactical/Keys.h, src/game/Tactical/LOS.cc
Small behaviour change, previously you got the 'Lock destroyed' message only when you shot the lock. Now it's displayed when you blow the lock with an explosive, too.
=> Fix #1538 Possible INT8 overflow in bLockDamage

src/game/Tactical/Interface_Items.cc, src/game/Tactical/Interface_Panels.cc, src/game/Tactical/Items.cc, src/game/Tactical/Items.h, src/game/Tactical/Keys.cc, src/game/Tactical/Soldier_Control.cc, src/game/Tactical/Soldier_Control.h
Cleans up a bit of copy & paste coding, removes the function `RemoveKeyFromSlot` and uses the generic `RemoveKeysFromSlot` instead. 
Adds a simple method to make the key ring slot checks easier to read.
=> Cleanup KEY_ON_RING related code

src/game/SaveLoadGame.cc
This should fix the locally failing unittest. The condition didn't simply check if the sector is invalid before, but compared it to the values that should be set when no sector has been visited yet. Still not sure why it does not fail in CI though...
=> Restore the save game validity condition from before sector refactoring

src/game/Tactical/Soldier_Control.cc, src/game/TacticalAI/AIUtils.cc, src/game/TileEngine/Isometric_Utils.cc, src/game/TileEngine/Isometric_Utils.h
This function is an abomination. It has one really simple job but manages to make a complete mess out of it: its far too complicated algorithm produces the wrong result for 56 out of the 64 possible combinations of its arguments.
It even has a safeguard against its own brokenness which is itself really silly: why would you abort the algorithm at 101 when you know perfectly well that the greatest possible result is 4?
Luckily, the three users of this function do not care that much, as long as `FindNumTurnsBetweenDirs` is consistently wrong they're happy.
=> Fix FindNumTurnsBetweenDirs

src/game/Tactical/Animation_Cache.cc, src/game/Tactical/Animation_Cache.h, src/game/Tactical/Animation_Control.cc, src/game/Tactical/Soldier_Control.cc
• Do not dynamically allocated 6 byte arrays and then use an 8 byte pointer
to store their addresses.
• Convert the free functions to class methods.
• Don't let functions other than init pass in the soldier's profile id
because the AnimCache and the profile id must come from the same soldier.
• The cache size was not helpful
=> Overhaul Animation_Cache

src/game/Tactical/Soldier_Control.cc
The current one is not that great, to put it mildly. It looks like the author couldn't quite figure out the math (that is the commented out version), so he chose brute force and used eight `if` statements.
Three of the eight if blocks are missing the `break` statement so we are doing unnecessary comparisons after we already have the correct result.
x and y are swapped in the atan2 call so the ranges look weird, north is where east should be, etc.
Finally, all these instances of 0.623 should be 0.625.
Due to the last bug, this implementation does not always return the same result. I wrote a short test program to compare the results of the two functions and the output is exactly what I expected:
> 201850880 comparisons, 392136 different.
So in 0.2% of all cases the result differs. I doubt …
=> New implementation of atan8

src/externalized/strategic/UndergroundSectorModel.cc, src/game/Strategic/Auto_Resolve.cc, src/game/Strategic/Creature_Spreading.cc, src/game/Strategic/Game_Init.cc, src/game/Strategic/Map_Screen_Interface.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Queen_Command.cc, src/game/Strategic/SAM_Sites.cc, src/game/Strategic/StrategicMap.cc, src/game/Strategic/Strategic_AI.cc, src/game/Strategic/Strategic_Movement.cc, src/game/Tactical/Morale.cc, src/game/Tactical/Tactical_Save.cc, src/game/TacticalAI/Knowledge.cc, src/game/TileEngine/Map_Edgepoints.cc, src/game/Utils/_ChineseText.cc, src/game/Utils/_DutchText.cc, src/game/Utils/_EnglishText.cc, src/game/Utils/_FrenchText.cc, src/game/Utils/_GermanText.cc, src/game/Utils/_ItalianText.cc, src/game/Utils/_PolishText.cc, src/game/Utils/_RussianText.cc, src/sgp/Types.cc, src/sgp/Types.h
First commit fixes three invalid format strings for `SLOGD` and introduces `SGPSector` support for `ST::format`. Search for `{}{}` to find the replaced cases.
Second commit fixes invalid format strings in translations.
Should close https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1569. I hope that these are all remaining cases...
=> Fix some remaining invalid format strings for sectors

src/game/SaveLoadGame.cc, src/game/Tactical/Interface_Panels.cc, src/game/Tactical/Items.cc, src/game/Tactical/LoadSaveSoldierType.cc, src/game/Tactical/Soldier_Control.h, src/game/Tactical/Weapons.cc, src/game/Tactical/Weapons.h
Ensure that SOLDIERTYPE::bWeaponMode and bDoBurst are sensible after
changing the soldier's hand item. Resolves #196.
This also partly fixes #1184:
- You can't crash the game any more by switching from a weapon with burst mode to another item and then throwing something.
- The problem that a throw attempt can turn into a burst if burst mode is enabled still exists.
=> Keep hand item and weapon mode in sync

src/game/TileEngine/LightEffects.cc, src/game/TileEngine/LightEffects.h, src/game/TileEngine/SmokeEffects.cc, src/game/TileEngine/SmokeEffects.h, src/game/TileEngine/WorldDef.cc
Let the callers of these functions call AllTeamsLookForAll themselves when
they need to.
=> Do no update sight values in DecaySmokeEffects and DecayLightEffects

src/game/Strategic/MapScreen.cc, src/game/Strategic/Map_Screen_Interface_Bottom.cc, src/game/TileEngine/Render_Dirty.cc, src/game/TileEngine/Render_Dirty.h, src/sgp/Button_System.h, src/sgp/MouseSystem.cc, src/sgp/MouseSystem.h
• Several locations in Map_Screen_Interface_Bottom.cc were testing the wrong uiFlags.
• MSYS_RemoveRegion was testing a different flag than four other locations before
calling FreeBackgroundRectPending.
The first bug (testing `GUI_BUTTON`'s uiFlags instead of `MOUSE_REGION`'s) seems harmless, we either redraw too often or miss one redraw, I didn't notice any display errors.
The second bug, however is more serious: there are five places in `MouseSystem.cc` that call `FreeBackgroundRectPending`, four of them tested the `MSYS_GOT_BACKGROUND` flag before and cleared this flag afterwards.
Only MSYS_RemoveRegion used `MSYS_HAS_BACKRECT` instead, which could theoretically lead to a second `FreeBackgroundRectPending` call for this `BACKGROUND_SAVE`. Worst case scenario would be that this …
=> Fix fast help active checks

src/game/Tactical/LOS.cc, src/game/Tactical/Weapons.cc, src/game/Tactical/Weapons.h, src/game/TileEngine/Structure.cc
• Due to some fishy calculations in BulletHitStructure(), StructureHit()
occasionally ended up with the wrong GridNo.
• Two places used 0 instead of INVALID_STRUCTURE_ID
I checked the other code locations that use BULLET's qCurrX, Y, Z but could not find any other place that also add 0.5 to these values.
I can only assume that this is not intentional but an actual bug, but it would be good to get more testing, that's why I changed the warning to an assert: it makes it less easy to ignore any remaining issues, if there are any.
=> Fix Structure not defined warnings

rust/stracciatella/src/schemas/yaml/tactical-map-item-replacements.schema.yaml, rust/stracciatella/src/schemas/yaml/weapons.schema.yaml
- Weapons ids are item ids and should be uint16 (although they can only go from 0 - 70)
- Some weapon sound properties were missing their type
- Item ids should be uint16 for tactical item replacements
=> Fix incorrect schemas for weapons and item replacements

CMakeLists.txt, dependencies/lib-lua/CMakeLists.txt, dependencies/lib-miniaudio/CMakeLists.txt, dependencies/lib-sol2/CMakeLists.txt
These are needed for the OpenBSD package. Other systems will probably want them too to avoid embedded dependencies, FreeBSD for instance patched the source locally: https://cgit.freebsd.org/ports/tree/games/jaggedalliance2/files?id=a50372b91f2b327f3bc400d088e21f4b18c2a112
=> Merge cherry-picked build fixes into 0.19.x

src/game/GameLoop.cc
This is currently preventing the game from properly reporting errors (see for example 1589), instead of
> Game has been terminated due to an unrecoverable error: ...
we're getting 
> terminate called after throwing an instance of 'ST::unicode_error'
what():  Invalid UTF-8 sequence byte
=> Do not use the c_str() result of an already destroyed ST::string

dependencies/lib-miniaudio/CMakeLists.txt, dependencies/lib-miniaudio/getter/CMakeLists.txt.in, src/sgp/SoundMan.cc
Somewhere between versions 0.10.20 and 0.10.43, miniaudio changed the
type of the ma_decoder_seek_proc function type's 2nd parameter from int
to ma_int64. That's an ABI breakage warranting a major version bump, but
the project only bumped the patch version.
The latest Stracciatella master already runs on the latest miniaudio
version which is 0.11.9, but Stracciatella 0.19.x needs to update to
0.10.43 because package maintainers will try to package the latest
0.10.x miniaudio to satisfy the dependency and that causes a compile
error.
=> [0.19.x] update miniaudio to 0.10.43

src/sgp/Debug.h
Using Assert and AssertMsg can lead coverity scans to assume that the condition
we asserted could be false. For example
Assert(ptr); if (ptr->something == 0) ....
could create a defect report.
If this works as well as I hope it does, it should eliminate reduce the number of open defects quite a bit.
=> Try to avoid false positives from coverity scans

src/externalized/scripting/FunctionsLibrary.cc, src/externalized/scripting/FunctionsLibrary.h, src/externalized/scripting/ScriptingExtensions.h, src/externalized/scripting/ScriptingExtensionsLua.cc, src/game/Tactical/Arms_Dealer_Init.cc, src/game/Tactical/ShopKeeper_Interface.cc, src/sgp/Types.h
- Adding a couple of observables so mods can update dealers items and prices
- Exposing a few functions to manipulate shop keeper behaviour and their inventories
- Added support for passing UINT32 values to and from Lua
These should do nothing on its own, but allow Lua scripts to override items and prices. They allow mod support for things like Unfinished Business ([PATCH132](https://github.com/ja2-derek/ja2-ub-comparison/commit/70809a14)), and also #1205.
```lua
RegisterListener("OnDealerInventoryUpdated", "adjust_franz_inventory")
ARMS_DEALER_FRANZ = 2
-- Check every morning, and ensure Franz has a VideoCam to sell if the robot quest is started
function adjust_franz_inventory()
if gubQuest[Quests.QUEST_DELIVER_VIDEO_CAMERA] == QuestStatuses.QUESTINPROGRESS then …
```
=> Add integration points to change shop inventories and prices

src/externalized/scripting/FunctionsLibrary.cc, src/externalized/scripting/FunctionsLibrary.h, src/externalized/scripting/ScriptingExtensionsLua.cc, src/game/Tactical/Dialogue_Control.cc
Exposes 2 functions to Lua, so mods can create message pop-ups. See also #1205.
- DoBasicMessageBox - based on [DoScreenIndependantMessageBox](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/e23678b74af7e7fa2ccaf067eb44993184af0a33/src/game/MessageBoxScreen.cc#L589)
- [ExecuteTacticalTextBox](https://github.com/ja2-stracciatella/ja2-stracciatella/blob/c3d48e93b9e6c4509ff5d9816594b50243504c75/src/game/Tactical/Dialogue_Control.cc#L952)
----
=> Functions to make message boxes in Lua

src/game/TileEngine/Buildings.cc, src/game/TileEngine/WorldDef.cc
The `GenerateBuildings()` call was deleted by mistake in a previous commit.
I wondered why the soldiers weren't following me onto the roof right next to helicopter drop off zone any more.
=> Let enemy soldiers climb onto roofs again

src/coverity_model.cpp, src/sgp/Debug.h
Let's see, two days until the next coverity run.
std::unique_ptr has operator bool, but the compiler didn't find it sufficient, hence the `get()` chunk.
=> Debug: another attempt at avoiding asserting coverity reports

.github/workflows/coverity-scan.yml
Continuation of trying to get Assert* false positives to vanish.
In the meanwhile I played with various models, for example trying to manually provide the one function needed from the templating of LogMessageST, toyed with other ideas, but this is the simplest next attempt — just don't ifdef the assert out for coverity, since it's not analyzing a debug build.
=> coverity: enable asserts

src/game/Strategic/Auto_Resolve.cc, src/game/Tactical/Animation_Cache.cc, src/game/Tactical/Animation_Cache.h, src/game/Tactical/Soldier_Create.cc
Make it crystal clear that we're not freeing one of the soldiers from the Menptr
array. Also fix the (harmless) warnings caused by #1571.
CID 275310
About these warnings: the AR soldiers aren't fully initialized but `DeleteSoldier()` doesn't know about that and tries to free the animation cache. That makes `UnLoadAnimationSurface()` unhappy and causes it to print one warning for every AR soldier. Ugly. Now every AnimationCache is always in a valid state, no matter where the outer SOLDIERTYPE was created.
And `ProfileID` is used for Merc Profiles, not soldier ids.
=> Let Auto Resolve free the soldiers created for it

src/game/Tactical/OppList.cc, src/game/Utils/Debug_Pages.cc, src/game/Utils/Debug_Pages.h
Print the actual debug strings, not their addresses.
Before:
After:
.
=> Fix display of the debug pages

src/game/Strategic/Scheduling.cc, src/game/TacticalAI/AI.h, src/game/TacticalAI/FindLocations.cc
Fixes #1631
To compare the result of the old and the new code I added some SLOGI statements to print the result of `FindNearestEdgePoint`.
This is the testcase in #1631 with the current code:
> 2022-08-04T07:51:54 [INFO] game/TacticalAI/FindLocations.cc: FNE: 7406
2022-08-04T07:51:54 [INFO] game/TacticalAI/FindLocations.cc: FNE: 7724
2022-08-04T07:51:54 [INFO] game/TacticalAI/FindLocations.cc: FNE: 6929
2022-08-04T07:51:54 [INFO] game/TacticalAI/FindLocations.cc: FNE: 25601
2022-08-04T07:51:54 [ERROR] game/Tactical/PathAI.cc: Trying to calculate path from off-world gridno 25601 to 25601
2022-08-04T07:51:54 [INFO] game/TacticalAI/FindLocations.cc: FNE: 25601
2022-08-04T07:51:54 [ERROR] game/Tactical/PathAI.cc: Trying to calculate path from off-world gridno 25601 to 25601 …
=> Let FindNearestEdgePoint try harder to find a suitable gridno

src/game/SaveLoadGame.cc, src/game/SaveLoadGame_unittest.cc, src/game/Strategic/Quests.cc, src/game/Strategic/Strategic_Event_Handler.cc, src/game/Strategic/Strategic_Movement.cc, src/game/Tactical/Handle_Items.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/ShopKeeper_Interface.cc
• Wrong index used into soldier's inventory (CID 249130)
• Buffer overrun in SaveLoadGame unit test (215865)
• harden logic in a workaround for a potential problem in ancient saves (250860)
• Coverity does know that Random(10) can only return 0-9 (81654)
• Safer array access in CheckFact (254706)
• Remove special SKI handling in InitItemDescriptionBox (249140)
• Write after free in HandleNonCombatGroupArrival (209947)
Two real bugs in the game (209947 and 249130), one in an unit test, and another that's unlikely to still be relevant (the fix for saves version 61-65). The other three are "make Coverity happy" changes, but at least one also gets rid of some horrible code in `InitItemDescriptionBox`
=> Fix seven more Coverity issues

src/game/Tactical/Enemy_Soldier_Save.cc, src/game/Tactical/OppList.cc
1. The tempfile for some reason I couldn't figure out sometimes overwrites valid insertion grids with NOWHERE. I added extra checks to prevent that from happening.
2. Soldiers still in the helicopter are not visible on the map and therefore NOWHERE. This is valid, but they cannot be used in `HandleSight()`
I also finally caved in and added a NOWHERE check in HandleSight(). This should help @guijan with his DistanceVisible() crashes, but if we see this new error message we should treat it as a serious problem with the game logic that must be investigated.
Fixes #1634 and #1635.
=> Fix two more world data OOB accesses

src/game/Tactical/QArray.cc, src/game/Tactical/QArray.h, src/game/Tactical/Rotting_Corpses.cc, src/game/Tactical/Soldier_Control.cc
• `gsTerrainTypeSpeedModifiers` didn't have an entry for NO_TERRAIN
• `LookForAndMayCommentOnSeeingCorpse` can also be called for EPCs with a profile id > 74
• Remove unused array `QuoteExp_TeamSpecific`
I found this while testing my new fix for 1635 with an ASan build. More to come, but I need to investigate another crash I encountered a bit more first.
=> Fix two out of range array accesses

android/app/build.gradle, android/app/src/main/java/io/github/ja2stracciatella/ConfigurationModel.kt, android/app/src/main/java/io/github/ja2stracciatella/LauncherActivity.kt, android/app/src/main/java/io/github/ja2stracciatella/StracciatellaActivity.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/DataTabFragment.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/PlaceholderFragment.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/SectionsPagerAdapter.kt, android/app/src/main/res/layout/activity_launcher.xml, android/build.gradle
After doing the NDK upgrade, I decided to do the same for other android dependencies, while keeping the target sdk the same (because the issues described in https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1592). I fixed all deprecations as well. Functionally there should be no changes.
=> Upgrade Android dependencies and clean up deprecations

src/game/Tactical/OppList.cc, src/game/Tactical/Tactical_Turns.cc, src/game/Tactical/TeamTurns.cc, src/game/TileEngine/LightEffects.cc, src/game/TileEngine/LightEffects.h, src/game/TileEngine/Overhead_Map.cc, src/game/TileEngine/SmokeEffects.cc, src/game/TileEngine/SmokeEffects.h, src/game/TileEngine/WorldDef.cc
This adds more checks in OppList.cc if a soldier should even be considered in several places, some of which even already had comments that this should be done.
The changes in the other files are necessary to stop us from already trying to update sightings while we are still on the overhead map placing mercs.
I've tested this patches with an ASan build (with a hacky workaround for the Z blitter problem) with @guijan's saves from #1634 and #1635, some of the other saves I have around and played my own campaign for over an hour without problems. No promises that the game is now completely stable because I'm still early in the campaign, but it's definitely improving.
=> Make OppList.cc more robust

src/game/Tactical/Items.cc, src/game/Tactical/Morale.cc, src/game/Tactical/Soldier_Add.cc, src/game/Tactical/Soldier_Ani.cc, src/game/TacticalAI/AIMain.cc, src/game/TacticalAI/Movement.cc, src/game/TileEngine/Physics.cc
• Missing null check (14638, 254710)
• Logical dead code (81428, 81439, 81442, 81443)
• Unused value (81671)
• Identical code in different branches (81477)
• Dereference after null check (81474)
Nothing really substantial this time. I used the opportunity to change the bad algorithm to loop over all directions in a random order.
=> More Coverity fixes

src/externalized/VanillaWeapons_unittests.cc, src/game/Editor/EditScreen.cc, src/game/Strategic/Quests.cc, src/game/Tactical/Morale.cc, src/game/Tactical/Soldier_Add.cc, src/game/TacticalAI/NPC.cc
> Release the wrapper object in an items unit test (CID 219694)
> Out of bounds array accesses (81526, 81541, 249147, 254706)
> 
> Attempt to address the "Untrusted value as argument" CIDs
>     
> Ensure that `usFactMustBeFalse` and `usFactMustBeTrue` are in range before using them as array indices.
The check in `EditScreen.cc` may be necessary (I use the editor too rarely to be sure) but other than that these changes shouldn't do anything except reduce the number of incidents.
=> Another round of Coverity fixes

src/game/Tactical/Dialogue_Control.cc, src/game/Tactical/Dialogue_Control.h
The dialogue events are dynamically allocated so they must be deleted when they are popped from the queue.
=> Fix memory leak in EmptyDialogueQueue()

.ci/ci-build.sh, .github/workflows/github-ci.yml
Currently the version is not contained in the Android package name. Example: `ja2-stracciatella_-1648pullrequest+d295641_android.apk `
Seems like this is caused by the wrong java version used for the related `gradlew` call.
=> Fix Android package name

dependencies/lib-gtest/getter/CMakeLists.txt.in
This version of g-test fixes a compilation error with gcc-11. The commit message has a link with more details.
=> Upgrading googletest to v1.11

src/game/TileEngine/Render_Dirty.cc, src/game/TileEngine/Render_Dirty.h
`GetFreeBackgroundBuffer` does not guarantee that the returned `BACKGROUND_SAVE` is in a clean state so `RegisterBackgroundRect` must always set all members of this struct.
Without a reliable way to reproduce #1661 this is nothing more than an educated guess. I have definitely seen structs which had `fDisabled` set which can certainly cause graphical corruptions.  Another possible cause might be non-null `pSaveArea` or `pZSaveArea` pointers which would confuse `RestoreBackgroundRects` and `SaveBackgroundRects`. Vanilla had some extra checks which would have hidden this problem.
=> Ensure RegisterBackgroundRect properly initializes BACKGROUND_SAVE structs

src/externalized/scripting/FunctionsLibrary.cc, src/externalized/scripting/FunctionsLibrary.h, src/externalized/scripting/ScriptingExtensionsLua.cc, src/game/Tactical/Merc_Hiring.cc, src/game/Tactical/Soldier_Create.cc, src/game/Tactical/Soldier_Profile.cc
This adds new functions for mods to manipulate soldiers via scripts. This allows more complex logic on soldiers (skills, name, stats and appearances of RPC, hired mercs, enemies) which can depend on progress, current squad composition, fact, events, or items owned.
Exposing a new function and a data type via Lua:
- `GetMercProfile()`
- `SGPSector`
New observable extension points:
- `OnMercHired`
- `OnRPCRecruited`
- `OnSoldierCreated` now covers AutoResolve battles too
- Make enemies soldiers tougher on specific events
- Dynamically grant RPCs, depending on what skills you need the most (or the least)
- Update stats or skills of un-hired soldiers to simulate growth
=> Script extension points on new merc hired

src/game/Strategic/Auto_Resolve.cc, src/sgp/MouseSystem.h
It is only used once in auto resolve, where it can easily be replaced because the mouse region's user data is not used for anything else.
=> Remove the MouseRegion::Base hack

src/game/Laptop/AIMFacialIndex.cc, src/game/Laptop/AIMMembers.cc, src/game/Laptop/BobbyRMailOrder.cc, src/game/Laptop/EMail.cc, src/game/Laptop/Laptop.cc, src/game/Laptop/Personnel.cc, src/game/Strategic/Assignments.cc, src/game/Strategic/MapScreen.cc, src/game/Strategic/Map_Screen_Interface.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Map_Screen_Interface_Map_Inventory.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/Interface_Panels.cc, src/game/Tactical/ShopKeeper_Interface.cc, src/game/TileEngine/Overhead_Map.cc, src/game/TileEngine/Radar_Screen.cc, src/sgp/Button_System.cc, src/sgp/Button_System.h, src/sgp/MouseSystem.cc, src/sgp/MouseSystem.h
This should fix:
- #1679: Caused by the mouse region deleted within its callback, leading to a segfault. We now guard against deleted / disabled regions in `MouseCallbackPrimarySecondary` and `ButtonCallbackPrimarySecondary` before calling the callbacks
- #1666: We now always compare callback reason flags using the `&` operator
- Assertion messages on tactical placement screen: The array was not properly zeroed out when resetting merc placements
=> Touch control fixes

src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/game/GameScreen.cc, src/game/Strategic/Assignments.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Strategic_AI.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/LOS.cc, src/game/Tactical/Touch_UI.cc, src/game/TacticalAI/CreatureDecideAction.cc, src/game/TacticalAI/DecideAction.cc, src/game/TileEngine/Tactical_Placement_GUI.cc
This cleans up some compiler warnings I get from clang:
- Variables that are only assigned to, but never used
- Conflicts between function declaration and function definition
- Comparisons of signed values using `< 0`
- Missing cases in switches
=> Cleanup clang compiler warnings

src/externalized/mercs/MercProfile.cc, src/game/Tactical/Overhead.h, src/game/Tactical/Soldier_Control.h, src/game/Tactical/Soldier_Profile.h, src/game/Tactical/Soldier_Tile.cc, src/game/TacticalAI/NPC.cc
Fixes #1657. Also fixes an OOB in the MercProfile constructor and cleans up struct SOLDIERTYPE a little.
=> Do not call NPCReachedDestination() for soldiers without a MercProfile

src/game/Tactical/Morale.cc
Groups are not squads. Regressed by patch from #1608.
I found this while testing the 0.20 RC. It's a must-fix IMO.
=> Fix segmentation fault in NumberOfPeopleInSquad()

android/app/src/main/java/io/github/ja2stracciatella/LauncherActivity.kt
We currently have rendering issues with odd resolutions, but the Android laucher didn't take that into account when recommending a resolution.
This is bad experience for new players, as they will get corrupted graphics by default.
The actual rendering issue: https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1694
=> Don't recomment odd resolutions in Android launcher

src/game/TileEngine/RenderWorld.cc
This is a fix for the issue @lynxlynxlynx discovered in #1680. Exiting south was only possible in low resolutions. This should be fixed now. TBH the scrolling code is still quite incomprehensible to me, so I just increased the padding when the world is considered "scrolled all the way down". As the world actively scrolls down anyways when the exit cursor is shown I think this is an ok solution.
=> Fix exiting the map to the south on higher resolutions

src/game/Tactical/Handle_Items.cc, src/game/Tactical/PathAI.h, src/game/Tactical/Rotting_Corpses.cc, src/game/Tactical/Soldier_Add.cc, src/game/TileEngine/Exit_Grids.cc
Several functions store the old values of the global Path AI variables `gubNPCAPBudget` and `gubNPCDistLimit` and restore them upon function exit. However, four of these functions have early returns where the values are not restored.
The first commit fixes the problem, the second commit uses the new class where applicable.
I don't believe this is an urgent problem and who knows if this doesn't somehow cause some regression with the fragile path finding code, so it's probably a good idea to delay this until after the 0.20 release.
=> Properly restore two Path AI variables upon return from function

src/game/Tactical/Handle_Items.cc
clang-tidy found this vanilla bug. It's a nice example for the argument that variables should have the smallest scope possible.
=> Use correct gridno to calculate cost of a swipe attack

src/game/Tactical/Soldier_Ani.cc
`GetSoldier` returns a `shared_ptr`, which isn't cheap. `AdjustToNextAnimationFrame` can be called hundreds of times per second, but this `shared_ptr` is only used in four of the animation frames.
Usually I am not too concerned about performance of a game that was designed to run on a Pentium 133, but this one is really ugly, we are hammering the memory allocator just to set one `SOLDIERTYPE` member in very few cases.
We could also consider removing `GetSoldier` entirely. The other use cases aren't as bad, but the fact remains that none of them actually needs a shared pointer.
=> Do not use GetSoldier in AdjustToNextAnimationFrame

CMakeLists.txt, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/DefaultContentManagerUT.cc, src/externalized/ModPackContentManager.cc, src/externalized/strategic/BloodCatSpawnsModel.cc, src/externalized/strategic/BloodCatSpawnsModel.h, src/externalized/strategic/MovementCostsModel.cc, src/externalized/strategic/MovementCostsModel.h, src/externalized/strategic/SamSiteModel.cc, src/externalized/strategic/SamSiteModel.h, src/game/SaveLoadGame.cc, src/game/SaveLoadGame.h, src/game/Strategic/StrategicMap.cc, src/sgp/SGP.cc
clang 15 has enabled a new warning,  unqualified-std-cast-call, by default and found another useless variable. While I was fixing warnings anyway, I also enabled -Wignored-qualifiers.
=> Address new clang 15 warnings

src/sgp/Input.cc
It seems like there is also touch emulation for mouse events not only the other way around.
It's a bit more complex. There is a hint `SDL_HINT_ANDROID_SEPARATE_MOUSE_AND_TOUCH` for SDL2 `2.0.4` to `2.0.10`, to separate touch and mouse on Android. After `2.0.10` we have `SDL_MOUSE_TOUCHID`. I chose just to cover the second part, as we compile with `2.0.20` anyways for Android. The `#ifdefs` are there for older SDL versions on Linux.
Should close #1710.
=> Fix double events for mouse input on touch devices

src/game/Editor/EditScreen.cc, src/game/Editor/EditorItems.cc, src/game/Editor/SelectWin.cc, src/game/SaveLoadScreen.cc, src/game/Strategic/Auto_Resolve.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/sgp/Button_System.cc, src/sgp/VObject_Blitters.cc, src/sgp/VObject_Blitters.h, src/sgp/VSurface.cc
Passing `SGPRect` by value instead of by pointer so we do not have to assert the pointers are not null.
Not that it matter much but this should be about as efficient as the current method or even a tiny bit better because an `SGPRect` fits into a 64-bit register (2 registers on 32-bit systems).
=> Change function signature of (G|S)etClippingRect

src/sgp/MouseSystem.cc, src/sgp/MouseSystem.h
All of the current callers of MSYS_(G|S)etRegionUserData use constants for the index so it is pointless to check it at runtime.
In theory this prevents us from using variables for the indices in the future, but I don't see that as a real problem:
- nothing is stopping you from accessing the user.data array directly
- now that MOUSE_CALLBACK is defined as a std::function, you have a much more powerful way to pass data to your callbacks by using lambdas.
=> Check indices of MSYS user data functions at compile time

src/game/TileEngine/Exit_Grids.cc
With cheats enabled,  Ctrl + PgUp/PgDown should allow you to change floor levels. This is currently broken.
I found this while looking at #1720, but since this is a cheats-only function it cannot be the cause of that problem.
=> Fix AttemptToChangeLevel

CMakeLists.txt, src/game/Utils/Cursors.cc, src/sgp/Types.h
Wmissing-braces is triggered by Cursors.cc, Wunused-function can be triggered if the ENUM_BITSET macro is used and Wdeprecated-declarations is needed by the official latest RapidJSON release.
I should have investigated this better (turning sccache off helps), but a full rebuild with the local RapidJSON library currently produces lots of warnings.
=> Fix fallout from PR 1724 and disable some compiler warnings again

src/game/GameRes.cc, src/game/GameRes.h, src/game/Laptop/AIM.cc, src/game/Laptop/AIMLinks.cc, src/game/Laptop/AIMSort.cc, src/game/Laptop/BobbyR.cc, src/game/Laptop/BobbyRMailOrder.cc, src/game/Laptop/Florist.cc, src/game/Laptop/Funeral.cc, src/game/Laptop/IMPVideoObjects.cc, src/game/Laptop/Insurance.cc, src/game/Laptop/Mercs_Account.cc, src/game/Laptop/Mercs_Files.cc, src/game/Options_Screen.cc, src/game/SaveLoadScreen.cc, src/game/Strategic/PreBattle_Interface.cc
A shortcut for AddVideoObjectFromFile(GetMLGFilename()), this also saves a pair of ST::string constructor/destructor calls at the calling location.
Fairly trivial stuff, but it reduces code size at the calling sites by combining four function calls into one.
=> Add an overload for AddVideoObjectFromFile

src/externalized/AmmoTypeModel.cc, src/externalized/CalibreModel.cc, src/externalized/DefaultContentManager.cc, src/externalized/LoadingScreenModel.cc, src/externalized/MagazineModel.cc, src/externalized/ModPackContentManager.cc, src/externalized/army/GarrisonGroupModel.cc, src/game/Editor/LoadScreen.cc, src/game/Laptop/IMP_Begin_Screen.cc, src/game/SaveLoadGame.cc, src/game/SaveLoadGame.h, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Tactical/Animation_Data.cc, src/game/Tactical/Dialogue_Control.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/Interface_Panels.cc, src/game/Tactical/Rotting_Corpses.cc, src/game/Tactical/Tactical_Save.cc, src/game/TileEngine/Overhead_Map.cc, src/game/TileEngine/Radar_Screen.cc, src/game/TileEngine/Structure.cc, src/game/TileEngine/Structure.h, src/game/TileEngine/Tile_Cache.cc, src/game/TileEngine/Tile_Cache.h, src/game/TileEngine/Tile_Surface.cc, src/sgp/SGPFile.cc
• Several are no longer needed since PR #1713
• `JsonObject::AddMember` has a matching overload since PR #1045
• `IoException` always had ST::string as its parameter
This saves some ST string ➟ C string ➟ ST string round trips, which is just a convoluted way to create string copies that no one needs.
=> Remove unnecessary ST::string.c_str calls

assets/externalized/weapons.json
RPK was looking for a burst sound file that didn't exist so bursttype1 is now used for the RPK while other 5.45 weapons continue to use the sounds defined in calibres.json. Fixes the problem mentioned in #1714
=> Fix RPK burst sound

src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/DefaultContentManagerUT.cc, src/externalized/DefaultContentManagerUT.h, src/externalized/DefaultContentManager_unittests.cc, src/externalized/ShippingDestinationModel.cc, src/externalized/ShippingDestinationModel.h, src/game/Strategic/Strategic_Movement_Costs.cc
• Use smart pointers for ContentManager members.
• deleteElements templates no longer copy the map or vector
they're deleting first.
• Store ST::strings in vectors, not pointers to them.
• Remove useless clear() calls of vectors that are about to be destructed.
• DefaultContentManager::readJsonDataFile is already public, no need to
"expose" anything in DefaultContentManagerUT
=> Use more automatic memory manangement in ContentManager

assets/externalized/mercs-profile-info.json, rust/stracciatella/src/schemas/yaml/mercs-profile-info.schema.yaml, src/externalized/mercs/MercProfile.h, src/externalized/mercs/MercProfileInfo.cc, src/externalized/mercs/MercProfileInfo.h, src/game/Tactical/ShopKeeper_Interface.cc
Add a new field to mercs-profile-info.json which lets users specify a modifier when trading with arms dealers.
Always hiring Flo just to get more money from Tony is boring, so now others can get a bonus (or a handicap), too. Here is an overview of what's possible:
| Modifier | Buying a 100% dart gun | Selling a 100% MAC-10 |
| :---         |    ---:      |          ---: |
| 100  | 625 | 877 |
| 110 (Flo) | 563  | 964  |
| 10 (Minimum) | 1187 | 88 |
| 180 (Maximum) | 125 | 1578 |
I've never worked with the yaml schema files before, so it'd be good to have a closer look at these changes.
=> Externalize Flo's weapon deals bonus

src/game/MainMenuScreen.cc, src/game/TileEngine/WorldDef.cc, src/sgp/Input.cc, src/sgp/Input.h
- remove DequeueAllEvents from TileEngine/WorldDef.cc to make inputs while loading savegame
- rename DequeueAllEvents to DequeueAllInputEvents
Signed-off-by: Richard Fröhning <misanthropos@gmx.de>
=> - remove DequeueAllEvents from TileEngine/WorldDef.cc and name it DequeueAllInputEvents

src/game/TacticalAI/DecideAction.cc
DecideActionRed had two code paths where it would return AI_ACTION_CHANGE_STANCE without setting the new stance in usActionData.
I found this rather by accident [here](https://github.com/hb029/JA-2-Stracciatella/commit/00936bcfa680f48fe1e0316b987edc4151892af0). The author claims this can cause an AI deadlock, if that's true then this is a quite important fix and it would have been nice if he had let us know about it.
=> Add two missing usActionData assignments

src/externalized/AmmoTypeModel.cc, src/externalized/AmmoTypeModel.h, src/externalized/CalibreModel.h, src/externalized/DefaultContentManager.cc, src/externalized/Exceptions.h, src/externalized/ModPackContentManager.h, src/externalized/Soldier.cc, src/externalized/content/Dialogs.h, src/externalized/mercs/MercProfileInfo.cc, src/externalized/mercs/MercProfileInfo.h, src/externalized/mercs/RPCSmallFaceModel.cc, src/sgp/SGPStrings.h
• string_theory uses uint64_t but does not include stdint.h
• dangling references to rapidjson arrays
• incorrect initialization order in MercProfileInfo
• warning about possible OOB array access in switchHeadGear (not really
possible, but this code would not be safe if we'd use multithreading).
=> Address problems when compiling with GCC 13

src/game/Tactical/TeamTurns.cc
The function call for this message was probably unintentionally removed in a previous commit. Right now, we display the list only when there are more than six guys interrupting, so almost never.
[(This commit, if you're curious.)](https://github.com/ja2-stracciatella/ja2-stracciatella/commit/706477d84f95ab26095f7c022c488c9f7142de1b#diff-683714cce60d534b535dfdc2addbcb887374d604f05f72ccfa6a9f325e37af05L568)
=> Restore the "Interrupt for ..." message from vanilla

src/game/Credits.cc
Currently the KEY_DOWN event from pressing the ESC key takes us back to the main screen where the corresponding KEY_UP event then makes us quit the game.
=> Fix: Pressing ESC while the credits are playing no longer quits the game

src/game/GameScreen.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Tactical/Interface_Panels.cc, src/game/Utils/MercTextBox.cc, src/game/Utils/MercTextBox.h, src/sgp/Font.cc, src/sgp/Font.h, src/sgp/VSurface.cc, src/sgp/VSurface.h, src/sgp/Video.cc
The only difference between SGPVSurfaceAuto and SGPVSurface is that the former frees the underlying SDL_Surface upon destruction while the latter does not. There is only one surface where we do not want this automatic free to happen: the screen buffer.
This behaviour was added back in 2013 to fix issue #45: crashes on MacOS. So why do we not need this special behaviour any more? Back then the wrapped surface for the screen buffer was obtained by a call to the SDL 1.2 function SDL_SetVideoMode, and that surface must not be freed by the application, similar how the surface obtained by a call to SDL_GetWindowSurface in SDL 2.0 must not be freed.
Nowadays Stracciatella uses CreateRGBSurface for the screen buffer, so the need for SGPVSurfaceAuto simply is not there any more. SGPVSurface can …
=> Remove SGPVSurfaceAuto

src/game/Strategic/Map_Screen_Interface_TownMine_Info.cc, src/game/Strategic/StrategicMap.cc, src/game/Strategic/StrategicMap.h
Fixes the logic in AddCommonInfoToBox that got broken when SAM site locations were externalized. Also removes an unnecessary overload for GetTownIdForSector, the compiler will automatically convert an UINT8 to a SGPSector for us.
=> Display correct information in sector popup boxes

src/game/Tactical/Overhead.cc
It is true that drunk Larry does not have a quote for being under fire, however the dialogue system does not expect every merc to have a full set of quotes and handles this situation just fine. All this check does now is prevent modders from adding the missing quote.
=> Remove a check for profile ID 53 in HandleSuppressionFire

src/game/Laptop/Insurance_Contract.cc, src/game/Strategic/Auto_Resolve.cc, src/game/Strategic/Strategic_Movement.cc, src/game/TileEngine/SaveLoadMap.cc, src/game/TileEngine/Structure.cc, src/game/Utils/Slider.cc, src/game/Utils/Text_Input.cc, src/sgp/Debug.h, src/sgp/MouseSystem.cc
• Do not construct strings for the filename prematurely • Do not create a new instance of an empty string every time an Assert
line is reached, use just one global instance instead.
• Use Assert instead of AssertMsg for null pointer checks, the message
does not add anything useful.
I repeated my test from #1751 with this patch and this saved ~1.9 million allocations in four minutes, or ~7800 allocations every second.
=> Reduce the cost of Assert and AssertMsg

src/game/Tactical/Animation_Control.h, src/game/Tactical/Soldier_Control.cc, src/game/Tactical/Soldier_Macros.h, src/game/Tactical/Soldier_Tile.cc
When a prone merc M1 swapped places with a not prone merc and M1's new grid and position didn't allow him to be prone there, he became unhittable.
This is not what is causing the enemies to become unhittable because the AI does not exchange places, but the added warning in `SetSoldierGridNo` should make it easier to figure out who's calling that function without proper checks.
=> Prevent mercs from swapping places when that make one of them unhittable

src/game/Tactical/LoadSaveSoldierType.cc, src/game/Tactical/Soldier_Control.cc, src/game/Tactical/Soldier_Control.h, src/sgp/LoadSaveData.h
• Low morale confirmations restored (#1757), can be muted by game option
• BATTLESNDS BOOLEAN member had three different values
• Typos
• Changed SOLDIERTYPE::bOldBattleSnd from INT8 to enum
=> BattleSnds maintenance

src/sgp/SGP.cc, src/sgp/Video.cc, src/sgp/Video.h
I misunderstood the SDL documentation, `RenderCopy` only stretches the texture to fill the viewport, while `RenderClear` clears the entire window area. Fortunately it is still not necessary to clear everything every frame.
=> Fix visual artifacts when resizing the window or toggling fullscreen

src/game/Tactical/Soldier_Control.cc
Not setting `sGridNo` causes problems when NPCs leave a sector, for example when Fatima moves from A9 to A10.
Make the new warning appear less often, we only need it figure out the problem with the enemy AI.
I should have known better than to blindly trust code comments, this causes several error messages and OOB accesses in current builds.
=> Undo damage from PR #1759

src/game/Tactical/Soldier_Ani.cc, src/game/Tactical/Weapons.cc, src/game/Tactical/Weapons.h
These function used a BOOLEAN to express four different possible results. This commit also uses the new return type for `FireWeapon`, even though nobody is currently using the returned value. This adds a fifth possible result to the enum.
More code comments that contradict the actual code, lovely.
=> Give CheckForGunJam and OKFireWeapon a proper return type

src/game/Strategic/Assignments.cc
DetermineWhichAssignmentMenusCanBeShown must not call this function before checking some flags, otherwise mousing over a vehicle triggers a stream of assertions.
This commit includes another fix for a problem found by clang-tidy: being a POW was supposed to be stressful and impede healing, but this never worked due to a missing 'else'.
=> Fix assertion failure in GetSelectedAssignSoldier

src/game/Tactical/Overhead_Types.h, src/game/Tactical/Points.cc, src/game/Tactical/Points.h, src/game/Tactical/UI_Cursors.cc, src/game/Tactical/UI_Cursors.h
Fixes #1765. This commit also merges the refine aim related constants that were split over two headers and adresses two issues pointed out by clang- tidy: dead stores in UI_Cursors.cc and Points.h needed other headers to be included before it.
=> Do not add aim time to displayed # of APs when using the underhand launcher

src/game/TacticalAI/AI.h, src/game/TacticalAI/AIInternals.h, src/game/TacticalAI/AIMain.cc, src/game/TacticalAI/Movement.cc
These functions were using int, INT16 or INT8 to return TRUE or FALSE. Also remove declarations of four nonexistent functions.
If you're wondering why I care, I tried building with `-Wconversion`. Ouch. I believe the developers were just throwing a dice when they had to decide which type to use.
=> Change return type of four AI-related functions to bool

src/game/Strategic/Assignments.cc
Use a more reliable way to find the selected merc to remove. Fixes #1788.
This also changes the logic in `CreateDestroyMouseRegionsForRemoveMenu` a bit: `GetNumberOfLinesOfTextInBox(ghRemoveMercAssignBox)`  always returns 2 here, no other value would make sense, there are only two mouse regions available for this.
=> Don't crash when removing a dead merc from the roster

src/game/Strategic/Assignments.cc, src/game/Strategic/Assignments.h
Fallout from the introduction of `SGPSector`: `fSectorsWithSoldiers` used the strategic index (0-323) as its array index, not the sector index (0-255). Changing this array to a bitset and adding a dedicated function to convert a `SGPSector` to a position should help to avoid this mistake in the future.
This function was only used once, but in the really important function `FindStratPath`, which probably caused the enemy troops to use incorrect routes.
=> Fix: IsThereASoldierInThisSector uses wrong SGPSector to index method

src/game/TileEngine/Tile_Surface.cc, src/sgp/Buffer.h, src/sgp/HImage.cc, src/sgp/HImage.h, src/sgp/Types.h, src/sgp/VObject.cc, src/sgp/VObject.h
`SGP::Buffer` is essentially just a pre C++11 version of unique_ptr's array variant. It is less functional and certainly far less known than its modern successor.
This PR demonstrates a practical benefit of this approach: `SGPImages`  are short-lived (often unnamed and temporary) objects that are only created as a step in the creation of other things ike `SGPVObject`. It is therefore safe to move data away from `SGPImage` instead of copying it.
=> Proposal: Transition away from SGP::Buffer

src/game/Tactical/OppList.cc, src/game/Tactical/Overhead.h
• Remove the `HandleSight` warning about NOWHERE, it is no longer useful
• Remove the always defined `WE_SEE_WHAT_MILITIA_SEES_AND_VICE_VERSA` macro
Addresses #1801.
=> OppList.cc maintenance

src/game/Utils/_ChineseText.cc
Resolves #1784.
Before:
After:
=> Fix errors in _ChineseText.cc

.ci/ci-build.sh, .ci/ci-setup.sh, .github/workflows/coverity-scan.yml, .github/workflows/github-ci.yml
The image we use (ubuntu-18.04) is in the process to be deprecated.
- Announcement: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
- Details: https://github.com/actions/runner-images/issues/6002
=> Upgrade GitHub Action builder image

assets/externalized/game.json, rust/stracciatella/src/schemas/yaml/game.schema.yaml, src/externalized/policy/DefaultGamePolicy.cc, src/externalized/policy/GamePolicy.h, src/sgp/SGP.cc, src/sgp/Video.cc, src/sgp/Video.h
Change how often GameLoop() gets called
Before this commit, the duration between two GameLoop calls was
configurable (ms_per_game_cycle, default 25ms). This is problematic
because many of the predefined timecout counters use multiples of 5ms,
and the delay between two soldier animations is even calculated with
a resolution of 1ms.
With this commit the game now tries to call GameLoop at a rate of
144Hz (every ~7ms), corresponding to the refresh rate of modern
monitors. To satisfy the needs of our users who do not need 144 FPS
and would prefer a lower CPU usage, GameLoop()'s heaviest subfunction
RefreshScreen() now has its own timeout.
This patch should make our timings be more in line with those originally intended by the JA2 developers. For example, `ExecuteOverhead` was supposed to run …
=> Proposal: Revamp calling of the game loop

src/game/Strategic/Assignments.cc, src/game/Strategic/Assignments.h, src/game/Tactical/Squads.cc
Fixes #1813. Also clean up code duplication in RepairMenuBtnCallback.
=> Stop ChangeSoldiersAssignment from clobbering just set repair values

src/game/Strategic/Auto_Resolve.cc, src/game/Utils/Sound_Control.cc, src/game/Utils/Sound_Control.h
• `getSoundSample()`: unused function that didn't do anything useful.
• `PlayJA2StreamingSample()`: exactly the same as `PlayJA2Sample`
• `PlayJA2Sample`: could call SoundPlay with a NULL filename
• `PlaySoldierJA2Sample`: wrong return value in case of an error
• simpler implementation of `SoundRange()`
=> Address several problems in Sound_Control.cc

src/game/TacticalAI/FindLocations.cc
As the name suggests, this function is supposed to calculate how much better a new cover position is compared to the old one, so returning NOWHERE would indicate the new cover is 25,600% better.
In theory this could change the behavior of the AI slightly so that enemies choose a different gridno to take cover, in practice I didn't any case where this function actually returned 25600.
=> Fix return value of CalcPercentBetter

src/game/Laptop/Mercs.cc, src/game/Tactical/Soldier_Ani.cc, src/game/Tactical/Soldier_Control.cc, src/game/Tactical/Weapons.cc, src/sgp/Random.cc, src/sgp/Random.h
This addresses several cases where a probability of 50% was intended but the result was either a bit or completely off. Notable change in gameplay: critical hits to the torso will no longer automatically cause a loss of dexterity.
=> Add a new function CoinToss() to Random

CMakeLists.txt, src/sgp/Platform.h
• remove unused define WITH_SOUND_DEBUG
• fix WITH_ASAN option
• only add compiler warnings flags when compiling, not when linking
• disable some MSVC warnings here instead of in Platform.h
I could've used generator expressions for the warnings but I find the if-else-endif construct much easier to read and understand.
=> CMakeLists.txt maintenance

src/game/Laptop/IMP_Begin_Screen.cc
Limit nickname length to 8 characters.
It's currently possible to create a nickname that's too long if you enter a full name with more than 8 characters before the first space and then leave the nickname text field empty.
=> Prevent overly long IMP nickname

src/sgp/Button_System.cc
It is pointless and doesn't even build any longer since GUI_CALLBACK was changed to std::function.
This was causing the Appveyor build failure in #1829.
=> Remove BUTTONSYSTEM_DEBUGGING

src/externalized/scripting/FunctionsLibrary.cc, src/externalized/scripting/FunctionsLibrary.h, src/externalized/scripting/ScriptingExtensionsLua.cc, src/game/Strategic/Game_Event_Hook.cc, src/game/Strategic/Quests.cc, src/game/Tactical/Campaign.cc
Adding several more event hooks and Lua functions for mods to handle Strategic level events.
- Allowing mods to process, or ignore StrategicEvents - `OnStrategicEvent`
- Allowing mods to trigger  StrategicEvents - `AddEveryDayStrategicEvent`, `AddStrategicEvent`
- Allowing mods to override the current value of game progress (which affects weapons availability, enemy levels) - `OnCalcPlayerProgress`
- Allowing mods to process quests - `OnCheckQuests`, `OnQuestEnded`
- Allowing mods to process facts - `SetFactTrue`, `SetFactFalse`, `CheckFact`
- Mods can read the current game clock - `GetWorldTotalSeconds`, `GetWorldTotalMin`, `GetWorldDay`
---
Example: Disabling Meanwhile scenes from mod
```lua
require('enums.lua')
RegisterListener("OnStrategicEvent", "skip_meanwhile")
function …
```
=> Strategic-level modding support (Event, Quests and Facts)

CMakeLists.txt
Add a CMake option to use precompiled standard library headers. This cuts down compilation times quite a bit when not using ccache or sccache.
I obviously didn't try every possible combination of headers , compilers and configurations, but to give you some idea of the savings for a fresh build without cache:
Compiler, Config | no PCH | PCH |
---------------- | ------ | --- |
GCC 13, Debug | 1143.46user |883.24user |
Clang 16, RelWithDebInfo | 1638.52user | 1249.86user
=> Add an option to use precompiled headers

src/game/Credits.cc, src/game/Editor/EditScreen.cc, src/game/Editor/LoadScreen.cc, src/game/Editor/MessageBox.cc, src/game/Editor/PopupMenu.cc, src/game/GameInitOptionsScreen.cc, src/game/GameScreen.cc, src/game/HelpScreen.cc, src/game/Intro.cc, src/game/Laptop/Laptop.cc, src/game/Loading_Screen.cc, src/game/MainMenuScreen.cc, src/game/MessageBoxScreen.cc, src/game/Options_Screen.cc, src/game/SaveLoadGame.cc, src/game/SaveLoadScreen.cc, src/game/Strategic/Auto_Resolve.cc, src/game/Strategic/MapScreen.cc, src/game/Strategic/PreBattle_Interface.cc, src/game/Strategic/Quest_Debug_System.cc, src/game/Tactical/Auto_Bandage.cc, src/game/Tactical/ShopKeeper_Interface.cc, src/game/TileEngine/Overhead_Map.cc, src/game/TileEngine/RenderWorld.cc, src/game/TileEngine/Render_Dirty.cc, src/game/TileEngine/Render_Dirty.h, src/game/Utils/Animated_ProgressBar.cc, src/sgp/Video.cc, src/sgp/Video.h
ExecuteBaseDirtyRectQueue and EndFrameBufferRender just set two flags that the entire screen should be refreshed or that the frame buffer is dirty, something RefreshScreen() can figure out itself by looking at the state of three variables it needs to check anyway.
These changes turned made AddBaseDirtyRect just a synonym for InvalidateRegionEx, so it could be removed, too.
=> Remove three unnecessary functions handling video refresh

src/game/Editor/EditScreen.cc, src/game/Editor/Road_Smoothing.cc, src/game/Editor/Road_Smoothing.h
The function InitializeRoadMacros simply computes an array of constants from another array of constant values, so there is no need to do this at run time and include the code for it in the executable.
=> Compute gsRoadMacroStartIndex array at compile time

src/game/Tactical/Points.cc, src/game/Tactical/Points.h, src/game/TacticalAI/AIInternals.h, src/game/TacticalAI/Attacks.cc
MinAPsToAttack() can return 1 for extreme values of ubShotsPer4Turns in weapons.json, so always subtracting 1 AP for the cost of turning even if the soldier does not need to turn for the attack gave 0 for ubRawAPCost and a division by 0 followed when computing the hit rate.
CalcTentacleAttack() had the same problem.
Removed declaration of non-existant function GetBPsTouseJar().
Fixes #1840 (the crashing part, I didn't observe the unexpected item class warning while testing this).
=> Fix division by 0 in CalcBestStab()

src/game/Tactical/Tactical_Save.cc
This function returned wrong results while loading the game, which lead to misleading warning messages like "SynchronizeItemTempFile() Reported 0, should be 1".
`SynchronizeItemTempFileVisbleItemsToSectorInfoVisbleItems`  simply wants to compare the number of
WORLDITEMs in the temp file with the `uiNumberOfWorldItemsInTempFileThatCanBeSeenByPlayer` in the 
`SECTORINFO` or `UNDERGROUND_SECTORINFO` structs, but `GetNumberOfVisibleWorldItemsFromSectorStructureForSector`
does a little more than just return that number.
=> Fix GetNumberOfVisibleWorldItemsFromSectorStructureForSector

src/game/TacticalAI/Attacks.cc
Make it crystal clear even to static analyzers that ubRawAPCost can never be 0. CIDs 322125, 322126.
This is almost funny, now that I've fixed the situations where this might actually happen in #1843, Coverity finally detects that MinAPsToAttack might return 1 and 1-1=0. Why it didn't find that when we were still unconditionally subtracting 1 is a mystery.
=> Address two new coverity defects

src/game/Tactical/Interface_Dialogue.cc
Apparently, a long time ago before vanilla was even released, Carlos's "greeting" when you enter the rebel basement was implemented as a conversation. Now he simply talks to no one in particular so we do not need to find someone on our team he can converse with.
=> Remove some useless code in DoneFadeInActionBasement

src/game/Tactical/Turn_Based_Input.cc, src/sgp/Input.cc
Treat the keys that are labeled with the grave, equals sign and slash on an US keyboard like those keys on all keyboard layouts so they can be used as shortcuts in tactical mode. Does not affect text input when entering save game descriptions.
Also add ',' as an alternative to '*' to toggle red item glow.
Fixes #1844.
=> Give special treatment to some keys used as shortcuts in tactical

.ci/ci-functions.sh, appveyor.yml
[skip actions]
After reading https://www.appveyor.com/docs/build-cache/#caching-chocolatey-packages I think we could make those builds faster and more reliable by caching the sccache binary itself, too.
=> AppVeyor: Cache sccache binary

src/game/Strategic/PreBattle_Interface.cc
Move a GUI_CALLBACK instead of copying it (clang-tidy warning).
=> Fix hardcoded SAM site locations in PreBattle_Interface

CMakeLists.txt, COMPILATION.md, src/sgp/Video.cc
I unintentionally raised this when I used SDL_CreateRGBSurfaceWithFormat in 67654996626ea5ceb20abe5236f4d625e6063b42. So far nobody has complained and I don't believe requiring your SDL version to be less than seven years old is too much too ask.
=> Correct documentation of minimum required SDL2 version

src/game/Tactical/Soldier_Create.cc
Having a zero gmSMCurrentMerc pointer while the SM panel is open is pretty bad. All the panel's mouse regions and their callbacks are still active and many of them expect a valid pointer.
There is not enough information in #1870 to say that this is the cause of that crash, but I've definitely seen an ASAN violation when the current merc left, so something like this is needed in any case.
=> Force a switch to the team panel when necessary.

src/game/Tactical/Soldier_Add.cc
The method these functions used to filter out gridnos without a path to the sweet spot was broken: uiRange was set to 999 and then compared to uiLowestRange. However, since uiLowestRange initial value is 999999, this invalid gridno could be considered as the best, and if there are no gridnos with a valid path in the search range, it could be returned as the result.
I believe this bug is not very likely to happen, but it could potentially the source (or one of the sources) of the path finding warnings we get occasionally.
=> Fix bug in two FindGridNoFromSweetSpot* functions

src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/sgp/FileMan.cc, src/sgp/FileMan.h, src/sgp/SGPFile.cc, src/sgp/SGPFile.h
This is optional (not needed to open the file), but enables better diagnostics.
Remove unused SGP_FILETIME and SGPFileFlags.
Failure to open a file already logs the filename. Actual file operations should do the same, it would help in cases like #1873.
=> Add the filename to SGPFile

src/game/Strategic/Strategic_Movement.cc, src/game/Strategic/Strategic_Pathing.cc
Also change a couple of assertions to SLOGE messages. This avoids the crash with the save game provided in issue #1871.
The strategic pathfinding problem is still there, that's why I'd leave 1871 open, it has a nice testcase. This is what it looks like with this commit:
```
2023-08-10T09:14:16.024072348Z [ERROR] game/Strategic/Strategic_Movement.cc: Invalid DIAGONAL waypoint being added for groupID 30. AM-0
2023-08-10T09:14:16.024268076Z [ERROR] game/Strategic/Strategic_Movement.cc: Invalid DIAGONAL waypoint being added for groupID 30. AM-0
2023-08-10T09:14:16.024369941Z [ERROR] game/Strategic/Strategic_Movement.cc: Invalid DIAGONAL waypoint being added for groupID 30. AM-0
2023-08-10T09:14:16.024461411Z [ERROR] game/Strategic/Strategic_Pathing.cc: Path exists, but no waypoints were …
```
=> Do not dereference a null pointer in RebuildWayPointsForGroupPath

src/game/TileEngine/Ambient_Control.cc, src/sgp/FileMan_unittest.cc, src/sgp/LoadSaveData_unittest.cc
5 new COPY_INSTEAD_OF_MOVE complaints, caused by #1874. CID 323024-323028
I felt obligated to fix these because I caused them, but in general I believe all these performance defects that Coverity is now reporting would best be handled automatically by a tool like clang-tidy.
=> Address new Coverity defects

src/game/Laptop/EMail.cc, src/game/LoadSaveEMail.cc
`CurrentMail` was not zeroed during load, so it pointed to the deleted object. Results can vary, but one of them is an assert firing in the string theory library:
```
string_theory/st_utf_conv.h:263: String data buffer is too large
```
fixes #1591
=> Fix crash when opening email box after save and load

src/game/Editor/EditorMercs.cc, src/game/JAScreens.cc, src/game/Tactical/Soldier_Control.cc, src/game/Tactical/Soldier_Control.h, src/game/Tactical/Soldier_Init_List.cc, src/game/Tactical/Soldier_Init_List.h, src/game/Utils/Utilities.cc
• Fix null pointer deref in FindSoldierInitNodeWithID when trying to
add a soldier to an already full team
• GetPaletteRepIndexFromID does no longer throw an exception; the editor
uses this function to determine if there is a valid replacement
The first one is a vanilla bug; the exception was added in 71bd4e296a11e46dbe8593f67359cbd388c9e2ea  but I think this change failed to take the editor's needs into account.
=> Make the editor crash less often

src/game/TileEngine/Lighting.cc, src/game/TileEngine/WorldDef.cc, src/game/TileEngine/WorldDef.h
This array was allocated with new once during the program's initialization phase and only released during shutdown. This made little sense because much of the codebase expects it to be always present in memory.
This makes the array a bit faster to access and saves a couple of KB code size in a release build.
=> Statically allocate the gpWorldLevelData array

src/game/Strategic/Auto_Resolve.cc, src/game/Strategic/Town_Militia.cc, src/game/Strategic/Town_Militia.h, src/game/Tactical/Militia_Control.cc, src/game/Tactical/Overhead.cc
Not all members of the militia team are trainable militia as in vanilla; the editor also allows to add so-called "rebels" to this team. Mods should be able to use these rebels without crashing the game when we try to promote militia after a successful fight.
Fixes #1886.
=> Handle attempts to promote militia better

src/game/Editor/EditorBuildings.cc, src/game/Utils/Text_Input.cc
HandleMouseClicksInGameScreen() could call InitDoorEditing() again and again, leading to a stack of buttons and text input fields on top of each other that were impossible to get rid of completely.
Also Text_Input.cc didn't properly update all its pointers when pushing or popping an editing context.
Fixes #1892.
=> Fix editing of keys

src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/ItemSystem.h, src/game/Strategic/QuestText.h, src/game/Tactical/Arms_Dealer_Init.cc, src/game/Tactical/World_Items.cc, src/sgp/SGP.cc
Compilation failed with GCC13 when precompiled headers were disabled. Also addresses some other minor issues:
• Unnecessary copy of a map and a vector
• move SLOGD out of DefaultContentManager's destructor so it
can be noexcept
• Pointed out by clangd: const keyword prevents return value
optimization
=> Fix compilation failures due to missing headers

assets/externalized/weapons.json, src/game/Tactical/Weapons.cc
This should fix the problem of the missing sound for CAWS buckshot ammo and the RPK74 using the generic sound even when the 5.45 burst sound is available (when we have four or less shots left). Issues #1730 and #1764.
This could definitely use more testing, I'd appreciate help here. This is what I found with two known problematic weapons:
|CAWS, CAWS buckshot magazine||
|---|---|
|>=3 bullets left| bursttype1.wav|
|2 bullets left| bursttype1.wav|
|1 bullet left| bursttype1.wav|
|CAWS, CAWS magazine||
|---|---|
|>=3 bullets left| shotgun burst 3.wav|
|2 bullets left| shotgun burst 2.wav|
|1 bullet left| shotgun single shot.wav|
|RPK74||
|---|---|
|>=5 bullets left:|bursttype1.wav|
|4 bullets left| 5,45 burst 4.wav|
|3 bullets left| 5,45 burst 3.wav|
|2 bullets left| 5,45 burst 2.wav|
|1 …
=> Rework burst sound logic

src/game/TileEngine/Structure.cc, src/sgp/VObject.cc, src/sgp/VObject.h
The Z-Blitter functions disagree with AddZStripInfoToVObject about the format of the zchange array in a ZStripInfo, which leads to constant complaints (with valgrind) or crashes (in ASAN builds) when blitting some multitile VObjects. Since nobody seems to fully understand what this code is supposed to do, this commit changes the zchange array to a fixed size of 16 bytes. Each byte is supposed to represent the z change of 20 pixels, so this is enough for multitile VObjects up to 320 pixels wide. AFAIK the biggest asset in the original game data is the queen monster, which requires a zchange array of 10 bytes, so 16 bytes should be plenty.
=> Workaround for the Z-Blitter address sanitizer problem

rust/Cargo.lock, rust/stracciatella/Cargo.toml, rust/stracciatella/src/fs.rs, rust/stracciatella/src/vfs/mod.rs, rust/stracciatella_c_api/src/c/fs/mod.rs
Some linking issues with the new version still exist, but we dont even use it, except for one test where the directory is empty anyways.
=> Remove remove_dir_all rust dependency

src/game/Tactical/Handle_UI.cc, src/game/Tactical/Handle_UI.h, src/game/Tactical/Real_Time_Input.cc, src/game/Tactical/Turn_Based_Input.cc, src/game/TileEngine/RenderWorld.cc
This should greatly improve the experience on touch devices, as scrolling when in pan mode is less glitchy. In order to test more easily I also added panning with `Shift+Middle Mouse Button` on non-touch devices using the same code paths.
Closes #1490
=> Add pan mode for non-touch devices and fix stuttering scrolling

rust/stracciatella/src/config/stracciatella_home.rs
The new dir should be: `C:\Users\Alice\AppData\Roaming\JA2`, which is not influenced by MS Defender on Windows.
Closes https://github.com/ja2-stracciatella/ja2-stracciatella/issues/1864.
I need someone to test this though, as I dont have a Windows system available to me.
=> Change configuration directory on Windows to AppData

dependencies/lib-string_theory/builder/CMakeLists.txt.in
Closes the overflow bug reported by @momoko-h  https://github.com/zrax/string_theory/issues/29.
Also closes the stdint include issues.
=> Upgrade string_theory to 3.8

src/game/Strategic/MapScreen.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Map_Screen_Interface_Map.h
b_map.pcx was loaded twice and copied to a surface twice during startup, once just to compute the green and red alternative palettes for the map. The palettes are now generated later, from the surface that is actually used during the game.
Not really a big deal, modern CPUs are just too fast to care about loading a ~450k PCX file.
=> Load the big map of Arulco just once

src/game/Laptop/AIMFacialIndex.cc
The red shade of dead mercs was constantly recreated and leaked while moving the cursor around over these faces.
Probably a copy and paste bug; there's very similar code in Merc_Files.cc, AIMMembers.cc and Insurance_Contract.cc, but in those cases we don't leak because we're always using new SGPVObjects.
=> Fix memory leak in DrawMercsFaceToScreen

src/game/TileEngine/Radar_Screen.cc, src/game/TileEngine/RenderWorld.cc, src/game/TileEngine/RenderWorld.h
These variables were only set in InitRenderParams and computed from constants, so the results were also constant.
=> Make four render variables const

android/app/src/main/java/io/github/ja2stracciatella/GameDir.kt, android/app/src/main/java/io/github/ja2stracciatella/LauncherActivity.kt, android/app/src/main/java/io/github/ja2stracciatella/ui/main/DataTabFragment.kt, android/app/src/main/res/values/strings.xml, rust/stracciatella/src/vfs/mod.rs, src/launcher/Launcher.cc, src/launcher/Launcher.h
Now a warning is shown after three user interactions
- Selecting a game directory
- Autoguessing version
- Starting the game
whenever one of the following conditions is true:
- Game directory does not contain `Data` dir
- Game directory contains a 1.13 data file
The user has the choice to continue anyways or cancel the action.
As discussed in #1693.
=> Warn about 1.13 modified game files in launcher

src/game/Tactical/Soldier_Create.cc
We can have a non-null gpSMCurrentMerc even when the current screen is not the game screen. Calling SetCurrentInterfacePanel() in that situation leads to all the interface elements of the panel being created, so you could for example end up with a Change Squad button on the main menu screen.
To reproduce this bug: in Tactical, have the Single Merc Panel open, the press O to go to the options screen. Choose Quit to go back to the main menu then move the mouse over the region where the three buttons left of the radar area are.
=> Fix bug in InternalTacticalRemoveSoldier panel logic

src/game/TileEngine/RenderWorld.cc, src/game/TileEngine/Structure.cc, src/game/TileEngine/TileDef.cc, src/sgp/VObject.cc, src/sgp/VObject.h
This removes some boilerplate cleanup code.
You have probably heard this all before; raw owning pointers bad, smart pointers good, etc.
Obviously this is a really low priority change that can easily wait until the 0.21 release.
=> Use smart pointers to manage ZStripInfo structs

src/game/Tactical/Interface_Items.cc, src/game/Tactical/Items.cc
• Fix off-by-one crash in CycleItemDescriptionItem (cheats only)
• Add warning about invalid status value to CreateItem
• Address some clangd complaints about copying MOUSE_CALLBACKs
Fixes #1925 and adds some diagnostics that may help figure out #1924. I had to change the key combination to cycle backwards because we don't reach that part of the code when both alt and shift are pressed.
=> Minor cleanup of item creation code

src/game/MainMenuScreen.cc
Due to some leftovers from really ancient debug code which used the main menu screen to test the display of foreign language fonts, the main menu screen redrew its buttons every game loop. The result was that the game required a highly inflated number of CPU cycles to render a static image.
Some callgrind numbers (IR per call, inclusive)
| Function    | Unpatched |Patched|
| -------- | -------: |-----:|
| GameLoop  | 661460    |32112|
| MainMenuScreenHandle | 246454     |1449|
Looks like [this junk](https://github.com/dariusk/ja2/blob/876ccf5dfdad7e6821c5b26d6d783132ea1ab7a2/ja2/Build/MainMenuScreen.c#L661) wasted plenty of energy over the last 25 years...
=> Reduce CPU usage of the main menu screen

src/game/Tactical/Items.cc
This should only do minimal damage to items: worst case is 3 points to bloodcat pelts.
=> Limit the damage to items done by alt+o to almost nothing

src/game/Editor/EditorMercs.cc, src/game/Editor/Editor_Taskbar_Utils.cc
This made an area of the merc inventory panel hard to reach, issue #1946.
=> Correct bottom coordinate of an editor mouse region

src/game/Utils/Text_Input.cc
This function still tried to handle input even when there was no active input field, for example after calling DisableAllTextFields(), which could lead to a access violation when trying to dereference a NULL gpActive pointer.
STR if you want to see the crash for yourself:
1. Open the editor
2. Load sector A9
3. Click on the Mercs tab
4. Find Pacos or Fatima and right click on them
5. Click the "Merc Att" button to see their stats in disabled text fields
6. Press the right arrow or the End key
=> Fix crash in HandleTextInput()

src/game/Strategic/Strategic_Pathing.cc, src/game/Strategic/Strategic_Pathing.h
PathAI.cc and Strategic_Pathing.cc both had global definitions of the types path_t and trail_t. Fixed by placing the strategic variants in a new namespace.
This commit also removes some old crud from the header.
Fixes #1963.
=> Fix ODR violation in pathing code

rust/Cargo.lock
Should close #1968
The Android built failure should be looked at separately.
=> Update getrandom and tempfile with cargo update

src/externalized/ItemModel.cc, src/externalized/ItemModel.h, src/game/JA2Types.h, src/game/Strategic/Map_Screen_Interface_Map_Inventory.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/Item_Types.h, src/game/Tactical/Items.cc, src/game/Tactical/Items.h, src/game/Tactical/LoadSaveObjectType.cc, src/game/Tactical/Rotting_Corpses.cc
The member OBJECTTYPE::ubWeight is kept for savegame compatibility but no longer used; instead the object's current weight is calculated when needed.
Converting from hectograms to kilograms and pounds gave me a headache so the new function Weight() returns the object's weight in grams (currently the return value is always a multiple of 100).
=> Allow total weight of objects to exceed 25.5 kilograms

src/game/Tactical/Turn_Based_Input.cc
Pressing Ctrl+L to go to the Load screen during the AI's turn is a Straciatella feature not present in Vanilla, however cancelling the load screen did not work, it took you to the Options screen instead.
Fixes #1972.
=> Fix bug returning to the game screen from the load screen

src/game/MessageBoxScreen.cc, src/game/MessageBoxScreen.h
• Pass the message box by const reference. A missing &
caused us to do unnecessary string copies in ~70 places.
• Remove the unused default message box style. This style
could only be reached by doing something really silly
like DoMessageBox((MessageBoxStyleID)9, ...).
• MakeButton is now a lambda so we do not have to always
pass the same constant arguments to it
• Combined the six seperate callback handlers that only
differed by their return value into one common handler
If you are wondering what the deleted default style looked like, here it is:
=> Clean up MessageBoxScreen a bit

src/game/Strategic/Assignments.cc
Currently when a task is assigned, equipped one-handed guns are put in a pocket when swapped with a toolkit or medkit, which then makes it a bit of a hassle to open every soldier's inventory and equip them back. The proposed enhancement puts items in the secondary hand so that we can quickly swap them by right clicking on team panel in tactical mode.
=> Put the content of the primary hand in the secondary (not a pocket) when assigning doctor/repair tasks 

src/sgp/Logger.h, src/sgp/Types.h
Perfect forwarding of the variadic arguments should reduce the number of Coverity's COPY_INSTEAD_OF_MOVE defects.
Added [[maybe_unused]] to tell the Compiler that it is okay that isAssert is not used when ENABLE_ASSERTS is not defined.
Since these changes require a complete recompilation of almost all C++ code I used the opportunity to mark some functions in Types.h as constexpr.
=> Make our tools less unhappy about LogMessageST

src/game/Strategic/MapScreen.cc
A one-character typo in #1479 disabled yellow highlighting of the soldiers in a selected sector.
=> Fix disabled yellow highlight of those in the selected sector

src/game/TileEngine/WorldDef.cc
PROBLEM (in vanilla too)
Structure-destroying explosions make nearby roof tiles obstacle-blocked if occupied by soldiers at the moment of the explosion.
1. Load this savefile: https://disk.yandex.ru/d/NhSrPal-hll_zw
2. End turn
3. The enemy soldier will attack Gus with a LAW, destroying some ground level structures in the process:
(LAW missiles going through roofs unimpeded is an unrelated bug)
4. Within a certain radius the roof tiles occupied at the moment of the explosion by soldiers will be blocked for travel:
5. The same story will be with destruction by TNT, for example.
SOLUTION
Add a check excluding anything flagged STRUCTURE_PERSON (which includes monsters and bloodcats, by the way) from explosion-induced travel cost recompilation.
TESTING
People structures …
=> Fix tile path-blocking on roofs due to nearby explosion

src/game/Tactical/Handle_UI.h, src/game/Tactical/Interface_Dialogue.cc
Remove unnecessary include of magic_enum.hpp
Also fixes use of wrong version of assert which could cause a compilation failure if nothing includes cassert.
=> Fix building without magic_enum

src/externalized/strings/EDT.h, src/externalized/strings/IEDT.h
Apparently MSVC's STL does not like how we use initializer_list so see if we can replace them with vectors to get a working build.
=> Attempt to work around crashes with the MSVC build

src/game/SaveLoadGame.cc
Closes #292
PROBLEM
In relation to the following code:
```c++
void ResetMilitia()
{
if( gfStrategicMilitiaChangesMade || gTacticalStatus.uiFlags & LOADING_SAVED_GAME )
{
...
}
}
``` 
1. The value of gfStrategicMilitiaChangesMade is not stored in savefiles and not reset on savegame load, allowing it to be "inherited" either from other playthroughs or from the default FALSE value set on game launch.
2. There is no execution path where (gTacticalStatus.uiFlags & LOADING_SAVED_GAME) is TRUE, because:
```c++
/* CJC January 13: we can't do this because (a) it resets militia IN THE
* MIDDLE OF COMBAT, and (b) if we add militia to the teams while
* LOADING_SAVED_GAME is set, the team counters will not be updated properly!
*/
//	ResetMilitia();
``` 
Steps to reproduce the case, when …
=> Fix militia resetting their positions during battle or not showing up in the tactical screen

src/game/Tactical/Soldier_Profile.cc
Fixes an obvious typo that's been present since vanilla.
Closes #1956.
=> Fix Larry's profiles swapping incorrectly

src/game/Tactical/FOV.cc
In debug builds (when _DEBUG is defined) you can press Num Lock to display a soldier's FOV when he is moving. The problem is that he JA2 clock is no longer updated on a seperate thread so you can't busy loop on GetJA2Clock() to freeze the program for a constant duration, it would just enter an infinite loop. Use SDL_Delay() instead.
=> Fix hang while displaying FOV debug info

src/game/Strategic/Map_Screen_Interface_Map.cc
This function can sometimes be called with an invalid sector which caused an assertion failure and a incorrect read of the SectorInfo array. Fixes #2005.
=> Make IsTheCursorAllowedToHighLightThisSector() more robust

src/game/Tactical/Handle_UI.cc
PROBLEM
1. Jumping over the base tile of a soldier is too tricky. First you have to trigger blocked path cursor over their legs, then move it to the jump location in the pattern shown in this pic:
2. You can't even jump over someone facing west, because their "extended" structure is flagged as passable, so there is no blocked path cursor to take advantage of:
3. There is no block test for jumper's source tile, only for destination, which allows you to phase through walls and doors:
SOLUTION
Add a check that takes into account selection cursor.
Add a test for jumper's source tile block.
=> Fix jump location validation

src/game/Strategic/Auto_Resolve.cc
Closes #1228
PROBLEM
The global variable gubCreatureBattleCode is not reset properly after an auto-resolved battle with the town-attacking crepitus.
1. Load this savefile: https://disk.yandex.ru/d/pA6Ay02ON3BDgQ
2. Advance time until an auto-resolved Drassen creature attack happens (since it's random, you'll want to reload if the night passes without an attack)
3. Go to the Drassen mine. It'll be empty all the way down.
4. Alternatively you can load the savefile from the original issue ([savegame.tar.gz](https://github.com/ja2-stracciatella/ja2-stracciatella/files/5245693/savegame.tar.gz)) and go to the mine there. The result will be the same.
The only ways to reset gubCreatureBattleCode: 
- Relaunch ja2.exe
- Wait for another creature attack while having your mercs in …
=> Fix empty crepitus' lair bug

src/game/Strategic/MapScreen.cc, src/game/Strategic/Map_Screen_Interface_Map.cc
Introduced by #2009. Also remove unused parameter fStationary of RenderMapHighlight(), the unused variable towns in RenderMapHighlight() and the unused macro LARGE_MILITIA_ICON_SPACING.
Fixes #2018.
=> Bug fix: underground levels no longer accessible on map screen

src/game/GameLoop.cc, src/game/MessageBoxScreen.cc, src/game/Tactical/UI_Cursors.cc, src/game/TileEngine/Interactive_Tiles.cc, src/game/TileEngine/Isometric_Utils.cc, src/sgp/Cursor_Control.cc, src/sgp/Cursor_Control.h, src/sgp/Input.cc, src/sgp/Input.h, src/sgp/Video.cc
Return the position directly as a SGPPoint instead of through a pointer or reference to SGPPoint.
=> Change signatures of GetMousePos and GetCursorPos

dependencies/lib-smacker/CMakeLists.txt, src/game/Laptop/Finances.cc, src/game/Laptop/History.cc, src/game/TileEngine/TileDef.cc, src/game/Utils/Cinematics.cc
• Default signedness of char is platform-dependent, which leads to compiler warnings while compiling libsmacker
• Assignment in TileDef should be a comparison
• PAGE_SIZE macro is already defined on some platforms
• Unused macros warnings
=> Fix several compiler warnings

.github/workflows/github-ci.yml
https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md
This is basically just for PR builds, if one wants to look at the artifacts directly. We upload to our infra in a previous step already.
=> github-ci.yml: upload-artifact@v4 requires unique names

src/game/Strategic/Map_Screen_Helicopter.cc, src/game/Tactical/Interface_Dialogue.cc, src/game/Tactical/Soldier_Profile.cc
Closes #478
Fixed (or circumvented) issues:
1. Doesn't matter, if unescorted manually or by a proximity trigger (quest completion), NPCs are always put on the north entry point after a sector reload. From now on they'll be at the exact tile the player left them, if unescorted manually.
2. There's map editor placement info for Skyrider in the airport sector, but it's ignored.
3. There's no map editor placement info for Joey in his home sector.
4. Unescort-related placement/disappearance code is a bit scattered all over the place.
=> Fix EPCs unescort functionality

src/game/TileEngine/Map_Edgepoints.cc, src/game/TileEngine/Map_Edgepoints.h
Functions SearchForClosestPrimaryMapEdgepoint and
SearchForClosestSecondaryMapEdgepoint were almost identical except for a switch statement to select the vector to use at the start of these functions. This commit moves this switch to a seperate function, which makes one copy of the search functions redundant.
=> Refactor SearchForClosestMapEdgepoint functions

.github/workflows/github-ci.yml
MacOS 11 is no longer supported since 2024-06-28. Compare the [Github docs page](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
=> Use MacOS 12 for the mac runner

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
We introduced a dependency on some functions which only become available with the Android SDK 21 (equivalent to Android 5). As Android 4 (the previous equivalent minimum version) is already > 10 years old I think this requirement should be fine (covers 99.5% of all running Android devices according to https://apilevels.com/).
=> Fix Android build by upgrading minimum Android SDK to 21

src/game/Utils/Message.cc, src/game/Utils/WordWrap.cc, src/game/Utils/WordWrap.h
LineWrap now returns a vector of utf32_buffers instead of a classic C-style singly-linked list, which makes this function easier to use and obsoletes two helper functions.
=> Change the result type of LineWrap()

src/game/Tactical/Interface_Dialogue.cc, src/game/Tactical/Interface_Dialogue.h
The amount specified in tactical-npc-action-params.json had no effect because the code used the wrong NpcActionParamsModel method (getGridNo instead of getAmount).
I moved the code to handle these two cases into a new function because HandleNPCDoAction() is the worst function in the sense of code complexity measurements.
=> Fix moddability of Walter's bribe amount

src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/ItemRange.h, src/externalized/ItemSystem.h, src/game/Editor/EditorItems.cc, src/game/Editor/Sector_Summary.cc, src/game/Laptop/BobbyR.cc, src/game/Tactical/Arms_Dealer_Init.cc, src/game/Tactical/Inventory_Choosing.cc
This changes the way items are iterated over in most of the places. `GCM` has a new method, which returns a new class called `ItemRange`, which is a range over the items vector.
It can be used where we need iteration over items instead of the loop over the item ids.
I've used this in most places where we do iterations over item ids, except for two cases:
- When the thing we are iterating over is not really the items vector but something different (e.g. the arms dealer inventory)
- When the iteration logic is not a straight forward iteration over all items.
NB: This would be a place where we actually would benefit from the C++20, as it supports ranges and views over the items vector.
=> Refactor iteration over items

src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/DefaultContentManagerUT.cc, src/externalized/DefaultContentManagerUT.h
During unit testing the file itemdesc.edt from the original game resources is not available which caused several irritiating warning messages in DefaultContentManager:: loadGameData(). This method is now virtual and overridden by the unit test content manager. The new loadGameData method simply uses an empty VanillaItemStrings instance because the unit tests do not need the actual item descriptions.
=> Fix warnings when running the unit tests

src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/ItemSystem.h, src/externalized/VanillaWeapons_unittests.cc, src/game/Laptop/BobbyR.cc, src/game/Tactical/Items.cc, src/game/Tactical/LoadSaveObjectType.cc, src/game/Tactical/Points.cc
getItem returned NULL if the item index was invalid but almost all callers assume a valid pointer.
This commit changes getitem to throw out_of_range exception and adds a new overload with the old behavior for the few cases that actually check the result.
=> Change getItem() to throw an exception in case of failure

src/game/Laptop/Mercs.cc, src/game/Strategic/Map_Screen_Helicopter.cc, src/game/Strategic/Map_Screen_Interface_Map.cc, src/game/Strategic/Meanwhile.cc, src/game/Strategic/SAM_Sites.cc, src/game/Strategic/Strategic_AI.cc, src/game/Strategic/Strategic_Mines.cc
Several ContentManager methods return a reference to a vector. Simply calling this methods with` auto v = GCM-> methodName() `creates a new copy of the vector in v but in most of this cases we simply want to read from the vector.
=> Reduce the number of unnecessary vector copies

src/game/Tactical/Arms_Dealer_Init.cc
Closes #2040.
Fixes an oversight regarding implicit conversion from signed argument -1 to the unsigned int parameter `ubDealerID`. Had no effect until #2031.
=> Fix crash on cash deposit

src/game/Tactical/PathAI.cc
Introduced in #1995
Reproducible by allowing Seargeant to leave. The last door is the sliding door on which he freezes if it's closed.
=> Fix NPCs getting stuck on diagonal travel through closed sliding door

.github/workflows/github-ci.yml
Tries to fix the disk space issues for the Android build on GitHub actions by clearing some space at the beginning of the pipeline.
=> Fix running out of disk space for Android github runner

src/game/SaveLoadGameStates.cc, src/game/SaveLoadGameStates.h, src/game/SaveLoadGameStates_unittest.cc
• return references instead of copies if possible
• avoid the use of lvalues; pass on function results
directly to other functions
• use a more efficient way to create the temporary map
or vector in SetMap and SetVector
• mark getters as const
Should hopefully also get fix CID 407869 although I believe that one is a false positive. The note about "function has been overridden by a builtin model" looks dubious.
=> Less copying in SaveLoadGameStates

src/externalized/DefaultContentManager.cc, src/externalized/content/NPCQuoteInfo.cc, src/externalized/content/NPCQuoteInfo.h, src/game/TacticalAI/NPC.cc
Also, it is not necessary to pass a MercSystem and a ItemSystem pointer to deserialize() because
ContentManager inherits both interfaces.
The code is working as is but this is currently the only warning on the Linux runner; it's nice to keep that one free of warning because it makes it easy to notice any new ones.
=> Fix sign-compare warning in NPCQuoteInfo

src/externalized/ItemModel.cc, src/externalized/ItemModel.h, src/externalized/MagazineModel.cc, src/externalized/WeaponModels.cc
deserializeName, deserializeShortName and deserializeDescription were copy & paste versions of the same code. That code was a bit backwards: it always got the fallback strings before checking if that was even necessary. If the string was overridden in JSON that string was retrieved twice.
=> Clean up ItemModel's deserializer methods

src/externalized/CalibreModel.cc, src/externalized/CalibreModel.h, src/externalized/MagazineModel.cc, src/game/Tactical/Interface_Items.cc, src/game/Tactical/Items.cc
This struct neither inherits from anything nor is it inherited anywhere so its functions don't need to be virtual.
Let the constructor do all the work of creating a new instance from JSON instead of moving all data from deserialize().
=> Clean up CalibreModel

src/game/Laptop/AIMMembers.cc, src/game/Strategic/Merc_Contract.cc, src/game/Strategic/Strategic.cc, src/game/Strategic/Strategic_Merc_Handler.cc, src/game/Tactical/Handle_Items.cc, src/game/Tactical/Merc_Hiring.cc, src/game/Tactical/Morale.cc, src/game/Tactical/Overhead.cc, src/game/Tactical/SkillCheck.cc, src/game/Tactical/Soldier_Ani.cc, src/game/Tactical/Soldier_Profile.cc, src/game/Tactical/Soldier_Profile.h, src/game/Tactical/Soldier_Profile_Type.h
`GetFirstBuddyOnTeam()` returns merc ID instead of expected index for the array of friends. As a result, mercs who are joining or renewing the contract ignore friends on the team if there are also enemies. The bug is not present in vanilla.
Steps to reproduce (using Grizzly who is friends with Bull and enemies with Dr. Q): 
1. Hire Dr. Q and make sure he's in Omerta
2. Attempt to hire Grizzly. He will decline and mention Dr. Q as the reason.
3. Hire Bull and make sure he's in Omerta
4. Attempt to hire Grizzly. He will decline and mention Dr. Q as the reason. The correct behavior: he must agree and mention Bull as the reason
Additionally: code that's unreachable because `hated` by design cannot be more then 2. Doesn't actually affect anything except 
code readability.
=> Fix mercs refusing to join/renew contract

src/game/TacticalAI/Attacks.cc
This code did the opposite of what the comment says and what is intended: the search for gridnos should continue if the current one is not in the excluded list yet.
=> Fix logic error introduced in the previous commit

src/game/TileEngine/RenderWorld.cc, src/game/TileEngine/WorldDef.h
Merging the three arrays RenderFX, RenderFXStartIndex and g_render_fx_layer_flags has two advantages:
1. It indicates the close relationship of these arrays and how they control the program flow in Render().
2. This makes it more obvious that copying values from RenderFX and RenderFXStartIndex to temporary arrays at the start of Render() was not necessary. We can just look up these values in the constant table when needed.
Seeing that this data is constant also made it easier to see that we do not need to initialize various variables for every levelnode because they will stay constant while Render() processes an entire render layer.
=> Merge three arrays that control Render()

assets/externalized/smoke-effects.json, rust/stracciatella/src/schemas/yaml/smoke-effects.schema.yaml, src/externalized/ContentManager.h, src/externalized/DefaultContentManager.cc, src/externalized/DefaultContentManager.h, src/externalized/ExplosionAnimationModel.cc, src/externalized/tactical/CMakeLists.txt, src/externalized/tactical/SmokeEffectModel.cc, src/externalized/tactical/SmokeEffectModel.h, src/game/Tactical/LOS.cc, src/game/Tactical/OppList.cc, src/game/Tactical/Overhead.cc, src/game/Tactical/Soldier_Control.cc, src/game/TacticalAI/AIUtils.cc, src/game/TileEngine/Explosion_Control.cc, src/game/TileEngine/Explosion_Control.h, src/game/TileEngine/SmokeEffects.cc, src/game/TileEngine/SmokeEffects.h
Still needs some testing, but should be about done. This externalizes `SmokeEffectModel` from code, which represents the effects of smoke (e.g. Smoke, Teargas).
=> Extract smoke effects

src/game/Strategic/Auto_Resolve.cc
Bug was introduced in #2044. Before that PR much of the code in this function was inside an `if` block that wasn't needed and when I removed the `if` and unindented the code I placed a closing curly bracket at the wrong location.
Fixes #2068. While looking at this code again I also noticed that iNumFaces is redundant.
=> Fix null pointer deref in RemoveAutoResolveInterface

src/externalized/WeaponModels.cc, src/externalized/WeaponModels.h
Instead of passign the strings for name, short name and description around from constructor to another we now initialize the WeaponModel member variables after we have constructed the object.
This should cut down the enormous amount of complaints Coverity (COPY_INSTEAD_OF_MOVE) has about WeaponModels.cc.
This file is currently responsible for the most CIDs by far with 103. This solution seems better to me than adding lots of `std::move` everywhere.
=> Change the way we initialize WeaponModel instances

src/game/TileEngine/Structure.cc, src/game/TileEngine/Structure.h, src/game/TileEngine/Structure_Internals.h, src/game/TileEngine/TileDef.cc, src/game/TileEngine/TileDef.h, src/game/TileEngine/Tile_Surface.cc, src/game/TileEngine/WorldDef.cc
The motivation behind this PR is not a mere puritanical "raw ownings pointers are bad, modern C++ should use RAII" but rather to improve the debug experience with these structs. It is just more productive when your debugger can tell you that `pAuxObjectData` is a vector of 12 elements and not just a pointer to an unknown number of elements, etc.
For example, `gpStructureFileRefs ` in the current code simply points to the first elements of a linked list that usually has more than 300 elements. `gpStructureFileRefs->pNext->pNext->pNext->pNext...` is not fun at all and just a waste of time. The map that replaces this pointer is easy to browse and additionally tells you the filename of the JSD.
=> Clean up STRUCTURE_FILE_REF and TILE_IMAGERY

src/game/TileEngine/Explosion_Control.cc
Fixes #2083
For some explosions, that do not have an explosive associated with them, we got a null pointer from `getExplosive`. Previously it used the first index in `explosion_info`, which did no damage or anything.
=> Fix corpse explosion crashing the game

src/sgp/Video.cc
Older versions of SDL_BlitSurface did not always handle the case where the source and destination surface are the same correctly. This bug has been fixed quite a while ago and is included in SDL 2.0.5, which is coincidentally also our current minimum requirement so we can remove the workaround where we use a temporary surface and blit twice.
This makes scrolling a bit faster and we no longer have to allocate at least 600 KB every time we scroll.
=> Remove workaround for an old SDL bug in ScrollJA2Background

src/game/GameLoop.cc, src/sgp/Video.cc
RefreshScreen was originally intended to force a refresh of all regions that were marked as invalid at the time. On systems more modern that the original minimum system requirements that resulted in hundreds of FPS and high CPU usage so it got a limiter. However, this meant that in some situations the screen was not updated often enough, resulting in somewhat choppy animations or content that might not show up at all.
Two examples of where you should notice a difference, especially if you have a rather low FPS limit in game.json:
1. The transition from the map screen to the Laptop is now a bit more fluid.
2. The message box that simply says "Saving..." whenever we save the game should now always appear; before it was often not visible at all.
=> Move the FPS limit out of RefreshScreen to a separate function

src/game/TileEngine/Isometric_Utils.cc, src/game/TileEngine/Isometric_Utils.h
There are about 60 places where DirectionInc is called with one of the WorldDirections enumerators which always yields the same result. This result can already be computed at compile time, resulting in code that is a tiny bit smaller and faster.
=> Add a constexpr overload for DirectionInc

CMakeLists.txt, dependencies/lib-string_theory/CMakeLists.txt
This informs the compiler not to generate warnings for code in this header. This change was brought about by clang's complaints about miniaudio.h.
=> Mark include directories of dependencies as SYSTEM

src/game/SaveLoadGame.cc, src/game/SaveLoadGame.h, src/game/SaveLoadGameStates.cc, src/game/SaveLoadGameStates.h, src/game/SaveLoadGame_unittest.cc
The size of ste SaveStates was written to the file header at the start of SaveGame but since #2051 was checked in, saving the strategic status added more data to those SaveStates. The result of this bug was that SaveGameInfo could no longer determine the mods activated for a save, resulting in wrong tool tips on the load screen and wrong warnings about a mismatch in the activated mods.
=> Bug fix: size of SaveStates in the save game header

src/game/Utils/WordWrap.cc
Because the width variable was never updated this function didn't really do anything. Fixes #1491.
=> Fix ReduceStringLength()

src/game/Strategic/Creature_Spreading.cc, src/game/Strategic/Creature_Spreading.h
Just initialized to 0 but never modified or read anywhere.
=> Remove four unused variables in Creature_Spreading

src/game/SaveLoadGame.cc
MSVC correctly points out that the combination of unary minus and an unsigned integer does not do what one might expect; the result is still positive. In our case we are passing a huge number close to 2^32 to seek() and the only reason we are getting the expected result is that seek() interprets this number as a small negative number. If we would ever modernize seek's first argument to int64 this would break.
=> Fix warning C4146 in SaveGameInfo

src/sgp/Font.cc, src/sgp/Font.h, src/sgp/SGP.cc
Both lines of this function are useless:
A NULL default font would just cause failed assertions and there is nothing in the code base that wants to print to the back buffer.
Also use the SGPFont typedef where appropriate.
=> Remove InitializeFontManager

src/externalized/DealerInventory.cc
getItemByName takes a reference to ST::string, which is already the type of the variable 'it'. The old code did a round trip ST::string -> C string -> ST::string.
=> Avoid some conversions from and to ST::string in DealerInventory

.ci/ci-setup.sh
This SDK is already preinstalled on the Github runners using Ubuntu.
Let's test if this completes successfully.
=> Do not install the Google Cloud SDK on Ubuntu

src/game/Tactical/Overhead.cc
Not sure if that would ever happened, as a robot cannot have a gas mask equipped, but it was detected by Coverity as a possible null pointer dereference if the first condition was evaluated as `true`.
=> Fix possible null pointer dereference when ignoring smoke effects

src/game/Tactical/Animation_Data.cc
Some of the problems with the prone stance:
1. You can go prone when closely facing a structure that is **whole-tile** blocking, but not when facing north. And, if facing away, not when facing south or east:
(reminder: the game world north is the direction Dynamo is looking in on the first pic)
2. Crawling along the south (and only south) side of such structures looks like this:
Crawling along all other sides moves the char instantaneously - no stance change needed.
3. None of the above happens with walls and doors. Instead, they have a clipping problem that results in soldiers affecting or being affected by things illogically, like obstructing paths or taking damage with one part of their structure phased through a wall:
The only reason it's not very game-breaking is because that part is …
=> Fix prone positioning

src/game/Credits.cc, src/game/Credits.h, src/game/GameInitOptionsScreen.cc, src/game/GameInitOptionsScreen.h, src/game/ScreenIDs.h, src/game/Screens.cc, src/game/Utils/MapUtility.cc, src/game/Utils/MapUtility.h
These headers only contained a single definition for a ScreenHandle function. In their place we are now using a function template in ScreenIDs.h.
=> Remove three header files

src/game/MessageBoxScreen.cc, src/game/Strategic/MapScreen.cc, src/game/Strategic/Map_Screen_Interface.cc, src/game/Strategic/Map_Screen_Interface.h
This removes the secret handshake between the message box screen and the map screen where the former asked the latter to redraw itself without the cursor interaction over the Arulco map before rendering itself. Some code change in the past (I did not investigate which) broke this brittle concept and made some buttons and the map coordinates disappear.
Now the map screen redraws itself without the mentioned interaction one last time before handing control over to the message box screen.
The function `HandleTacticalUILoseCursorFromOtherScreen` which does something similar for the game screen is also a bit suspect but unless someone can point to an actual problem with it I'd rather not touch it.
Fixes #2119.
=> Fix missing buttons in MapScreen

.github/workflows/github-ci.yml
Trivial stuff, one other cases is already using this runner.
=> github-ci: macos-12 is getting sunset, switch to latest

src/game/TacticalAI/AIUtils.cc
Found by valgrind. If a merc and his team have no idea about an opponent's location yet, `ClosestKnownOpponent` calls `SameBuilding` with sGridNo == NOWHERE, which uses it unchecked an as an index to the `gubBuildingInfo` array.
The closely related function `ClosestReachableDisturbance` already checks for this so it is not affected.
=> Fix out of bounds read in SameBuilding

src/game/TileEngine/WorldDef.cc
Reuse `RecompileLocalMovementCostsFromRadius` to implement this function; they are basically identical except that the former uses a fixed 'radius' of 4.
=> Simplify RecompileLocalMovementCosts

src/game/TileEngine/Render_Dirty.cc, src/game/TileEngine/Render_Dirty.h
The only user of this function was the old FPS code.
=> Remove SetVideoOverlayText

src/game/SaveLoadGame.cc, src/game/Utils/Animated_ProgressBar.cc, src/game/Utils/Animated_ProgressBar.h
This function was only used in code inside JA2BETAVERSION blocks, apparently to give the developers a way to observe the loading progress. Not only is that code gone now, on modern computers those messages would disappear far too fast to be usable.
This also makes two flags and their related code redundant.
=> Remove SetProgressBarTextDisplayFlag

src/game/Tactical/Overhead.cc, src/game/Utils/Music_Control.cc, src/game/Utils/Music_Control.h
Looking back at the original sources it seems this variable never did anything at all.
=> Remove gfForceMusicToTense

src/game/Laptop/History.cc, src/sgp/Font.cc, src/sgp/Font.h
The three column headers were all supposed to be centered but the 'Event' header was not since the the vanilla days.
The imminent cause of this bug is almost certainly a case of copy & paste and then forgetting to adjust the arguments but I believe the real underlying problem is the text API which makes this often needed task far more cumbersome to use than necessary:
The first method is to use FindFontCenterCoordinates or FindFontRightCoordinates followed by MPrint. This method requires passing several arguments twice.
The second method is the DrawToScreen function. This is just one call but it doesn't respect the currenly active font and colors and instead requires the caller to always pass in this information.
For this reason this commit adds a new MPrint overload that takes an …
=> Properly center the history table header columns

src/sgp/Font.cc, src/sgp/Font.h
The new functions cannot be marked noexcept because another function it calls indirectly (SubRegionProperties) can potentially throw.
=> Address new coverity issues caused by the IAlignment code

src/game/Laptop/EMail.cc, src/game/Laptop/Finances.cc, src/game/Laptop/IMP_Finish.cc, src/game/Laptop/IMP_Voices.cc, src/game/Laptop/Laptop.cc, src/game/Laptop/Personnel.cc, src/game/Strategic/Game_Clock.cc, src/game/Strategic/Map_Screen_Interface_Bottom.cc, src/game/Tactical/Interface.cc, src/game/Tactical/Interface_Dialogue.cc, src/game/Tactical/Interface_Panels.cc
Achieves the same result with less boilerplate code.
The code in `Email.cc` was particularly weird and passed in nonsensical values for the height. This only worked because the computed y value was just discarded.
=> Use the new alignment functions in a couple of places

src/sgp/HImage.cc, src/sgp/HImage.h, src/sgp/VSurface.cc
In its original form `CopyImageToBuffer` supported copying compressed data to a surface. It lost that ability long ago apparently because it was not used and now this function is just an elaborate way to copy raw data from a `SGPImage` to a `SGPVSurface`.
`SDL_ConvertPixels` can do this copy just as well which allows us to remove `CopyImageToBuffer` and its helper functions.
The loading screens and the map of Arulco on the map screen are among the users of this function if you want to verify that this approach works.
=> Use SDL to simplify AddVideoSurfaceFromFile

src/externalized/DefaultContentManager.h, src/externalized/IGameDataLoader.h
Apparently class IGameDataLoader was supposed to be an interface definition but because its only function is not declared virtual this is really a class without any data members and a declaration for a function that does not exist anywhere.
The actually existing and used readJsonDataFile is a non virtual member function of DefaultContentManager.
=> Remove IGameDataLoader.h

src/game/TileEngine/Render_Fun.cc, src/game/TileEngine/Render_Fun.h
This can be triggered by the Night Ops map for H14, which has buggy room information data.
It's a bit more code than strictly necessary but I really dislike the MAPROWCOLTOPOS macro with its use of  0xFFFF to indicate a problem with its input arguments.
=> Fix possible OOB crash in SetRecalculateWireFrameFlagRadius

src/game/Laptop/EMail.cc, src/game/Laptop/Files.cc, src/game/Laptop/Finances.cc, src/game/Laptop/History.cc, src/game/Laptop/Laptop.cc, src/game/Laptop/Laptop.h, src/game/Laptop/Personnel.cc
This video object is needed by the main Laptop code and gets loaded when the Laptop screen is entered. Nevertheless several sub screens had their own copy of this file without any good reason; now these screens also use the already existing instance.
=> Load the Laptop title bar graphic just once

src/game/Laptop/AIMMembers.cc
EnterAIMMembers always loaded this file but this vobject never got used. CreateAimPopUpBox loads its own copy of the file when it is actually needed.
=> Remove unused VObject

src/sgp/VObject_Blitters.cc
• Blt8BPPDataTo16BPPBufferTransShadowZNBClip was using the wrong comparison operator (<= instead of <)
• Blt8BPPDataTo16BPPBufferTransShadowZClip was accessing the 16-bit Z Buffer as if it was and array of 8-bit values.
Both are not implemented as instantiations of a shared function template to ensure they don't diverge again.
• Blt8BPPDataTo16BPPBufferTransShadow and Blt8BPPDataTo16BPPBufferTransShadowZ multiplied their indices into arrays by 2 as the result of a mistranslation of the original x86 code.
I am not sure how I feel about this PR. Code inspection suggests these changes should be correct, but as I wrote in #2146, I can't to trigger these blitters except Blt8BPPDataTo16BPPBufferTransShadowZNBClip, which is the least problematic of the four. Here, all that can happen that one …
=> Fix four blitters

src/sgp/VObject_Blitters.cc
This blitter used the variable px in places where it should have used PxCount. Another bug was that the src pointer must always be incremented, no matter if we write to the Z buffer or not.
=> Fix mixed up variables in Blt8BPPDataTo16BPPBufferTransShadowZClip

.github/workflows/coverity-scan.yml, .github/workflows/github-ci.yml
Let's see if it all still builds. The image got removed last week, triggering a scheduled coverity runner failure.
=> github: ubuntu-20.04 was removed, bump used runner

.github/workflows/github-ci.yml, dependencies/lib-gtest/getter/CMakeLists.txt.in, dependencies/lib-string_theory/builder/CMakeLists.txt.in
I currently cannot build the project with my version of CMake (4.0.0) anymore. It results in the following error:
```
CMake Error at _bin/lib-gtest/src/CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
The same happens for `string_theory`.
This PR upgrades `gtest` and `string_theory` to their most recent versions, which fixes the issue.
=> Upgrade dependencies for CMake 4

src/game/TileEngine/Physics.cc
This should close #2154. Seems like rocks reach this code path as well and we need to check whether the item is an explosive before accessing explosive properties such as light effect, etc.
=> Check if item is explosive before getting explosive effects

src/game/TileEngine/Structure.cc
Detonate a bomb on this tile right at the beginning of the game in Omerta:
Crash will happen with the message:
`[ERROR] sgp\SGP.cc: Game has been terminated due to an unrecoverable error: Failed to add node to world`
It will occur with almost any corner consisting of walls placed in this way:
The reason is slightly wider walls used to place adjacent walls like this:
They take up two tiles thus being able to "overlap" with other walls. Since they are purely for visual effect we can easily make a special exception for them.
The bug was introduced by [this](https://github.com/ja2-stracciatella/ja2-stracciatella/commit/119a1d172852ca503e1dda10435e4430af73a134) ancient commit.
=> Fix crashing on destruction of a corner wall

src/game/Tactical/Handle_Doors.cc
Introduced by #2166
`ubDoorHandleCode` not reset properly for structures other than doors.
Closes #2187
=> Fix broken interaction with boxes

src/game/GameLoop.cc
1. In `ja2.json` substitute `game_dir` value with UB dir:
```javascript
"game_dir": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Jagged Alliance 2 Gold Unfinished Business",
``` 
2. The game will crash without giving a useful error text because it tries to create an error save file and fails since there cannot be game world loaded while in main menu.
This fix makes it bypass the error save file creation (if in main menu) and correctly output:
`[ERROR] sgp\SGP.cc: Game has been terminated due to an unrecoverable error: openGameResForReading: Vfs_open "loadscreens/ja2logo.sti": entity not found`
before the crash.
=> Fix exception handling in main menu

.ci/ci-functions.sh, .ci/ci-setup.sh, .ci/upload-artifact.sh, .github/workflows/github-ci.yml, cmake/toolchain-macos.cmake, src/launcher/CMakeLists.txt
#2099
saves:
- ~15s by not building tar any more on linux
- ~60s by not building fltk on mac
- ~1s by not building gtest on mac
Also fixes too new python on the mac runner and CI_TARGET being ignored.
=> Make some Github runners do less work

src/game/Tactical/Handle_Doors.cc, src/game/Tactical/Handle_UI.cc
Introduced by #2166 
1. In real-time press the lockpick button in the door menu
2. Right away before the lockpicking action has been completed hover the cursor over the door
3. The lockpicking will be replaced with the ordinary door opening action
Closes #2192
=> Fix lockpicking being overridden with opening on cursor hover over door

src/game/Tactical/Handle_Items.cc
Conditions for reproduction:
1. Trigger an item-giving quote. E.g. Mary's ("This is all the vacation money we have[...]").
2. WHILE the item-receiving char is BOTH visible to the giver (Mary) and moving....
3. ... end the quote (by clicking on it or waiting for it to finish).
Closes #2194
=> Fix infinite UI lock on item-giving action

dependencies/lib-fltk/builder/CMakeLists.txt.in
This should fix the windows build hopefully. Unfortunately on my machine (Manjaro) building with `-DLOCAL_FLTK_LIB=ON` still fails, because it complains about undefined references to XLib functions. I have the same behavior for FLTK `1.3.8` though, so that is not a new regression.
=> Update included FLTK version

src/sgp/SGP.cc, src/sgp/Video.cc, src/sgp/Video.h
Required by some video drivers to avoid ugly artifacts in the border area.
=> Call RenderClear on every frame again

CMakeLists.txt, dependencies/lib-gtest/CMakeLists.txt, src/launcher/main.cc
MinGW/MSYS2: deprecate mingw-std-threads is no longer needed and prints annoying compiler messages.
ja2-launcher could not resolve the HANDLE symbol and that need the windows.h inclusion.
=> MinGW/MSYS2: deprecate mingwstd_threads package. Fix ja2-launcher.

src/externalized/mercs/MercProfile.cc
From Discord:
https://discord.com/channels/348449397308391426/883987395484200970/1423893658863665153
> Merc relations are not working. Ex: Grizzly does not bark negatively when dropped into Omerta with Dr. Q, Fox does not when dropped in with Steroid, Steroid with Igor and so on. Mercs also neither gain nor lose morale when spending time with liked or disliked mercs...
Given the severity this calls for a release update.
=> Fix mercs' opinions and relations not extracting from prof.dat
